ossf/fuzz-introspector

post-processing/fuzz_html.py
It's a hassle to maintain both and we are really only interested in the
colored calltree. If at some point we need to have one that is opaque
then we can always introduce the logic in a manner that integrates with
the colored calltree.
=> Remove support for non-colored calltree

oss_fuzz_integration/build_patched_oss_fuzz.sh
We need this to differentiate local vs cloud build. When making the cloud build, the local variable CLOUD_BUILD_ENV is set so all.sh is skipped.
As I tested this should work and not break the local build.
cc @oliverchang
=> make all.sh conditional to avoid it in cloud build

llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
Fuzzer can be compiled in different directories. We have to make sure the profiles are created in a pre-determined location to let compile script be able to find and use them.
Fixes issues like [this](https://github.com/ossf/fuzz-introspector/issues/43#issuecomment-1051258838)
=> Prefix all profile log files

post-processing/fuzz_data_loader.py
Needed this to have the name of the suggested fuzz target demangle.
P.S: I've seen your comment @DavidKorczynski, this is correct behavior as this function is only called by [analysis_synthesize_simple_targets](https://github.com/ossf/fuzz-introspector/blob/5bc9bc1d0e80d01a7675f2a99e96b2eb8da57bc8/post-processing/fuzz_analysis.py#L380) on each suggested fuzz target. So, it is  essentially collecting reached_by_fuzzers including the suggested fuzzers.
=> demangle the new fuzzer name before adding to list

post-processing/styling/custom.js
If a table has the column "source code lines" it will sort by that table descending.
Closes https://github.com/ossf/fuzz-introspector/issues/45
=> Sort table by source code lines

post-processing/fuzz_html.py, post-processing/styling/styles.css
The colormap would not fit inside the html body and would be wider than it. This fits it inside the body so that you don't have to scroll to view it.
=> Fit colormap in html body

post-processing/styling/styles.css
Moves the search field and the pagination navigation of all tables to the left side.
Fixes https://github.com/ossf/fuzz-introspector/issues/56
=> Reorganize tables

post-processing/fuzz_html.py
Fixes the first issue in https://github.com/ossf/fuzz-introspector/issues/73
=> Make calltree fully expanded by default

post-processing/fuzz_analysis.py, post-processing/fuzz_cfg_load.py, post-processing/fuzz_cov_load.py, post-processing/fuzz_data_loader.py
The function names extracted from the node destination and the coverage
profile were not the same. The problem was one was normalised and the
other was not, which resulted in one having whitespace and the other
not. This fixes it.
Ref: https://github.com/ossf/fuzz-introspector/issues/74
=> post-process: fix calltree issues

llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
=> llvm: add more default functions to ignore

oss_fuzz_integration/oss-fuzz-patches.diff
The default config for excluding certain functions is now always
happening unless otherwise told.
=> oss-fuzz: remove config env var as no longer neeeded

oss_fuzz_integration/oss-fuzz-patches.diff
Instead of changing the existing Dockerfile to not download
fuzz-introspector, simply remove the downloaded version. This enables us
to avoid updating the checkout commit each time oss-fuzz is bumped.
=> oss-fuzz: make patch a bit more permanent

post-processing/fuzz_html.py
With coverage reports by target produced on OSS-Fuzz side, we can use it in "Fuzzer details" section.
It makes sense for the project overview report to link to overall coverage, so I did not change it.
=> Use per-target coverage report in fuzzer details

post-processing/styling/calltree.js
Scrolls the calltree to a specific node if the parameter "scrollToNode" is given in the URL, eg: "?scrollToNode=00500"
=> Add feature to link to specific node in calltree

post-processing/fuzz_analysis.py, post-processing/fuzz_html.py, post-processing/fuzz_utils.py
#160 was incomplete. This one does the actual job of setting call-site urls using per-coverage url.
=> Using per-target coverage url in calltree

post-processing/fuzz_html.py, post-processing/styling/custom.js
This creates a json object for the "Project functions overview" table and the "All functions overview".
The rows a of the tables are then added to the table in the frontend instead of the backend.
The goal is to improve page load speed and avoid issues like: https://github.com/ossf/fuzz-introspector/issues/155. Locally the report page loads much faster for me. The two tables still take a couple of seconds to add the data, but the loading is now isolated to the tables instead of blocking the whole report page. If this becomes a problem for large projects, the UX can be further improved by adding a loader for each table.
There is a bit of refactoring to do as a result of this PR, but it would be good to test this out a bit before going too far down this way of improving page load speed. The …
=> Load table data from frontend for 2 tables

post-processing/styling/custom.js
The "view list" collapsible in the "All functions overview" was removed in https://github.com/ossf/fuzz-introspector/pull/163.
This PR brings it back.
=> Bring back view list collapsible in table

oss_fuzz_integration/oss-fuzz-patches.diff
This is no longer used by OSS-Fuzz as fuzz-introspector removed it
Ref: https://github.com/google/oss-fuzz/pull/7497
=> oss-fuzz: sync patch: remove git_repo_url usage

oss_fuzz_integration/oss-fuzz-patches.diff
This is now upstreamed.
Ref: https://github.com/google/oss-fuzz/pull/7502
=> oss-fuzz: remove patch for coverage_url

post-processing/fuzz_analysis.py
Remove the requirement of fuzz blockers not blocking "higher up code".
The problem with it is that sometimes a blocker will be in the middle of
a sequence of red nodes and this is fairly counter-intuitive. Having
looked at more reports now it seems to make more sense to simply focus
on sequences of red nodes and just identifying blockers by looking for
transition points.
=> post-process: refine fuzz-blocker definition

llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp, post-processing/fuzz_analysis.py, post-processing/fuzz_data_loader.py
Several OSS-Fuzz build logs are of many gigabytes (10+), much of which
is only useful for debugging. This silences many of these by default.
=> reduce logging across project

post-processing/fuzz_html.py
Display visual warning in the event that covered funtions (at runtime,
from coverage analysis) is larger than the functions deemed reachable by
the static analysis component. We could insert more warnings other
places, i.e. start to enforce a "certainty of analysis" for each
analysis.
Ref: https://github.com/google/oss-fuzz/issues/7593
=> post-process: display visual warning if reachability may be off

post-processing/analyses/fuzz_calltree_analysis.py, post-processing/styling/calltree.js, post-processing/styling/styles.css
Moves the expand/collapse symbol to the left side.
=> calltree: restructure html

post-processing/analyses/fuzz_engine_input.py, post-processing/fuzz_cfg_load.py, post-processing/fuzz_constants.py, post-processing/fuzz_utils.py, post-processing/main.py
Ref: https://github.com/ossf/fuzz-introspector/pull/237
Adds it so the fuzz_engine_input analysis runs without generating any HTML for the HTML report, but instead creates a file called `fuzz-introspector-engine-input.json` with data for the fuzzers.
A few points:
- the file `fuzz-introspector-engine-input.json` is not guaranteed to be there
- it is not guaranteed that there is an entry for each fuzzer in the `fuzzers` section
- c++ function names are mangled (I assume this is what libfuzzer needs)
Besides this, the json file is super simple and intuitive:
htslib:
```
{
"fuzzers": {
"hts_open_fuzzer": {
"focus-function": "view_sam"
}
}
}
```
libdwarf:
```
{
"fuzzers": {
"fuzz_init_path": {
"focus-function": "dwarf_object_init_b"
},
"fuzz_init_binary": {
"focus-function": …
```
=> engine-input: write to file

post-processing/fuzz_analysis.py, post-processing/fuzz_cov_load.py
Function names are not normalised when put in the coverage map. They are
in fact demangled.
Fixes: https://github.com/ossf/fuzz-introspector/issues/249
=> post-process: dont normalise coverage function

oss_fuzz_integration/README.md, oss_fuzz_integration/project-checker.py, oss_fuzz_integration/test_projects.sh, post-processing/fuzz_constants.py, post-processing/fuzz_data_loader.py, post-processing/fuzz_html.py, post-processing/fuzz_utils.py
Add testing set up for oss-fuzz that can automatically analyse
properties against a set of projects. This is achieved by making
fuzz-introspector write .json files with data about the run which is
then processed by the testing framework.
The testing framework has some hard-coded boundary checks on the data
for a given project. It has to be boundaries rather than fixed values
since the data may change from run to run depending on the fuzzing
results.
In order to make the check complete it needs to have hard-coded values
from a diverse set of projects, in particular both c and c++ projects.
Another benefit of this PR is that the output in json format can be consumed by other tools.
Ref: https://github.com/ossf/fuzz-introspector/issues/41
=> oss-fuzz: add proper testing set up

post-processing/analyses/fuzz_engine_input.py
Now multiple focus functions are output. Example file:
```
{
"fuzzers": {
"hts_open_fuzzer": {
"focus-functions": [
"view_sam",
"bcf_hdr_read",
"bcf_hdr_init",
"cram_read_file_def",
"possibly_expand_bam_data",
"sam_parse1",
"bgzf_read_block",
"sam_hdr_destroy",
"sam_read1"
]
}
}
}
```
The bulletpoints from https://github.com/ossf/fuzz-introspector/pull/245 still hold. Note `focus-function` was renamed to `focus-functions` in the json.
=> post-process: output multiple focus functions per fuzzer

post-processing/fuzz_cfg_load.py, post-processing/fuzz_constants.py, post-processing/fuzz_data_loader.py, post-processing/main.py
Refactoring: improving strong typing and style.
Bug fix in `correlate_binaries_to_logs` which uses an argument in
args.binaries_dir rather than the argument to the function. It only
works now because args is not wrapper in a function -- which this commit
changes.
Adds return codes as well. This is nice to have for fuzz-introspector to
communicate whether the process was successful or not.
=> post-process: refactor, bug fix and enable return codes

post-processing/analyses/fuzz_bug_digestor.py, post-processing/fuzz_analysis.py, post-processing/fuzz_cfg_load.py, post-processing/fuzz_constants.py, post-processing/fuzz_data_loader.py, post-processing/main.py
This adds a feature load in data about bugs. Next steps is to use this
in the report, e.g. displaying it in the calltree.
Ref: https://github.com/ossf/fuzz-introspector/issues/255
=> post-process: Add ability to load data about bugs

post-processing/fuzz_html.py
Currently the ordering is done by function name, which is never really
an interesting heuristic for sorting. Switching this to undiscovered
complexity such that it becomes faster to quickly identify what are the
functions that can open up for most new coverage.
=> post-process: sort all functions table by undiscovered complexity

.github/dependabot.yml
The Dependabot settings have to be enabled in the Admin section along with this.
=> Enabled dependabot for GitHub actions

llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp, post-processing/fuzz_analysis.py, post-processing/fuzz_cov_load.py, post-processing/fuzz_data_loader.py, post-processing/main.py
This PR adds these:
- Branch profiling at LLVM plugin: identify branch sides and their corresponding cyclomatic complexity
- Loading branch profile in fuzz_data_loader.py
- Loading branch coverage information in fuzz_cov_load.py
- Making the calls to branch-level blocker detection in fuzz_analysis.py
=> Add Branch profile and branch-level blocker detection

tests/python/test1/README.md, tests/python/test1/fuzz_test.py, tests/python/test2/README.md, tests/python/test2/fuzz_test.py, tests/python/test3/README.md, tests/python/test3/fuzz_lib.py, tests/python/test3/fuzz_test.py, tests/python/test4/README.md, tests/python/test4/fuzz_lib.py, tests/python/test4/fuzz_test.py
Adds Python test cases such that once these are analysed properly we
have basic support for python.
Step 1 of Python target integration
=> tests: add python targets

oss_fuzz_integration/test_projects.sh, post-processing/main.py
- Adds fio and tarantool to being monitor for successful builds (Ref:
https://github.com/ossf/fuzz-introspector/issues/278)
- Ensures the report command succeeds
=> oss-fuzz: extend testing infra

post-processing/fuzz_analysis.py, post-processing/fuzz_data_loader.py, post-processing/fuzz_html.py
This provides a few minor changes and some bug fixes, which enables
reading of the Python frontend's output as is. There will have to be
further changes to make the project more friendly for having data from
sources in different languages.
=> post-processing: enable reading of Python output

post-processing/exceptions.py, post-processing/fuzz_analysis.py, post-processing/fuzz_cfg_load.py, post-processing/fuzz_data_loader.py
The post-processing logic is getting larger and makes sense to make it
more Pythonian. Switching calls to exit for python exceptions to support
this.
=> post-process: substitute exits for exceptions

frontends/python/main.py
The data is useful as is but is not the exact same as LLVM IR-extracted data, since the data-extraction is quite different in Python in comparison to LLVM IR. In Python we rely on the AST versus LLVM IR for C/C++. Will refine this later but for now it gives the same high-level meaning e.g. complexity is higher for more complex functions so it's useful for guiding the development and giving initial results.
Cross-referencing https://github.com/AdaLogics/PyCG/commit/cf66667825527ec649fd1f424ade1516ccc824f8
=> frontends: python: add some more data collection 

frontends/python/main.py, oss_fuzz_integration/build_patched_oss_fuzz.sh, oss_fuzz_integration/oss-fuzz-patches.diff, oss_fuzz_integration/rebuild_post_processing.sh, post-processing/analyses/fuzz_calltree_analysis.py, post-processing/fuzz_html.py
This adds a end-to-end Python support without runtime coverage. It
works, but there is one major issue, namely on how to automatically
identify relevant Python files for the AST iteration. This is coming
next.
=> oss-fuzz: add python support

oss_fuzz_integration/oss-fuzz-patches.diff
This makes it possible for build scripts to specify where relevant
Python packages are that should be considered in the fuzz-introspector
analysis.
Two example build.sh files are modified as well: pyxdg and pyyaml
=> oss-fuzz: add python package search

post-processing/fuzz_html_helpers.py
When fuzz-introspector is used on OSS-Fuzz it may be non-obvious where
to file suggestions and issues. To guide the user to the
fuzz-introspector repository include a short message in the navigation
bar directing where to file this.
=> post-processing: add link to repository issues

oss_fuzz_integration/oss-fuzz-patches.diff, oss_fuzz_integration/run_both.sh
=> oss-fuzz: enable run_both.sh for Python projects

frontends/python/main.py
Use this in the build.sh scripts to get the cg out for a given project.
=> frontend: python: enable quick cg debugging

post-processing/fuzz_cov_load.py
This works for loading a .json file as output by coverage.py. One of the
differences between this and the existing coverage logic is we need to
introduce coverage profiling by {source file : lineno} mapping. This is
in contrast to the existing logic which adds an abstraction of function
when looking up coverage data.
Next step is glueing to the rest of the report and also OSS-Fuzz.
=> post-processing: add python coverage loader logic

README.md
`texinfo` is the required dependency for command `makeinfo` when building binutils
=> Update binutils dependency

tests/simple-example-0/build_cov.sh
It seems this script is invoked in dir `work`:
https://github.com/ossf/fuzz-introspector/blob/22822c81cf2cfb0f6bd12e06ac8c14266a333ba4/README.md?plain=1#L189-L194
so it doesn't need `cd work` again.
=> Update local example script

post-processing/styling/styles.css
Modifies the layout of the "Columns" button and the search field next to it.
Preview:
=> Report page: Improve layout of button and field

post-processing/fuzz_analysis.py
Collecting the coverage hitcount diff between the blocked side and not-blocked side of each branch. My idea is that this later can be used to decide which strategy to use for unblocking.
My intuition is that if the diff is low (like 10) then setting `focus-function` can be promising.  Otherwise, for example if the diff is thousands, then the fuzzer has already tried to hit the branch and we may not get much just by focusing on that function.
=> Collect coverage hitcount diff for each blocked side

oss_fuzz_integration/build_patched_oss_fuzz.sh
Enable the option for building from scratch (i.e. clone oss-fuzz and
apply diffs) without needing to build base-image or base-clang.
=> oss-fuzz: add option for quicker build

post-processing/fuzz_analysis.py, post-processing/fuzz_data_loader.py
Reduces two places that spam the log into only being logged when in
debug mode.
=> post-process: reduce logging to debug

post-processing/analyses/fuzz_filepath_analyser.py, post-processing/fuzz_data_loader.py
Adds more information to the tables which can be used to
understand how the fuzzers target the file structure.
=> post-process: analyses: file_path: extend columns in tables

post-processing/fuzz_html.py, post-processing/fuzz_html_helpers.py, post-processing/styling/custom.js, post-processing/styling/styles.css
Adds a drop down button to select per-fuzzer coverage reports in the top left corner.
It might be a nice detail to add the coverage percentage after the fuzzer name if we have that available.
Previews:
=> Report page: add button with links to per-fuzzer coverage reports

post-processing/fuzz_html.py, post-processing/fuzz_html_helpers.py, post-processing/styling/custom.js, post-processing/styling/styles.css
Makes several low-profile improvements to the report page UI:
1. Change color of buttons for sorting tables to match the new yellow buttons.
2. Make the high-level conclusions collapsible and add the possibility to add further information.
3. Make the top "Project overview" box collapsible.
4. Minor alignment adjustments.
5. Move the title and link in the top navbar to the left side. This is slightly experimental.
Signed-off-by: AdamKorcz <adam@adalogics.com>
=> Report page: Minor improvements

post-processing/fuzz_html_helpers.py
Rename to "Project coverage" to intuitively match "Per-fuzzer coverage"
=> post-process: rename coverage report

src/fuzz_introspector/styling/styles.css
Signed-off-by: AdamKorcz <adam@adalogics.com>
Modifies the button and drop down to the select the columns in tables to align with the coverage report buttons.
Preview of new layout.
=> Report page: Restyle column selection drop down

src/fuzz_introspector/analyses/bug_digestor.py, src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/analyses/driver_synthesizer.py, src/fuzz_introspector/analyses/engine_input.py, src/fuzz_introspector/analyses/filepath_analyser.py, src/fuzz_introspector/analyses/optimal_targets.py, src/fuzz_introspector/analyses/runtime_coverage_analysis.py, src/fuzz_introspector/analysis.py, src/fuzz_introspector/html_report.py, src/main.py
Adds a static method for naming a given analysis. The idea is that it
becomes easier to extend because defining a new analysis no longer
requires specifying the name of the analysis multiple places.
This is aimed at making
https://github.com/ossf/fuzz-introspector/issues/384 more clear.
=> src: refactor analysis interface

src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/styling/calltree.js, src/fuzz_introspector/styling/styles.css
- Removes operation of setting the `padding-left` attribute of nodes in the javascript. This can be done in the backend instead for efficiency.
- Removes "Show IDX" button. This feature is deprecated.
- Makes titles in report page non-highlightable. It is not userfriendly to click the title to expand it, and then you highlight it at the same time.
=> UI: Remove operation in calltree + other small changes

src/fuzz_introspector/analyses/calltree_analysis.py
The two `.js` files serve no purpose in the calltree page.
=> Remove unused dependencies in calltree page

src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/styling/calltree.js, src/fuzz_introspector/styling/styles.css
Currently, the callsite links in table in the top of the calltree page will reload the page and then scroll to the callsite id.
This PR changes that behaviour to scroll on-page without reloading.
=> Calltree page: Make callsite links scroll on page

src/fuzz_introspector/styling/styles.css
Makes the butons on the calltree page yellow like the buttons on the report page.
=> Calltree page: Make buttons yellow

src/fuzz_introspector/styling/calltree.js
Adds an overview of the calltree in the side. It reuses the image generated in the backend.
=> Calltree page: Add overview

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp, src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/datatypes/project_profile.py
As a result of this, if LLVM pass cannot find source info, functionSourceFile will be empty string instead of "/".
The changes have been made to handle such cases.
Fixes #362
=> Avoid adding extra / to functionSourceFile

src/fuzz_introspector/commands.py, src/fuzz_introspector/datatypes/fuzzer_profile.py
Fixes #424 
@DavidKorczynski I noticed you were doing the correlation, just had to do it before accumulating fuzzer, so the executable name is set and used correctly via `profile.identifier`.
=> Correctly load per-fuzzer coverage

src/fuzz_introspector/html_report.py, src/fuzz_introspector/styling/styles.css
Substitute the use of conclusion box in cases where it is in fact not a
conclusion.
Fixes: https://github.com/ossf/fuzz-introspector/issues/429
=> html_report: add warning box

src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/html_report.py, src/fuzz_introspector/styling/calltree.js
Loading a specific callsite is done by way of URL parameters from a page
different than calltree.html.
Fixes: https://github.com/ossf/fuzz-introspector/issues/430
=> html_report: fix link to callsite node from main page

oss_fuzz_integration/get_full_coverage.py
to prevent the script from running it as a fuzz target and getting
```
Running llvm-symbolizer
...
/out/llvm-symbolizer -rss_limit_mb=2560 -timeout=25 -max_total_time=20 -detect_leaks=0 /tmp/llvm-symbolizer_corpus < /dev/null^M
error: unknown argument '-r'^M
error: unknown argument '-_'^M
error: unknown argument '-l'^M
error: unknown argument '-m'^M
...
Executing finished with exception
```
=> oss-fuzz: exclude llvm-symbolizer

oss_fuzz_integration/README.md, oss_fuzz_integration/get_full_coverage.py
to make it easier to run the script without having to press Ctrl-C
every time.
https://github.com/google/oss-fuzz/commit/218f5dc3cf70bd6
=> oss-fuzz: no longer launch the server showing coverage reports

oss_fuzz_integration/oss-fuzz-patches.diff
Remove commenting out starting the coverage web server as it's actually not needed: Ref: https://github.com/ossf/fuzz-introspector/pull/453
=> oss-fuzz: cleanup diff

oss_fuzz_integration/run_both.sh
to avoid collisions in general and make it easier to run the script in VMs/containers where only certain ports are forwarded.
I went with the environment variable because I wasn't sure how to keep the script working with `project time --jobs=...`.
I also dropped a redundant command. It isn't run anyway because the server is either interrupted with Ctrl-C
or fails with something like "OSError: [Errno 98] Address already in
use".
=> oss-fuzz: allow setting ports explicitly

src/main.py
* set up the logger before printing anything
* no longer print the same message twice
* avoid printing "Running ..." when the script is run with just `--help`
=> main.py: a few fixes related to logging

src/fuzz_introspector/datatypes/function_profile.py
Fixes: https://github.com/ossf/fuzz-introspector/issues/476
The issue happens when the underlying clang is out of sync with the post
processing part, because the "Callsites" element is not available in the
older clang frontend. We should, however, support a more safe loading
anyways.
=> function profile: quick fix

oss_fuzz_integration/README.md, oss_fuzz_integration/test_projects.py
to mostly make sure that projects using meson are buildable.
It can also eventually be used to make sure that filenames are normalized consistently but it should be put on hold until https://github.com/ossf/fuzz-introspector/issues/471 is fixed.
=> oss-fuzz/test_projects: add dbus-broker

src/fuzz_introspector/html_report.py
Ref: https://github.com/ossf/fuzz-introspector/issues/468
=> html_report: add report generation timestamp

src/fuzz_introspector/analyses/metadata.py, src/fuzz_introspector/analysis.py, src/fuzz_introspector/code_coverage.py, src/main.py
Display the data used for constructing the fuzzing report.
Includes links to .covreport, .data, .data.yaml
Ref: https://github.com/ossf/fuzz-introspector/issues/485
Build logs will come at a later stage.
=> analysis plugins: add metadata plugin

src/fuzz_introspector/analysis.py, src/fuzz_introspector/code_coverage.py, src/fuzz_introspector/data_loader.py, src/fuzz_introspector/datatypes/branch_profile.py, src/fuzz_introspector/datatypes/bug.py, src/fuzz_introspector/datatypes/function_profile.py, src/fuzz_introspector/datatypes/fuzzer_profile.py, src/fuzz_introspector/datatypes/project_profile.py
avoid having individual modules setting log level but use the global setting instead.
=> src: remove individual levels for logging

oss_fuzz_integration/project_checker.py, oss_fuzz_integration/test_projects.py
Fixes naming of oss-fuzz runner and also restricts URL checking. The URL checking is necessary to restrict to more precisely describe URLs, as I ran into an issue with the following "`<a href="http`" check from `tarantool`:
```
<a href="http_parser_fuzzer.covreport">
```
which gives the following exception
```
requests.exceptions.MissingSchema: Invalid URL 'http_parser_fuzzer.covreport': No schema supplied. Perhaps you meant http://http_parser_fuzzer.covreport?
```
=> oss-fuzz: fix testing set up

tests/build_simple_example.sh
For this test, the location of main.py is in src instead of post-processing (post-processing doesn't exist in the main branch).
Signed-off-by: Jordy Zomer <jordy@pwning.systems>
=> Fix location of main.py for simple test

src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/analysis.py, src/fuzz_introspector/constants.py, src/fuzz_introspector/datatypes/branch_profile.py, src/fuzz_introspector/utils.py
Similar to the logic in https://github.com/ossf/fuzz-introspector/pull/336#issue-1272902626, this PR goes one step further by differentiating uniquely reachable functions by each branch side.
For example in the following control flow consisting basic blocks A, B, C, D, and function calls to u, v, w, x, y; assume the edge A -> C is blocking, here we collect the complexity of functions `v, w` separate from `v, w, x, y` and mark if they are covered or not-covered. 
Then the branch blockers first are ranked based on `[unique_not_covered_funcs_complexity, unique_reachable_funcs_complexity]` and then the rest of reachable/covered functions compelxity.
```mermaid
graph TD;
A-->B:u;
A-.->C:v,w;
B:u -->D:x,y;
C:v,w -.->D:x,y;
```
Signed-off-by: Navid Emamdoost <navid.emamdoost@gmail.com>
=> Incorporate unique function complexity to rank branch blockers

src/fuzz_introspector/analysis.py, src/fuzz_introspector/datatypes/fuzzer_profile.py
This is to make it easier to have more complex logic when matching function names with a fuzzer's
entrypoint.
Ref: https://github.com/ossf/fuzz-introspector/issues/517
=> abstract entrypoint identification to fuzzer profile

src/fuzz_introspector/analysis.py, src/fuzz_introspector/cfg_load.py, src/fuzz_introspector/code_coverage.py
The calltree generation by way of the AST uses different filepaths than the coverage extraction utility. The AST ones can be a bit weird, e.g. including "......" in the path. This fixes it.
Fixes: https://github.com/ossf/fuzz-introspector/issues/517
=> fix mismatching of python calltree/coverage

src/fuzz_introspector/analyses/driver_synthesizer.py
TypedDict causes issues when running with Python3.6 as it's only
available from Python3.8. Switching to a simple class to broaden
support.
=> driver-synthesizer: refactor to avoid TypedDict

src/fuzz_introspector/code_coverage.py
In `.covreport` files, empty lines and comments should not be counted as `0` hit lines. Otherwise it skews the overall coverage calculation.
Fixes #523 
Example:
```
990|     18|    hts_tpool_result *r;
991|       |
992|     18|    if (fp->mt) {
------------------
|  Branch (992:9): [True: 0, False: 18]
------------------
993|      0|    again:
994|      0|        if (fp->mt->hit_eof) {
------------------
|  Branch (994:13): [True: 0, False: 0]
------------------
995|       |            // Further reading at EOF will always return 0
996|      0|            fp->block_length = 0;
997|      0|            return 0;
998|      0|        }
```
lines `991` and `995` does not have any code to be considered for coverage stats, so should be skipped in code coverage load.
=> Skip comments and empty lines when loading coverage data

src/fuzz_introspector/code_coverage.py
Is needed to avoid misrepresenting "no coverage" following https://github.com/ossf/fuzz-introspector/pull/528
=> python coverage: ensure coverage file list is accurate

frontends/python/main.py, src/fuzz_introspector/datatypes/fuzzer_profile.py
Previously we hardcoded this but this didnt allow fuzzers to have arbitrary function names for entrypoints, which indeed is allowed when developing python fuzzers.
=> fuzzer_profile: enable correct identification of python entrypoint

src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/html_report.py
The function table provided wrong urls to the coverage reports. This fixes it.
=> fix python coverage function url

src/fuzz_introspector/analyses/calltree_analysis.py
The current implementation creates wrong balances in terms of open and closed <div> tags. This creates various erroneous layouts, e.g. https://github.com/ossf/fuzz-introspector/issues/475
This fixes it.
=> calltree: fix up div creation

frontends/java/README.md, frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/yaml/BranchProfile.java, frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/yaml/BranchSide.java, frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionConfig.java, frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionElement.java, frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/yaml/FuzzerConfig.java
Dig up different information from the static analysis and call graph generation for fuzz introspector's further processing.
Also apply test on larger java project.
Referring to Steps 2 - 3 in Issue #536 
=> [Java Integration] : Dig up necessary information from the static analysis

src/fuzz_introspector/analysis.py
Fixes: https://github.com/ossf/fuzz-introspector/issues/506
=> Fix calltree links

frontends/java/README.md, frontends/java/soot/pom.xml, frontends/java/soot/run.sh, frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, frontends/java/wala/run.sh, tests/java/test1/TestFuzzer.java, tests/java/test2/TestFuzzer.java, tests/java/test3/TestFuzzer.java, tests/java/test4/Fuzz/TestFuzzer.java, tests/java/test5/Fuzz/TestFuzzer.java
Fix sample testcases and readme to demonstrate how to reproduce the call graph generation process and static analysis for java program.
=> [Java Integration]: Fix sample

frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
Fix two bugs for Issue #536 Step 3~4:
1. Old code forget to remove.
2. Logic of call graph extraction and method depth calculation does not consider looping or recursive code. These kind of code will generate circular edge in the callgraph which will cause infinitely loop when the visitor trace the code following those circular edges. This will end with StackOverflowError and fail the execution. New logic fixed that by recording method that has already been handled to avoid infinitely loop.
=> [Java-Integration]: Fix bug

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp, src/fuzz_introspector/datatypes/fuzzer_profile.py, src/fuzz_introspector/utils.py
This is in contrast to keeping it all in memory during the compilation. This will avoid significant memory overhead for some projects. Also avoid iterating the calltree for each function in the llvm module since we only use this to capture the functions reachable as well as function calldepth. Instead, we just capture outgoing edges for each function, and then propagate this in the python logic. This reduces the overhead of fuzz introspector because the llvm operations are resource heavy. Memory footprint is reduced a lot so we should be able to see more builds compile (e.g. the ones that are killed in the referenced issue), plus, it will speed up compilation by a lot.
Ref: https://github.com/ossf/fuzz-introspector/issues/195
=> llvm: write all functions without storing all in memory and delay function reachability for each function to post processing

src/fuzz_introspector/utils.py
We store tags in the binaries in order to identify which binary corresponds to which .data and .data.yaml files. Currently, we scan the entire binary for this tag. This commit changes it such that we stop scanning once we have found the tag.
Ref: https://github.com/ossf/fuzz-introspector/issues/585
=> correlation cmd: only scan to find the binary tag

frontends/python/main.py, frontends/python/prepare_fuzz_imports.py
This is a follow-up to https://github.com/ossf/fuzz-introspector/pull/586 and hopefully a nail in the coffin or close to.
When we the static analysis is run on python a scan is done for the files to include. This worked well for imports e.g. `import pkg; pkg.a()` but not for `from pkg import a; a()`. The reason was the logic for scanning for python code searched for `.../pkg/a.py` instead of `.../pkg`, which is what we need to include all relevant files. This caused `/src/pyintro-pack-deps` to be lacking files, which is the folder we treat as the "global package" when doing analysis.
This fixes it in that it refines how scanning is done. Now, `pkg` is included as a whole.
I have tested this on e.g. `glom`, `idna`, `pyyaml`, `g-api-*` projects and it's working well.
Signed-off-by: David …
=> frontend: python: improve automation of package finding

frontends/python/main.py
This is needed to include the various python sources for analysis. Also means we avoid having to pass the argument from oss-fuzz.
=> frontends: python: scan for sources by default

frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, src/fuzz_introspector/datatypes/fuzzer_profile.py
Fix the bug that some method and data are missing from the report. 
Also, now the call tree are displaying method arguments, to distinguish same name method with different argument for unique identification purpose.
Related to issue #536 
Aim to fix bug for PR #604
=> [Java Integration]: Fix jvm data bug

frontends/python/prepare_fuzz_imports.py
When module is not found we should continue and not crash.
Example issue found in `croniter` with stack trace:
```
Step #6 - "compile-libfuzzer-introspector-x86_64": Spec:
Step #6 - "compile-libfuzzer-introspector-x86_64": ModuleSpec(name='sys', loader=<class '_frozen_importlib.BuiltinImporter'>)
Step #6 - "compile-libfuzzer-introspector-x86_64": Hello
Step #6 - "compile-libfuzzer-introspector-x86_64":   - datetime.datetime
Step #6 - "compile-libfuzzer-introspector-x86_64": Traceback (most recent call last):
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/usr/local/lib/python3.8/importlib/util.py", line 96, in find_spec
Step #6 - "compile-libfuzzer-introspector-x86_64":     parent_path = parent.__path__
Step #6 - "compile-libfuzzer-introspector-x86_64": AttributeError: module …
```
=> frontends: python: fix issue

doc/Config.md
Closes: https://github.com/ossf/fuzz-introspector/issues/580
=> docs: specify the config file does not apply to coverage reports

src/fuzz_introspector/code_coverage.py
_fend_ will be -1 when the function is the last in the source file. And thus, for the last function in each source file, _fend_ will always be less than _exec_line_ or _non_exec_line_ making the last function of each source file will never be processed.
=> Fix bug for python coverage

oss_fuzz_integration/runner.py
There is a special case where the names of projects aren't added to links to public corpora if the names of fuzz targets already start with their project's name + "_": https://github.com/google/oss-fuzz/blob/7797279c274d10197d62841dc43834238fd483a1/infra/cifuzz/clusterfuzz_deployment.py#L295-L298
It should make it possible to use the script with projects like avahi
```
--2022-11-22 17:54:14--  https://storage.googleapis.com/avahi-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/avahi_avahi_packet_consume_record_fuzzer/public.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 173.194.222.128, 173.194.73.128, 74.125.131.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|173.194.222.128|:443... connected.
HTTP request sent, awaiting response... 403 …
```
=> runner.py: create links to public corpora like CIFuzz does

oss_fuzz_integration/jvm.patch, oss_fuzz_integration/runner.py
Add logic in fuzz-introspector runner to include all necessary steps (Build, run, generating coverage, generating html report) for oss-fuzz jvm project, thus connecting them to fuzz introspector.
This PR consist of the following steps for JVM project connection:
1. Apply patch for fuzz-introspector logic into the jvm project's build.sh before building the project.
2. Build the project normally, run the fuzzers, rebuild the project with coverage sanitizer to generate coverage report
3. Goto correct build result folder, set the correct permission.
4. Run fuzz-introspector main logic to generate HTML report
5. Launch the python http.server in the directory to showcase the HTML report.
This is related to the last step of issue #536
=> [Java Integration] Connect oss-fuzz jvm project with fuzz-introspector runner

oss_fuzz_integration/jvm.patch, oss_fuzz_integration/runner.py
- Change the paths where indicated by the `# Require change to "cp fuzz-introspector/frontends/java/*.data ./"
- Modify the `runner.py` to find the `jvm.patch` relative to the `runner.py` file instead of the current working dir
- wrap the `jvm.patch` script in a condition that's only true once, meaning we can run `runner.py` a number of times. This is a quick hack for a temporary situation.
- fix a bug in `runner.py` for correctly identifying fuzz targets.
=> oss-fuzz: refine jvm set up

.github/workflows/jvm-test.yml
Add in automatic cI to test jvm test cases on java code.
This is part of the final checking for issue #536 
=> [Java Integration] Add CI to execute jvm test cases

oss_fuzz_integration/build_post_processing.sh, oss_fuzz_integration/jvm.patch, oss_fuzz_integration/oss-fuzz-patches.diff, oss_fuzz_integration/runner.py
Provides patches for oss-fuzz that modifies the infrastructure to handle introspector runs for jvm targets. We only needed some minor changes in `infra/base-images/base-builder/compile` and some updates in `jvm.patch`. Also cleans up some of the jvm-specific logic from `runner.py` introduced in https://github.com/ossf/fuzz-introspector/pull/621
=> oss-fuzz: provide patches for jvm integration

oss_fuzz_integration/runner.py
There are use cases where it would be desirable to be able to point FI to specific local directories when projects are built. For example systemd can't be built with FI because it links its fuzz targets against shared libraries and any patches getting FI to work are unlikely to be accepted upstream. That shouldn't prevent anyone from using FI with it though as long as their local forks are compatible with FI. Also when fuzz targets and/or code are changed or when PRs are analyzed locally it should be possible to confirm that things have gotten better or at least haven't gotten worse.
It's probably worth mentioning that since `./infra/helper.py` doesn't clean up after itself for this to work build scripts should clean up their build directories themselves using `make clean`, `git clean …
=> Allow pointing runner to local source directories

oss_fuzz_integration/runner.py
to make it possible to just run it directly using `../runner.py` instead of `python3 ../runner.py`. It should make it a bit easier to use the script interactively.
=> Make runner executable

oss_fuzz_integration/runner.py
Fixes
```
python3 ../runner.py download-corpus avahi
Traceback (most recent call last):
File "/home/vagrant/fuzz-introspector/oss_fuzz_integration/oss-fuzz/../runner.py", line 652, in <module>
download_full_public_corpus(args.project)
TypeError: download_full_public_corpus() missing 1 required positional argument: 'target_corpus_dir'
```
It also makes it possible to download corpora to specific directories by passing --corpus-dir=...
=> runner: make download-corpus work

src/fuzz_introspector/html_report.py
Possible wrong inclusion of non-hitted function for coverage calculation.
=> [JVM Issue]: Fix possible errornous calculation

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
Java method from different classes are allowed to have a same signature. This logic does not work well with fuzz-introspector which identify unique function only by function name. In order to accommodate fuzz-introspector analysing logic, changes has been made on the Soot static analysis code to include also the class name as part of the function identifiers. This PR provide a fix to the soot generation logic to include class name in the resulting .data and .data.yaml file to allow fuzz-introspector correctly handle and analyse methods from different class but with the exact same signature.
Example:
toString() methods coming from java.io.File and java.io.FileInputStream have the exact same signature, making the method name as java.io.File.toString() and java.io.FileInputStream.toString() …
=> Java-Issue: Fix method naming logic error

src/fuzz_introspector/utils.py
We are seeing a lot of error messages when fuzzer profiles are loading. This PR makes the messages more verbose.
```
INFO:fuzz_introspector.utils:Error loading yaml file
INFO:fuzz_introspector.utils:Trying to load multiple file formats toget
INFO:fuzz_introspector.utils:Error loading yaml file
INFO:fuzz_introspector.utils:Trying to load multiple file formats toget
INFO:fuzz_introspector.utils:Error loading yaml file
```
=> More verbose YAML loading

CODE_OF_CONDUCT.md
Replace the placeholder text with the correct email address as confirmed via the OpenSSF Slack.
Signed-off-by: Caleb Brown <github@calebbrown.id.au>
=> Update contact for the code of conduct

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/BranchProfile.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/BranchSide.java
Branch Profiles has been generalised in PR #657. This change makes old yaml invalid, and will crash the running for JVM implementation of fuzz-introspector. This PR aim to fix the Soot CG and yaml generation logic to meet the new generalised format of the branch profiles to avoid errors in generating JVM report.
Issue #629 #630
=> Branch Profiles Change: Fix format change for yaml branch profile

src/fuzz_introspector/html_helpers.py, src/test/test_html_generation.py
Adds the option to add Google Analytics tracking by setting the `G_ANALYTICS_TAG` env variable.
Signed-off-by: AdamKorcz <adam@adalogics.com>
=> add option for Google Analytics

src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/analysis.py, src/fuzz_introspector/utils.py
Fix a bug that the jvm coverage links are missing because of wrong comparison and generation of java package name.
=> JVM implementation bug: Fix jvm link with missing package name

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
Add in all include options to force all library classes to be handled. These library classes includes package prefix which are considered as native code, which may accidentally covers some project with package name prefix same as these native package.
Solve issue #683 
=> JVM implementation bug: Fix package inclusion and exclusion bug

src/fuzz_introspector/analyses/bug_digestor.py, src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/analyses/driver_synthesizer.py, src/fuzz_introspector/analyses/engine_input.py, src/fuzz_introspector/analyses/filepath_analyser.py, src/fuzz_introspector/analyses/function_call_analyser.py, src/fuzz_introspector/analyses/metadata.py, src/fuzz_introspector/analyses/optimal_targets.py, src/fuzz_introspector/analyses/runtime_coverage_analysis.py, src/fuzz_introspector/analyses/sinks_analyser.py, src/fuzz_introspector/analysis.py, src/fuzz_introspector/commands.py, src/fuzz_introspector/constants.py, src/fuzz_introspector/html_report.py, src/fuzz_introspector/json_report.py, src/main.py
Create a flow to allow the user of fuzz-introspector generate a separate json report for sink coverage information of the target project.
Issue #670
=> Sink coverage report: Commit new flow for retrieving sink coverage from analyser

src/fuzz_introspector/analysis.py
Fix for https://github.com/google/oss-fuzz/issues/9209#issuecomment-1352241356
@Navidem I first tried to have a bit more tight control, but ended up wrapping the body of the loop in a try-catch -- we can debug specific issues from when we see error logging come up. WDYT?
=> analysis: temporary fix around branch blocker calculation

src/fuzz_introspector/code_coverage.py
This avoids matching keywords in the middle of variable of function names.
For example, this line will not match `COVERAGE_CASE_REGEX`:
```
strncasecmp((const char *) packet->line[packet->parsed_lines].ptr, "Transfer-Encoding: ", 19) == 0)
``` 
=> More restricted regex for loading coverage reports

src/fuzz_introspector/code_coverage.py, src/test/fuzz/test_fuzz_cov_load.py, src/test/fuzz/test_fuzz_report_generation.py
This is one of the reason some issues have not been reported by the fuzzer. https://github.com/ossf/fuzz-introspector/pull/686 introduced a new argument to `run_analysis_on_dir` which caused an argument in the fuzzer (the last argument, `False`) to reference a new argument. The effect is that the underlying loading of yaml profiles were multi-threaded, which consequntly do not propagate exceptions.
This commit changes it to specify arguments when calling `run_analysis_on_dir` so future scenarios won't switch the arguments as such. Note, I don't think this would have detected the branch blocker issues as this happened before the above change.
Ref: https://github.com/ossf/fuzz-introspector/issues/693
=> fuzz: specify arg values in fuzz_report_generation

src/fuzz_introspector/analyses/bug_digestor.py, src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/analyses/driver_synthesizer.py, src/fuzz_introspector/analyses/engine_input.py, src/fuzz_introspector/analyses/filepath_analyser.py, src/fuzz_introspector/analyses/function_call_analyser.py, src/fuzz_introspector/analyses/metadata.py, src/fuzz_introspector/analyses/optimal_targets.py, src/fuzz_introspector/analyses/runtime_coverage_analysis.py, src/fuzz_introspector/analyses/sinks_analyser.py, src/fuzz_introspector/analysis.py, src/fuzz_introspector/commands.py, src/fuzz_introspector/html_report.py, src/fuzz_introspector/json_report.py
This PR aims to revamp the json string result object and make it an instance variable. Then fix the logic to store those analyser instance that request to be included in the resulting json report.
=> Json report: Make json string result an instance variable

.clusterfuzzlite/build.sh
The goal is to speed up the CI.
=> clusterfuzz-lite: prefer binary when installing matplotlib

src/fuzz_introspector/data_loader.py, src/fuzz_introspector/utils.py
This should fix a bug found by the report fuzzer.
=> data_loader: wrap data loading to catch unicode errors

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, src/fuzz_introspector/datatypes/fuzzer_profile.py, tests/java/test1/.config, tests/java/test10/.config, tests/java/test11/.config, tests/java/test2/.config, tests/java/test3/.config, tests/java/test4/.config, tests/java/test5/.config, tests/java/test6/.config, tests/java/test7/.config, tests/java/test8/.config, tests/java/test9/.config
Fix naming output problem of Soot code for the entry method. Also changing the fuzz-introspector code to match the updated entry function names. Also include the entry function to the reached function list.
Last but not least, update the unit testing to match the changed name.
Relies on #702 
=> JVM bug: Fix naming problem

.github/workflows/codeql.yml, .github/workflows/google-java.yml, .github/workflows/jvm-unit-test.yml, .github/workflows/mypy.yml, .github/workflows/testing.yml
This is to make the CI only run relevant jobs for relevant code, in order to speed it up when it's not needed.
=> ci: specify paths for several jobs

frontends/java/oss-fuzz-main.py, frontends/java/run.sh, frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, frontends/java/src/test/java/ossf/fuzz/intropsector/soot/CustomSenceTransformerTest.java
Fix slow execution and out of stack memory problem. Change the calculation of function depth and add in options to include necessary package instead of including all library packages at once.
=> JVM implementation: Fix all around include and depth calculation

frontends/java/oss-fuzz-main.py, frontends/java/run.sh, frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
Fix the bug that python subprocess call cannot accept semicolon as valid character.
=> Jvm bug: Fix semicolon bug

requirements.txt
This is because readthedocs uses an older version of sphinx to generate docs, which produces different output to the latest sphinx. Specify version so it's fixed.
=> requirements: specify sphinx version

src/fuzz_introspector/analyses/__init__.py, src/fuzz_introspector/analyses/bug_digestor.py, src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/analyses/driver_synthesizer.py, src/fuzz_introspector/analyses/engine_input.py, src/fuzz_introspector/analyses/filepath_analyser.py, src/fuzz_introspector/analyses/function_call_analyser.py, src/fuzz_introspector/analyses/metadata.py, src/fuzz_introspector/analyses/optimal_targets.py, src/fuzz_introspector/analyses/runtime_coverage_analysis.py, src/fuzz_introspector/analyses/sinks_analyser.py, src/fuzz_introspector/analysis.py, src/fuzz_introspector/html_report.py
All analyses have an `Analysis` class, which is slightly annoying for python documentation (https://fuzz-introspector.readthedocs.io/) as it shows all of them with the same name. This changes the general names to plugin-specific names, and then has a list in analyses/__init__.py with all of the various plugin names. This improves documentation and I think also makes the code better.
=> Rename analyses to avoid Analysis class

src/fuzz_introspector/analyses/sinks_analyser.py
Fix naming handling for python which has <builtin> tag added for those function call in default package.
=> Sink Analyser:Fix python builtin package naming

src/fuzz_introspector/analyses/engine_input.py, src/fuzz_introspector/analyses/sinks_analyser.py, src/fuzz_introspector/commands.py, src/fuzz_introspector/html_report.py, src/fuzz_introspector/json_report.py
This removes the use of `fuzz-introspector.json` as we already had `summary.json` as a file for outputting data. The existing approach is to write the json contents when it's ready (using https://github.com/ossf/fuzz-introspector/blob/aeddd0658b7a76af5cbdc2dc035e3381755eeb66/src/fuzz_introspector/utils.py#L229) so am switching to a similar approach for the sink analyser. More refactoring is needed shortly to place all outputting logic into `json_report.py` instead of `utils.py`
=> Improve json output

src/fuzz_introspector/analysis.py, src/fuzz_introspector/datatypes/fuzzer_profile.py, src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/html_report.py, src/fuzz_introspector/json_report.py, src/fuzz_introspector/utils.py
Remove the use of write_to_summary in the utils.py module, and make more convenient wrapper functions in json_report.py. This also overcomes some existing limitations where we basically overwrote various key/value pairs in the report.
=> refactor json reporting

src/fuzz_introspector/constants.py, src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/json_report.py
When dumping a project profile to json "reached-complexity-percentage" is set to be `complexity_unreached` whereas it shold be `reached_complexity_percentage`. Also adds some utility and helper functions.
=> fix bug in json report creation

src/fuzz_introspector/analyses/optimal_targets.py, src/fuzz_introspector/html_report.py
This is needed for things such as comparing fuzz introspector runs and for creating scripts that gather overviews of a lot of fuzz introspector reports.
=> Output all functions table to json report.

src/fuzz_introspector/html_report.py
The existing `row` is in HTML format whereas we want it raw.
=> html_report: fix value writing to json report

src/fuzz_introspector/commands.py, src/fuzz_introspector/diff_report.py, src/main.py
Ref: https://github.com/ossf/fuzz-introspector/issues/734
=> Add initial layout for report diffing

src/fuzz_introspector/analyses/calltree_analysis.py
The indices are not shown anywhere in the table, but they are quite useful for correlating the blocker with the bitmap overview.
=> html report: show calltree indices in fuzz blocker table

frontends/python/prepare_fuzz_imports.py
This handles issues observed on OSS-Fuzz, e.g.
```
Step #6 - "compile-libfuzzer-introspector-x86_64": Traceback (most recent call last):
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/prepare_fuzz_imports.py", line 170, in <module>
Step #6 - "compile-libfuzzer-introspector-x86_64":     fuzz_packages = get_package_paths(filename)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/prepare_fuzz_imports.py", line 159, in get_package_paths
Step #6 - "compile-libfuzzer-introspector-x86_64":     fuzz_visitor.print_specifics()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/prepare_fuzz_imports.py", line 123, in print_specifics
Step #6 - …
```
=> frontends: python: handle import error when using importlib

oss_fuzz_integration/oss-fuzz-patches.diff
I deleted the out-of-date part in the `oss-fuzz-patches.diff`.
Following the first bash pieces of the [doc](https://fuzz-introspector.readthedocs.io/en/latest/user-guides/comparing-introspector-reports.html), the execution will fail at `./build_post_processing.sh` due to the out-of-date patch file. The root cause is that `ossfuzz/infra/base-images/base-clang/checkout_build_install_llvm.sh` has already updated the code in its [latest commit](https://github.com/google/oss-fuzz/blob/461d60ccc2e4d5cf0428616cdee284ed6e616fe4/infra/base-images/base-clang/checkout_build_install_llvm.sh#L132).
After deletion, the workflow in the doc works.
```bash
$ ./build_post_processing.sh
+ '[' -d oss-fuzz ']'
+ echo 'Cloning oss-fuzz'
Cloning oss-fuzz
+ git clone https://github.com/google/oss-fuzz
Cloning …
```
=> fix the out-of-date patch for `checkout_build_install_llvm.sh`

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/Callsite.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionElement.java
Fix soot logic to loop through all statement in processed methods to record its method invocation. This can help to provide callsite information and line number of every methods that has a parent function (with source code provided).
=> JVM Implementation: Fix soot logic to include callsite for all processed methods

doc/LanguageImplementation.md
Fix the documentation, adding the missing "Callsites" element desciption to the documentation.
=> Documentation: Fix data.yaml file element description

src/fuzz_introspector/html_report.py
Prettifying is cosmetical, and not a necessity.
The prettify function may throw a recursion error, so catch these and progress anyways. This caused the boost build to fail.
=> html_report: catch recursion errors when beautifying html

tools/sink-analyser/check_files.py
The result checking script for sink analyser fail to retrieve sink functions from the all_functions.js for JVM project because of incompatible function name and wrong sink function list used. This PR aims to fix that bug.
=> Sink analyser: Fix bug in the check file script

frontends/java/oss-fuzz-main.py
Some JVM project is built with gradle and thus its docker file does not have maven installed. This make the frontend java code failed to compile with maven. Fix the oss-fuzz-main.py script to install maven before compiling the frontend code for java.
=> JVM Integration: Fix maven missing bug

src/fuzz_introspector/datatypes/function_profile.py, src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/html_report.py
Add accessor function for working on the function dictionary, and also a wrapper function that filters external functions. This wrapper is then used to capture most of the statistic data displayed.
Ref: https://github.com/ossf/fuzz-introspector/issues/819
=> project-profile: add accessor for all functions

src/fuzz_introspector/datatypes/project_profile.py
Only include function names identified in the frontend static analysis when calculating project-wide coverage. This is because coverage reports and static analysis may provide some different information about the program if sanitizers/static analysis is not done consistently. This is e.g. an example in libfido2
https://github.com/ossf/fuzz-introspector/issues/812 where the coverage report includes a lot of functions from third-party libraries but these libraries are not being included in the fuzz introspector static analysis. We should guard against those situations and for now we will make the static analysis the decising component.
=> project_profile: refine calculation of project-wide coverage stats

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
There are too much recursive functions in the frontend code and some of them caused stack overflow and slow process shown in #716. This PR merges the the function depth calculation recursive function with the extract call tree recursive function to decrease the resources and time needed for the process.
=> JVM Integration: Fix slow process from heavy recursion

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, src/fuzz_introspector/datatypes/fuzzer_profile.py
In the current logic, the constructors and destructors of all java classes has been ignored by the JVM frontend. This PR includes empty profile for all constructors (including constructor for library classes or excluded classes) into the yaml file in order to give referencing information for further analysis of object method which requires creating contructor for object initialisation. Only limited information like argument list or exceptions thrown by contructors will be included. Also, constructor will not be handled in the call tree generation process to avoid flooding the result.
=> Java Integration: Add constructorto yaml file

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/JavaMethodInfo.java
In order to accommodate object creation, we need to know if the class itself is abstract or not or if it is an interface, and possible super class and implemented interface. The major usage of these information is to look for concrete subclasses for constructor calling because abstract class or interface are not able to construct. This PR add the superclass, implemented interface information for the class of the method to the data.yaml file. Also, an additional boolean value are added showing if that class is concrete or not, that is if that class's constructor can be called directly.
=> JVM integration: Add class info for constructor

tools/auto-fuzz/base_files.py, tools/auto-fuzz/fuzz_driver_generation_jvm.py, tools/auto-fuzz/manager.py, tools/auto-fuzz/post_process.py
- Fix bug in template, where the heuristics added to the code was not commented out.
- Only download maven once to save network bandwidth, then copy it over in each Dockerfile.
- Don't clone the repository in the Dockerfile as we copy it over instead.
- Make it possible to specify which language to test.
- Make the post processing able to give correct paths to java fuzzers.
=> auto-fuzz: fix up java integration

tools/auto-fuzz/fuzz_driver_generation_jvm.py, tools/auto-fuzz/manager.py
Add heuristic 2 for jvm auto fuzzer generator, also limit the maximum recursion for concrete subclass discovery to 10 to avoid infinity loop from cross constructor referencing.
=> Auto-fuzz: Add heuristic 2 for jvm

src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/analyses/optimal_targets.py, src/fuzz_introspector/html_helpers.py, src/fuzz_introspector/html_report.py
Move functions from `html_report.py` into `html_helpers.py` to have better separation between the code that assembles the overall report and that which creates the HTML text itself.
=> html-report: move code into html_helpers

tools/auto-fuzz/constants.py, tools/auto-fuzz/fuzz_driver_generation_jvm.py, tools/auto-fuzz/manager.py
For Java program, it is possible to specify a abstract superclass or interface as the argument type and all object of its subclass or class implemnting that interface are all valid object for that argument type. There is possibility that there are more than one possible options for the concrete object, this PR aims to generate object creation statement for each of the possibility in order to cover more fuzzer choice and targets. This PR also adds in a new constant for limiting the number of target generated for each project to increase efficiency.
=> Auto-Fuzz: Fix concrete subclass searching logic

tools/auto-fuzz/constants.py, tools/auto-fuzz/fuzz_driver_generation_jvm.py, tools/auto-fuzz/manager.py
The new heuristic 3 considers some cases where constructor call is not possible. In some of the classes, they provide some methods, which we normally named them as factory methods, to generate an object instance of a specific class. In some of these cases, the constructor are protected and developers are required to use those factory methods to create an object instance which may contain hidden settings or singleton control. These factory methods can be static or non-static. This heuristic focuses on static factory methods and calls them to retrieve an object instance before invoking an instance method. The focus for non-static factory methods are processed in heuristic 4.
=> Auto-fuzz: Add heuristic3 for java

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Following heuristic 3 in PR #856, this PR focus on using non-static factory methods to generate an object instance for instance method invocation. It will also refer to heuristic 1~3 to handle the arguments needed for the non-static factory methods.
=> Auto-fuzz: Heuristic4 for java

requirements.txt
The post processing of auto-fuzz uses the tqdm python module to display loading bar when the process check the auto generated fuzzer. This PR adds the tqdm module to the python dependency requirement list to enable it.
=> Auto-fuzz: Add tqdm module to requirement for python dependency

tools/auto-fuzz/base_files.py, tools/auto-fuzz/fuzz_driver_generation_jvm.py, tools/auto-fuzz/manager.py
The original code assumes that the target project uses maven structure, but there exists quite a number of projects that actually adopt Gradle project structure instead. This PR add logic to the auto-fuzz manager and base file builder in order to accommodate gradle projects. The new code will check if the project contains pom.xml or build.gradle which are the build property files for maven and gradle project respectively and build with the corresponding builder.
=> Auto-fuzz: Fix java autofuzz build fail

tools/auto-fuzz/constants.py, tools/auto-fuzz/manager.py, tools/auto-fuzz/oss_fuzz_manager.py
This is needed as otherwise the disk is quickly exhausted when doing large-scale runs.
=> auto-tools: clean up docker build cache after X runs

tools/auto-fuzz/constants.py, tools/auto-fuzz/manager.py
Move the maven and gradle properties to constants.py, this could make it easier to udpate the path and download links.
=> Auto-fuzz: Move maven and gradle properties to constants

tools/auto-fuzz/fuzz_driver_generation_jvm.py
In the Java auto fuzzing, there is a temporary measure added before to limit the number of recursion. When the maximum number of recursion is reached, the searching of possible constructor will stop and return an empty constructor as a fail safe option. This setting could eliminate the maximum recursion count reached problem, but it also makes some of the fuzzers fail to use the fuzzing data because empty constructor are used. 
With the fix in #862 It eliminates the error on repeat process of the same method. This will limit the number of recursion and the needs of the recursion count, thus this PR aims to remove the recursion count feature to allow a better fuzzer generation process with random fuzz data.
=> Auto-fuzz: Fix recursion

tools/auto-fuzz/post_process.py
This is needed to identify the increase in coverage that a given fuzzer has been achieved.
For example, auto-fuzz generates the following fuzzer for the `glom` project:
```python
import sys
import atheris
import glom
@atheris.instrument_func
def TestOneInput(data):
fdp = atheris.FuzzedDataProvider(data)
val_1 = fdp.ConsumeUnicodeNoSurrogates(24)
try:
glom.reduction.flatten(val_1)
except (glom.matching.Check._ValidationError,glom.core.GlomError,):
pass
def main():
atheris.instrument_all()
atheris.Setup(sys.argv, TestOneInput)
atheris.Fuzz()
if __name__ == "__main__":
main()
```
The output from running the fuzzer is:
```
INFO: A corpus is not provided, starting from an empty corpus
#2	INITED cov: 235 ft: 235 corp: 1/1b exec/s: 0 rss: 88Mb
#2048	pulse  cov: 235 ft: 235 corp: 1/1b lim: 21 …
```
=> auto-fuzz: extend post processing

frontends/python/main.py
We try to avoid any tests during analysis. This was missing a few instances. This fixes it.
=> frontends: python: Make path exclusion more elaborate

tools/auto-fuzz/manager.py
To ensure only unique lines of import statement and exception handling statement are added to each possible target for java auto fuzzing, the type of these two object variables are set to set instead of list. But set objects are not json serializable and cause some errors in writing the summary file. This PR adds an extra list() call to the object to ensure the return variables must be a list object for the json serialise process.
=> Auto-fuzz: Fix non-serializable set for json

tools/auto-fuzz/manager.py
Current manager assume all github project are using the default HTTPS links. But there are some project actually using SSH link instead of HTTPS link. The current logic fails to process the SSH links correctly. This PR solve this problem.
=> Auto-fuzz: Fix possible link error

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/JavaMethodInfo.java
For some of the existing java fuzzer, it requires using enum values as parameters parameters. Normal constructor or factory method fails to create an enum object with random fuzzing data. One of the solutions is creating an array of all possible values of the target enum and using the jazzer fuzzer to randomly pick one of them as parameters during fuzzing. For example in https://github.com/google/oss-fuzz/blob/master/projects/checker-framework/UtilCheckerFuzzer.java#L41-L49, it uses this approach to create random fuzzing enum values. This PR adds an additional boolean field `enum` to the .data.yaml file for jvm frontend to allow the auto fuzzer generator determine which parameters are enum type and use above mentioned special handling to create random enum value for fuzzing. This matches …
=> Auto-fuzz / JVM frontend: Add enum class support

tools/auto-fuzz/fuzz_driver_generation_jvm.py
There exists some instance methods which require certain configuration (by calling to some configuration methods) before executing the target instance methods. This PR adds in new logic to discover possible setting methods for the object prior to the method call and adds in the invoke statement of those setting methods before invoking the target methods. Currently, we assume that setting methods are instance methods belonging to the same class, either with function names started with set (setXXX) or return nothing after invoking them.
=> Auto-fuzz: Heuristic 6 for java

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Currently, if a class have multiple constructors, only one of them are picked for object creation. This setting limits the possible choice of fuzzer generation. This PR change the logic to include all possible constructor choice for the target class.
=> Auto-fuzz: Fix constructor list

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/ClassField.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/JavaMethodInfo.java
Some of the object creation can be done by referring to public static final class variable defined in that class. This methods allow the class developer create some default settings object. This PR includes these fields in the resulting data.yaml file to help the auto-fuzzing logic to generate code that are making use of these default class objects.
=> Auto-fuzz: Add class variable handling

tools/auto-fuzz/manager.py
In the current code, if project build or frontend code fail for java, it will stop the whole process because the current logic fails to move on to the next project when fuzzerLog-Fuzz1.data.yaml is missing. This PR adds the logic to skip projects with failed build in order to continue to work on projects which could build normally without interrupting the batch testing process.
=> Auto-fuzz:Add fail safe logic

tools/auto-fuzz/manager.py
In the current frontend java, the output fuzzerLogFile-XXX.data and fuzzerLogFile-XXX.data.yaml are created in the current working directory. The auto-fuzz manager for jvm will then copy the fuzzerLogFile-Fuzz1.data.yaml into the correct directory. The updated profiles data-loader logic of fuzz-introspector requires both fuzzerLogFile-Fuzz1.data and fuzzerLogFile-Fuzz1.data.yaml to read the profiles. Thus some project builds will fail and crash the batch process. This PR adds additional logic to also copy fuzzerLogFile-Fuzz1.data to the correct directory in order to accommodate the new fuzz-introspector data-loader logic.
=> Auto-fuzz: Add missing fuzzer profile

tools/auto-fuzz/constants.py, tools/auto-fuzz/fuzz_driver_generation_jvm.py
Current logic will only search for possible subclasses if the target class is not concrete. This setting limits the options if the target class is concrete. This PR fixes this logic by adding an additional boolean constant to allow the user to choose if this searching is needed. If the new constant is true, the logic will search for subclasses no matter if the target class is concrete or not. Otherwise, it will remain the same as the current logic which only searches for subclasses if the target class is not concrete. This increases the possible combination for object creation under the polymorphism scheme of java.
This refers to jvm-autofuzz-heuristics-2-SP in the documentation.
=> Auto-fuzz: Fix logic to include concrete class

tools/auto-fuzz/fuzz_driver_generation_jvm.py
In java, there is a kind of special type object which is the class object. Every class can return its relative class object and some method may require them for function calls of object creation. The most notable example is the java logger. This PR adds in heuristic 10 and related logic to handle class objects, it creates all possible class objects in the given data.yaml file for method calls or constructors which require class objects as arguments.
=> Auto-fuzz: Add heuristic 10 for java

tools/oss-fuzz-scanner/function_inspector.py
This is a simple example showing how it's possible to extract information out about functions in a given project using the OSS-Fuzz storage as a form of API.
=> oss-fuzz-scanner: add utility for extracting function information

tools/auto-fuzz/base_files.py, tools/auto-fuzz/constants.py, tools/auto-fuzz/manager.py
Some projects are found to be using ant project environment instead of maven or gradle. This PR adds build support to those project. When build.xml (ant project build property) is found, ant building logic are used.
=> Auto-fuzz: Add build support to ant based project

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
Some project's build property and source code are not located in the root folder. This PR adds logic to recursively search for the build property file from the subfolders if they are not found in the root folder. If more then one result are found, it will use the outermost directory as the subdirectory are considered as submodules for maven, gradle and ant project structure.
=> Auto-fuzz: Fix submodule build

tools/auto-fuzz/base_files.py
Some project submodule may locate deeper in the project tree rather than locating at the first child directory. This PR fix the base build script to search for submodule build property recusively in all possible subdirectories, following the approach in manager.py when the original project is built.
=> Auto-fuzz: Add recursive build property searching

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
Some projects set the maven build source and execution target to jdk 1.5 which is too old for the maven installed in the docker. This PR patches the project's pom.xml before build to make it use jdk 1.8 instead, which is still backward compatible with code in jdk 1.5.
=> Auto-fuzz: Change old jdk to newer one for maven project

tools/auto-fuzz/post_process.py
Improve how code coverage is collected from e.g. runs that trigger an exception. This would previously be classified as "failed to run" but we should keep the runs as often they indicate a successful fuzzer.
=> auto-fuzz: refine post-process

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, tools/auto-fuzz/manager.py
Some project build a lot of jar files and the long list of jar files path make the shell fail to run because it exceeds the argument length setting of the bash shell. This PR fixes the arguments by introducing wildcard for the class path to decrease the length of the frontend execution command.
=> Auto-fuzz: Fix java classpath too long problem

tools/auto-fuzz/manager.py
For some of the gradle projects build properties, there exists some self-module dependencies which are referring to older commit. So those dependencies will be missing if git shallow clone is used. This PR fixes the git clone command to avoid shallow clone and preserve the whole commit tree for those self-module dependencies.
=> Auto-fuzz: Fix missing dependency commit in shallow clone

tools/auto-fuzz/manager.py
For some of the gradle based project, the location of compiled class files may located in subdirectory if the project contains submodules. This PR fixes the searching of those compiled classes files by including build path of possible submodules when packaging and creating the jar file for further process.
=> Auto-fuzz: Fix compiled class searching and jar packaging

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Fix the bug where static method list are empty because of a wrong skipping of static methods.
=> Auto-fuzz: Fix empty static method list bug

frontends/java/oss-fuzz-main.py, frontends/java/run.sh, frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, frontends/java/src/test/java/ossf/fuzz/intropsector/soot/CustomSenceTransformerTest.java
In the current logic, the fuzz-introspector will gather all jar files built and analyse all classes in them and exclude some well known library classes. If there is some java based oss-fuzz project that generates a large list of dependencies and include them as jar files in the output directory, those dependencies are also analysed by fuzz-introspector if their package name is not specifically excluded. This setting actually creates a large overhead by analysing classes which are not part of the target project itself. Indeed, may project runs into OOM or timeout during fuzz-introspector processing because of this reason. This PR aims to decrease the overhead by allowing the project specifying its package prefix and fuzz-introspector will only go through classes with the specified package …
=> JVM Integration: Fix logic to allow specifying target package prefix 

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
Some projects may be based on older java versions, thus forcing it to build with javac version 15 in maven may result in error. The auto-fuzz module can support as old as java version 1.8. This PR fixes the logic for maven build by using javac version 1.8 in the maven argument to build the project if the project failed to build with javac version 15.
=> Auto-fuzz: Fix javac version

frontends/java/oss-fuzz-main.py
The parameter list for calling the java frontend in oss-fuzz-main is in wrong order after adding a new parameter. This PR fixes it by changing the parameter list to correct order.
=> Fix bug: Fix parameter for frontend call

src/fuzz_introspector/datatypes/fuzzer_profile.py
Some project may use non-standard parameter for fuzzerTestOneInput method and  the current logic cannot catch that and resulting in empty entry method. This PR fixes the logic to just check the method name and class name for entry method and ignore the parameter used.
=> JVM Implementation: Fix entry method checking for jvm

tools/auto-fuzz/manager.py
For some java project, the source folder may not copy to the oss-fuzz repository. This PR fixes an error thrown when the source file path is not existed when the cleaning operation is executed.
=> Auto-fuzz: Fix clean error for non-exist source folder

tools/auto-fuzz/base_files.py, tools/auto-fuzz/fuzz_driver_generation_jvm.py, tools/auto-fuzz/manager.py, tools/auto-fuzz/post_process.py
Java does not accepted hyphen as part of the class identifier. This PR fixes the bug to avoid the hyphen when merging successfully generated fuzzers.
=> Auto-fuzz: Fix bug for illegal java class name

tools/auto-fuzz/post_process.py
In #956, it adds the logic for merging auto-generated java fuzzers folder into a single folder. This approach is only working as an additional action when generating the fuzzers. It forgets to handle if the post process merging is needed for those java fuzzers. This PR fixes the post process to allow merging of the fuzzers after finishing the fuzzer generation process.
=> Auto-fuzz: Add java for merge run handling

tools/auto-fuzz/manager.py
The ant engine extracted from the zip file does not have permission right. This PR fixes the problem but setting the execution right for the ant tool before building the project.
=> Auto-fuzz:Fix permission denied bug for ant build

tools/web-fuzzing-introspection/app/site/templates/function-search.html
Without this long function names can force the table to go beyond what is appropriate.
=> web-app: ensure max table size

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/JavaMethodInfo.java
Some classes are not public for classes outside the package. This PR adds this information to the yaml file to determine if that method and its class is publicly accessible.
=> Java-Frontend: Add class method status in frontend

tools/auto-fuzz/fuzz_driver_generation_jvm.py
There is a bug in handling the retrieval of factory method and initialization methods. The method append is used instead of extend which actually make the whole result list an element in the bigger list, rather then adding elements to the bigger list. This PR fixes this.
=> Auto-fuzz: Fix list bug

tools/auto-fuzz/fuzz_driver_generation_jvm.py
General methods inherit from base Object class, or getter and setter methods don't have much values in fuzzing thus it maybe better to filter them out for the auto fuzzer generation process. This could help to decrease the number of possible targets. This PR applies the filtering during the data.yaml file processing.
=> Auto-fuzz: Add method filtering

frontends/python/prepare_fuzz_imports.py, src/fuzz_introspector/utils.py
A number of projects are failing to have any code analysed from the giving libraries they represent. This includes e.g. netaddr-py https://storage.googleapis.com/oss-fuzz-introspector/netaddr-py/inspector-report/20230423/fuzz_report.html
This PR addresses the above issue due to a bug in limiting the python modules when running the fuzz introspector frontend logic. The problem is, in order to identify what code to anlyse we rely on some AST parsing for capturing relevant import modules, and there was an issue in this code which limited the modules we'd include.
Also improves the way we create links in HTML reports for python projects.
This fix will likely have impact on https://github.com/ossf/fuzz-introspector/issues/973 since Fuzz Introspector will have an improved way of including …
=> python-logic: improve import handling in frontend and refine link handling

src/fuzz_introspector/code_coverage.py, src/fuzz_introspector/html_report.py
For C++ targets sometimes the function table would show wrong data, specifically functions that would have code coverage was not sometimes set to 0.0%. This fixes this issue by giving proper naming arguments to the code coverage lookup logic.
=> code-coverage: fix issue in all functions table

tools/oss-fuzz-scanner/function_inspector.py, tools/oss-fuzz-scanner/scanner.py
I ran into an issue running some tests with the introspector tool `function_inspector` `print_function_details`. I traced the issue down to a problem in `run_fuzz_introspector_on_dir` where `IntrospectionProject` is always being called with language `c-cpp`. When this is called with `python` instead it runs correctly.
I've added an optional language param. Try
``` python
import function_inspector
function_inspector.print_function_details("croniter", ["croniter.croniter.croniter.get_next"])
function_inspector.print_function_details("croniter", ["croniter.croniter.croniter.get_next"], language="python")
```
I also added a type hint to the `functions_to_analyse` param as it look me a while to realise it only accepts a list of strings.
=> Optional language param for print_function_details

tools/web-fuzzing-introspection/app/webapp/templates/index.html
To help clarify:
- The difference between projects on the website and projects on oss-fuzz
- How to enable a project to be indexed
I might also add a feature for showing the number of OSS-Fuzz projects over time, and correlate this with the number of indexed projects.
=> webapp: add indexing faqs

frontends/java/pom.xml
The Soot library used in the Java frontend only support Jar file compiled with JDK 18 or before. Recently, there are java projects in OSS-FUZZ started to create Jar file with JDK 19+, that make the current Soot library (depends on ASM library) fails to handle them and cause error. This PR updates the Soot dependency version to the newest (v4.4.1) (which supports newest ASM library that could handle JDK 20 or before).
=> Java-frontend: Update soot dependency version

frontends/python/prepare_fuzz_imports.py
Fixes some broken builds with stack traces:
```
[Call(func=Attribute(value=Call(func=Attribute(value=Attribute(value=Name(id='traceback', ctx=Load()), attr='TracebackException', ctx=Load()), attr='from_exception', ctx=Load()), args=[Name(id='e', ctx=Load())], keywords=[]), attr='format', ctx=Load()), args=[], keywords=[])], keywords=[])
Step #6 - "compile-libfuzzer-introspector-x86_64": Inside of call instruction -- TestOneInput
Step #6 - "compile-libfuzzer-introspector-x86_64": <_ast.Attribute object at 0x7f5006849e20>
Step #6 - "compile-libfuzzer-introspector-x86_64": Traceback (most recent call last):
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/prepare_fuzz_imports.py", line 173, in <module>
Step #6 - …
```
=> frontend: python: catch possible exception

frontends/java/oss-fuzz-main.py, frontends/java/run.sh, frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
Fix the following logic for java frontend in order to reduce the resulting callgraph and method profile.
1. Add a boolean switch for auto-fuzz, constructors and details java method information will only be included when the frontend is called with the auto-fuzz switch on. This could prevent too much unnecessary information in the method profiles.
2. Add logic to avoid adding duplicate method in the method profile.
3. Fix logic in the mergePolymorphism method.
=> java-frontend: Fix frontend logic

src/fuzz_introspector/data_loader.py
This PR disables the multiprocessing data profile loading for jvm project beceause jvm projects generally have large data profile and multiprocessing of the large object will easily reach the maximum recursion limit and fail the fuzz-introspector process.
=> Disable multiprocessing for jvm project

tools/auto-fuzz/manager.py
The changes in #1073 add a new boolean switch for auto-fuzz. That switch controls if constructors information are needed in the resulting data.yaml profile. Those information is only needed for auto-fuzz so the default value of the switch is set to False. This PR fixes that by specifically turn on the switch in order to get the constructors information for the auto-fuzzing process. **This PR should only be merged after #1073 is merged.**
=> Java Auto-fuzz: Add auto-fuzz switch

src/fuzz_introspector/analyses/sinks_analyser.py
The code will throw and ValueError if line number string are not included for a given method in the profile. This PR fixes it by setting the line number to -1 as default for those method which does not provide line number information.
=> Sink analyser: Handle empty line number

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
Some legacy projects configure their maven pom.xml to use java 1.7 or prior version to build the project. But maven has already desupport java 1.7 or before and so this PR adds logic to replace that settings in the project pom.xml to force the project build using java 1.8+.
=> Auto-fuzz Replace old java version

tools/auto-fuzz/fuzz_driver_generation_jvm.py
In general, methods with no parameters have less fuzzing values, but they may be useful as setup or initialisation of objects. Some of them may also be useful to test some of the internal logic which depends on some fuzzed data preset in the object. None of these usages are necessary to fuzz on their own. Thus this PR filters them from the target method list to reduce the number of generation targets. At the same time it is preserved in the reference method lists to aid the fuzzing of other methods.
=> Auto-fuzz: Add filter to method with no arguments

frontends/java/oss-fuzz-main.py, frontends/java/run.sh, frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, frontends/java/src/test/java/ossf/fuzz/intropsector/soot/CustomSenceTransformerTest.java, tests/java/runTest.sh
Some oss-fuzz project have fuzzers like https://github.com/google/oss-fuzz/blob/master/projects/jettison/JsonFuzzer.java which only call constructor of the target project. There is also some project logic are initialised from constructor. That cause problems to Java-frontend static analysis of these project because the java frontend ignore constructor when generating call graphs by default. The original reason for that is to avoid some large project call graph to be flooding with not useful data. This PR fixes that by adding options for user to include what methods to be excluded during the frontend process. By default, general constructor will not be ignored.
=> Java-frontend: Fix constructor ignore option

tools/web-fuzzing-introspection/app/static/assets/db/.gitignore, tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py, tools/web-fuzzing-introspection/app/webapp/__init__.py, tools/web-fuzzing-introspection/app/webapp/models.py, tools/web-fuzzing-introspection/app/webapp/routes.py, tools/web-fuzzing-introspection/app/webapp/templates/index.html, tools/web-fuzzing-introspection/app/webapp/templates/project-profile.html, tools/web-fuzzing-introspection/app/webapp/templates/projects-overview.html
The central theme of this PR is to split data sources from the fuzz runs into two:
- data from code coverage
- data from fuzz introspector analysis
The goal is to make https://introspector.oss-fuzz.com/ display data on all OSS-Fuzz projects that have either code coverage or introspector builds successful. Currently it only shows results for project with successful introspector results, which limits the number of projects shown.
The common denominator between OSS-Fuzz projects in terms of artifacts produced by code coverage builds is line coverage. All but Python have more common denominators, e.g. function coverage. As such, we use line coverage from coverage builds.
However, we cannot make the full transition yet, because there is currently a limitation in the data we have available from …
=> webapp: extend and refactor

frontends/java/oss-fuzz-main.py, frontends/java/run.sh
The newly added method ignoring switch in #1055 have a slight typo for the variable name and the name of the default method to be excluded. This PR fixes it.
=> Java frontend: Fix wrong variable and method name

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
Some project have non-conventional method invocation that could cause resolution error in Soot analysis. For example, invoking static class method from instance object is a non-conventional code. This PR fixes the problem by setting the analysis option of Soot to ignore resolution error and also to skip possible resolution error as those method should be already be handled when we analyse the class itself.
=> Java Frontend: Fix staticness resolution error

frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/Callsite.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionElement.java
The current logic does not check for duplicate callsite in the function elements and create many duplication. This makes the resulting data.yaml file large. This PR fixes the checking to decrease the size of the data profile.
=> Java frontend: Fix duplicate callsite

tools/auto-fuzz/base_files.py, tools/auto-fuzz/constants.py
The maven version we are using is 3.6.3, but recently apache archive the version older than 3.8.8 (exclusively), thus the original download link for maven version 3.6.3 is moved from active distribution URL to archive URL. This PR fixes the link for the maven binary download by pointing the maven binary download url back to the archive one.
=> Auto-fuzz: Fix maven link

tools/auto-fuzz/post_process.py
When merging java fuzzers generated by auto-fuzz, it needs to changes the class name to avoid duplication of fuzzer class. The changes is incomplete as some of the fuzzers will use the class object as parameters and that is not changed in the logic. This PR fixes it by also changing the use of class object to the new class name in the fuzzers.
=> Auto-fuzz: Fix bug in auto-fuzz java fuzzers merging

tools/auto-fuzz/base_files.py, tools/auto-fuzz/post_process.py
This PR fixes the merging of successfully generated java fuzzer. The new logic combines all successful fuzzers into a single java fuzzer Fuzz.java in order to significantly reduce the time needed for processing separate fuzzers. It also gathers the heuristic success ratio information and displays it at the end of the merging process to act as a benchmark on analysing the quality of each heuristic for discovering limitations and next step improvement of the java auto-fuzz process.
=> Auto-fuzz: Fix java merge

tools/auto-fuzz/oss_fuzz_manager.py
Line 81 - 118 and line 121 - 138 of auto-fuzz oss_fuzz_manager.py is an exact duplication. Python does allow the exact same method to be defined more than one time and the later definition will overwrite the earlier definition. Thus this duplication does not run into any error but the code in Line81 - 118 is never called. To avoid confusion, this PR removes the duplicated code.
=> Auto-fuzz: Remove duplicate code

tools/auto-fuzz/fuzz_driver_generation_jvm.py
There is a missing list initialisation in some of the code resulting in missing object creation statement retrieval for most methods. This PR fixes that but adding proper list initialisation for the object_creation handled methods checking list.
=> Auto-fuzz: Fix wrong list initialisation

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, tools/auto-fuzz/benchmark/jvm/benchmark1/src/main/java/autofuzz/benchmark/object/AutoFuzzException.java, tools/auto-fuzz/benchmark/jvm/benchmark1/src/main/java/autofuzz/benchmark/object/SampleEnum.java, tools/auto-fuzz/benchmark/jvm/benchmark1/src/main/java/autofuzz/benchmark/object/SampleObject.java, tools/auto-fuzz/benchmark/jvm/benchmark2/src/main/java/autofuzz/benchmark/object/AutoFuzzException.java, tools/auto-fuzz/benchmark/jvm/benchmark2/src/main/java/autofuzz/benchmark/object/SampleEnum.java, tools/auto-fuzz/benchmark/jvm/benchmark2/src/main/java/autofuzz/benchmark/object/SampleObject.java, tools/auto-fuzz/benchmark/jvm/benchmark3/src/main/java/autofuzz/benchmark/object/AutoFuzzException.java, tools/auto-fuzz/benchmark/jvm/benchmark3/src/main/java/autofuzz/benchmark/object/SampleEnum.java, tools/auto-fuzz/benchmark/jvm/benchmark3/src/main/java/autofuzz/benchmark/object/SampleObject.java, tools/auto-fuzz/benchmark/jvm/benchmark4/src/main/java/autofuzz/benchmark/object/AutoFuzzException.java, tools/auto-fuzz/benchmark/jvm/benchmark4/src/main/java/autofuzz/benchmark/object/SampleEnum.java, tools/auto-fuzz/benchmark/jvm/benchmark4/src/main/java/autofuzz/benchmark/object/SampleObject.java, tools/auto-fuzz/benchmark/jvm/benchmark5/src/main/java/autofuzz/benchmark/object/AutoFuzzException.java, tools/auto-fuzz/benchmark/jvm/benchmark5/src/main/java/autofuzz/benchmark/object/SampleEnum.java, tools/auto-fuzz/benchmark/jvm/benchmark5/src/main/java/autofuzz/benchmark/object/SampleObject.java, tools/auto-fuzz/benchmark/jvm/benchmark6/src/main/java/autofuzz/benchmark/object/AutoFuzzException.java, tools/auto-fuzz/benchmark/jvm/benchmark6/src/main/java/autofuzz/benchmark/object/SampleEnum.java, tools/auto-fuzz/benchmark/jvm/benchmark6/src/main/java/autofuzz/benchmark/object/SampleObject.java, tools/auto-fuzz/benchmark/jvm/benchmark7/src/main/java/autofuzz/benchmark/object/AutoFuzzException.java, tools/auto-fuzz/benchmark/jvm/benchmark7/src/main/java/autofuzz/benchmark/object/SampleEnum.java, tools/auto-fuzz/benchmark/jvm/benchmark7/src/main/java/autofuzz/benchmark/object/SampleObject.java, tools/auto-fuzz/benchmark/jvm/benchmark8/src/main/java/autofuzz/benchmark/object/AutoFuzzException.java, tools/auto-fuzz/benchmark/jvm/benchmark8/src/main/java/autofuzz/benchmark/object/SampleEnum.java, tools/auto-fuzz/benchmark/jvm/benchmark8/src/main/java/autofuzz/benchmark/object/SampleObject.java, tools/auto-fuzz/fuzz_driver_generation_jvm.py
This PR fixes the frontend to allow a fully-qualified name stored for each method callsite. Then the callsite list of all target methods are retrieve to indicate which methods have already been covered by other target methods and thus filtering them out.
=> Auto-fuzz: Filter method

tools/auto-fuzz/benchmark_target.py, tools/auto-fuzz/fuzz_driver_generation_jvm.py
This PR fixes logic for callsite discovery and filtering logic. It also fixes some of the wrong benchmark target in the constants.
=> Auto-fuzz: Fix filtering logic and wrong benchmark target

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Enum classes are not supposed to be fuzzed. This PR filters them and also fixes the problem that protected enum method is included as fuzzing target.
=> Auto-Fuzz Filter enum class from target

tools/auto-fuzz/fuzz_driver_generation_jvm.py, tools/auto-fuzz/manager.py
Some gradle and maven build process will relocate source of dependencies into their base directory. This adds noise to the filtering of non-target project code. This PR fixes that by retrieving a list of class before the building of the target project to get a better list of what class is indeed in the target project for further filtering.
=> Auto-Fuzz: Refine filtering for dependencies

.github/workflows/google-java.yml, tools/auto-fuzz/benchmark/jvm/benchmark5/src/main/java/autofuzz/benchmark/Benchmark5.java, tools/auto-fuzz/benchmark/jvm/benchmark7/src/main/java/autofuzz/benchmark/Benchmark7.java
Java benchmarks for auto-fuzz are obviously written in Java, but the original java format checking CI does not monitor pull request from the new benchmark directory. This PR fixes the java format checking CI and some "historic" format problem in the java benchmark.
=> Java-format-ci: Fix java format checking CI

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionConfig.java
This PR fixes the logic for recursively retrieving the call-depth of each methods in the resulting method list.
=> Java-frontend: Fix calldepth calculation in frontend

tools/auto-fuzz/constants.py, tools/auto-fuzz/fuzz_driver_generation_jvm.py
This PR adds an additional filtering by filter out target methods that have call depth lower than the configured ratio.
=> Auto-fuzz: Add logic to filter method with less call depth

frontends/java/oss-fuzz-main.py, frontends/java/run.sh, frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, frontends/java/src/test/java/ossf/fuzz/intropsector/soot/CustomSenceTransformerTest.java
Some projects may include too much dependency libraries in their packaged jar files. This setting affects the effectivenes of frontend analysis on the project code as there are too much noise. This PR adds a feature to the java-frontend for filtering out classes that are not belongs to the target project. If the source directory of the target project is provided, the Java frontend will scan through that directory for a list of Java files. If a class is not in that list, it is skipped during the frontend processing.
=> Java-frontend: Fix class filtering in frontend

tools/auto-fuzz/base_files.py, tools/auto-fuzz/constants.py, tools/auto-fuzz/manager.py
This PR fixes a bugs in the build script logic on duplicate classes in jar files which fails some of the project build. This PR also changes some of the constants value to allow more target to process.
=> Auto-fuzz: Fix build error and change constant parameters

tools/auto-fuzz/fuzz_driver_generation_jvm.py
This PR fixes a bug in handling variables and return value with void type (empty).
=> Auto-fuzz: Fix error for return type checking

tools/auto-fuzz/constants.py, tools/auto-fuzz/fuzz_driver_generation_jvm.py
This PR fixes the logic for call depth filtering and change the default ratio after source folder filtering has been added to the frontend processing in #1101.
=> Auto-fuzz: Fix logic for call depth filtering

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Heuristic 1 combined all static method call for each class and only generated one fuzzer for each class. That decreases the success rate because some of the target static method calls may fail. This PR fixes the logic of heuristic 1 to create one fuzzer for each static method call instead of merging all static method calls in each class into one fuzzer. This PR also fixes some problematic exception handling.
=> Auto-fuzz: Fix heuristic

tools/auto-fuzz/fuzz_driver_generation_jvm.py
This PR fixes the target method name stored in the fuzzer comment for post processing.
=> Auto-fuzz: Fix target method comment

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
There is a missing statement and missing skipping logic in the java frontend, causing methods and constructors of abstract classes and interfaces missing the correct information if its class is concrete or not. Thats makes the auto-fuzz logic fails to filter them out from the target method list. This PR fixes the bug to ensure the class's concrete status of each method is correctly stored.
=> Java-Frontend: Fix frontend bug

tools/auto-fuzz/base_files.py
Some jar file in the project directory may include some unsolved dependencies, they should be solved and included in the build.jar. Thus there is no need to include them for the fuzzer compile process. This PR fixes the discovery logic of jar files and remove the possibility of compilation error on those unrelated jar.
=> Auto-fuzz: Ignore unrelated jar

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
There is a logic in auto-fuzz maven build to replace some values in the project's pom.xml to force the project build with java 1.8. But the text replacement logic is ambiguous and replace some settings unexpectedly and cause some projects fail to build. This PR fixes the logic to ensure only the precise java version setting has been replaced. This PR also fixes the problem when the provided target repo list file contains unwanted whitespace.
=> Auto-fuzz: Fix build error and git repo white space

tools/auto-fuzz/fuzz_driver_generation_jvm.py
This PR fixes the duplication in the object creation list which cause duplication of the resulting fuzzers.
=> Auto-fuzz: Fix duplication of object creation statement

tools/auto-fuzz/constants.py, tools/auto-fuzz/fuzz_driver_generation_jvm.py
This PR modifies the method call depth filtering logic. The new logic sort the target method list in descending order by the method call depth and only choose the top 20 methods as target.
=> Auto-fuzz: Fix filtering logic for method call depth

tools/auto-fuzz/constants.py, tools/auto-fuzz/fuzz_driver_generation_jvm.py
This PR fixes the logic of calldepth filtering. The filtering will only apply when there is too much target fuzzers. The maximum can be set by the constants value MAX_FUZZERS_PER_PROJECT.
=> Auto-fuzz: Fix filtering logic

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionConfig.java
When calculating calldepth, the current logic accidentally removed all constructor from the method list. This cause some auto-fuzz project fails to generate any fuzzers because no constructor information exists in the data.yaml file. This PR fixes the bug.
=> Java-Frontend: Fix missing constructor

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
Some project may requires different jdk version except for 15 and 8. This PR fixes the maven build command to let the project choose the default version needed they are using version 1.8+. Otherwise force it to at least build with version 1.8.
=> Auto-fuzz: Fix default jdk build

frontends/java/oss-fuzz-main.py, frontends/java/run.sh
Some project may include main method in their code in order for user to use their build jar directly in command line. In general, main method is the entrance method and don't have much logic to fuzz. Thus it has not too useful for both fuzz-introspector report and auto-fuzz. This PR fixes the configuration to exclude the main method by default.
=> Java-Frontend: Exclude main method

tools/auto-fuzz/base_files.py, tools/auto-fuzz/constants.py, tools/auto-fuzz/manager.py
Some java project depends on Protoc to generate the source code during project building phase. This PR fixes the logic to also retrieve and include the protoc binary in the project directory in order for those project to build.
=> Auto-fuzz: Fix protoc binary dependency

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
There is a bug in #1121 which has been fixed locally but does not commit and push to github by accident. This PR commits and submit that fix back to github repository.
=> Auto-fuzz: Submit missing fix

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
Some maven project does not include shadowJar or copy-dependencies goal in their settings. This result in missing dependencies in the build jar and fail to use them directly without manually including the dependencies. This PR fixes the maven build process to force it to copy all needed dependencies jar file to the target directory in order for auto-fuzz to use them.
=> Auto-Fuzz: Fix dependencies

tools/auto-fuzz/manager.py
Some project requires a long list of dependencies for using their code. This long list of dependencies with flood the java frontend and may cause failing because of out of memory and time out. This PR fixes the logic of project build to move the dependency jar into a separate directory which could then be excluded in the Java frontend process.
=> Auto-fuzz: Exclude some dependencies for java frontend

tools/auto-fuzz/constants.py, tools/auto-fuzz/manager.py
This PR add JVM handle in the project build phase of the manager to ensure it match the jdk used in oss-fuzz.
=> Auto-Fuzz: Add jvm handle

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
Some projects has included PMD checking in their project build. PMD checking is  a static analysis of the code to discover possible code style, redundant / unused code or possible code with errors. This process may fail the maven build of the project which the code may passes through the compiler normally without errors. In order to speed up the process and to ignore warnings in the original project, this PR adds additional flag to skip the PMD checking for maven build.
=> Auto-fuzz: Skip PMD checking

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
By default, gradle will turn on a daemon when a build process is started to save time for subsequent build. If different version of gradle wrapper is used, there will be multiple gradle daemon started in the background because different version of gradle will host its own gradle daemon. In general, it is not a problem. But for auto-fuzz, since we are aiming to process a long list of project which may have different gradle version specified in their gradle wrapper, it could generate a hugh memory consumption for starting loads of gradle daemon with different gradle version. That cause OOM quick in a batch execution. This PR fixes the command to force the gradle daemon to stop after the gradle project build completed.
=> Auto-fuzz: Stop gradle daemon after project build

tools/auto-fuzz/manager.py, tools/auto-fuzz/oss_fuzz_manager.py
This PR fixes the cleaning logic to remove large and build only folder from the base directory to reverse space for larger batch execution.
=> Auto-fuzz: Add logic to clean base directory

tools/auto-fuzz/manager.py
Some project contains symlink which some of them are dangling. This prevent the copy of the whole project tree using shutil and cause the auto-fuzz failed before project is built. This PR fixes the shutil.copytree config to allow copy of symlinks.
=> Auto-fuzz: Fix symlink config

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
The current logic for gradle build only consider the build property written in Groovy and causing some of the gradle build property written in Kotlin failed to build. This PR fixes the build logic to include both.
=> Auto-fuzz: Fix gradle build logic

tools/auto-fuzz/base_files.py, tools/auto-fuzz/oss_fuzz_manager.py
There is an error in combining the project jar files, causing ClassNotFoundException during generated fuzzers execution. This PR fixes the logic by pointing the classpath to the jar dump directory. Also, this PR fixes the cleaning logic after each fuzzer testing in oss-fuzz directory.
=> Auto-fuzz: Fix class not found exception and clean directory

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Wrong method is called for retrieving a random character. This PR fixes that.
=> Auto-fuzz: Fix wrong method for character

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
Some maven projects depend on ant run plugin to check code. This PR disable the legacy ant run to avoid error in ant encoding.
=> Auto-fuzz: Skip legacy ant build

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
This PR fixes the spotlessCheck skip bug when spotlessCheck task is not defined in the project.
=> Auto-fuzz: Fix gradle build skip

tools/auto-fuzz/base_files.py
The current logic look for all Fuzz*.java to compile, but it could cause error if the project have some java source file also named with similar name. This PR fixes the ambiguity by removing the unnecessary wildcard character.
=> Auto-fuzz: Fix ambiguous fuzzer name

tools/auto-fuzz/base_files.py, tools/auto-fuzz/constants.py, tools/auto-fuzz/manager.py
Some maven projects defined require toolchains. This PR fixes the setting to direct the toolchains to the JDK HOME. In addition, this PR updates the JDK version to 19 to accommodate more projects. Lastly, this PR add configuration to skip checkstyle plugin to avoid project fail to build because of formatting problem.
=> Auto-fuzz: Fix maven toolchain and java version

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
Fix the logic to use the downloaded gradle bundle rather then the wrapper.
=> Auto-fuzz: Fix gradle build version

tools/auto-fuzz/base_files.py
This PR removes empty line added to dockerfile and build.sh license.
=> Auto-fuzz: Remove empty line in license

tools/auto-fuzz/base_files.py, tools/auto-fuzz/constants.py, tools/auto-fuzz/manager.py
By default, the base builder and base runner of oss-fuzz jvm image are using OpenJDK15. This PR changes the JDK version back to Java15 to match the oss-fuzz settings. It also removes the download of JDK in the base build.sh and use the oss-fuzz provided JDK to test the generated fuzzers.
=> Auto-fuzz: Fix java version to match oss-fuzz default version

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
This PR fixes the method and class filtering logic to reduce the output data.yaml files for auto-fuzz generation.
=> Java-frontend: Fix method filtering for auto-fuzz

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
Some project need different gradle version to compile and failed to compile with the default gradle 7.4.2. This PR fixes the logic to use the gradle wrapper provided by the project instead of the default gradle.
=> Auto-fuzz: Fix gradle build

tools/auto-fuzz/base_files.py, tools/auto-fuzz/constants.py, tools/auto-fuzz/manager.py
OSS-fuzz use openjdk 15 as default. But there is quite a number of projects failed to build because of unsupported jdk version. This PR fixes the logic to try using different jdk version to build the project if it is failed to build with jdk15. The success version will be tracked and used in the project testing stage. The order of jdk version tried is JDK15 -> JDK17 -> JDK11 -> JDK8 which are the major updates of jdk and should cover a large amount of projects.
=> Auto-fuzz: Multiple java version

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Some project have a large list of available methods. The current logic create a few duplicated set of methods for easy process but it may lead to OOM or process killed by Linux OOM Killer. This PR fixes the logic to reduce the need in some of the record duplication to reduce the memory need during the fuzzer generation process. This could improve the success rate of the auto-fuzz process with lesser chance of OOM.
=> Auto-fuzz: Reduce size of instance method list

tools/auto-fuzz/fuzz_driver_generation_jvm.py
From manual integration, it is known that some projects have constructors that are worth fuzzing because the constructor itself covers many of the undelying code when creating the instance. This PR adds heuristic 11 to generate fuzzers that call viable constructor target which take at least one parameter.
=> Auto-fuzz: Add heuristic 11 for constructor

src/fuzz_introspector/data_loader.py
This PR changes the not preferred `type(data) != dict` checking to the preferred `not isinstance(data, dict)` checking.
=> Fix dict type checking

tools/auto-fuzz/fuzz_driver_generation_jvm.py
The search factory method call the handle argument method with a wrong None object and cause NoneType error. This PR fixes that bug.
=> Auto-fuzz: Fix bug

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
This PR fixes the following gradle and maven project build error.
1. Sources comment or javadoc using non-ASCII encoding and cause building errors.
2. Project that experiencing building error during javadoc and sources jar compiling and generation.
3. Maven project that requires JDK8 tools chain and specify it as java version 8 instead of 1.8.
=> Auto-fuzz: Fix gradle build and maven build

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
This PR fixes the source code filtering of java-frontend for auto-fuzz. If source directory is specified, then the exclude prefix option will be ignored. This allows some projects with "JDK-like" package prefix to be included in the analysis if the source files do existed.
=> Java-frontend: Fix filtering for auto-fuzz

src/fuzz_introspector/analyses/annotated_cfg.py
It's nice to have all functions used, including `malloc`, `free` etc. where we don't have source files available. It's easy to filter after in case
=> analyses: annotated cfg: include all 1st level funcs

frontends/java/oss-fuzz-main.py
As mentioned in #1174, some projects do not have any loose class files to package because of different reasons. Thus passing an empty list of class files to the jar tools result in errors in shell execution. This PR fixes that by adding a conditional check to only run the jar tools when any loose class files are discovered. It will not affect the frontend execution as jar files packaged by the project itself would still be discovered in later code.
=> Fix empty class file list bug

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py, tools/web-fuzzing-introspection/app/webapp/routes.py
Will expose in the webapp the data added in:
- https://github.com/ossf/fuzz-introspector/pull/1170
- https://github.com/ossf/fuzz-introspector/pull/1177
The API will be `/api/annotated-cfg?project=XX`. It will take a few days however to be visible on introspector.oss-fuzz.com as we're waiting for the new introspector changes to be shown there.
Also fixes a bug in `is_end` calculation during DB creation. We were one day too late before.
=> webapp: extend with data about annotated cfg

src/fuzz_introspector/datatypes/function_profile.py, src/fuzz_introspector/html_report.py
Keep the original function name as it is in the binary. This is needed for cases such as https://github.com/ossf/fuzz-introspector/issues/1165
=> core: output raw function names

tools/auto-fuzz/fuzz_driver_generation_jvm.py
It is found that some projects have methods that take string like input parameters using the CharSequence interface (implements by String class) as argument types. This avoid the current auto-fuzz logic to generate correct parameters for these methods. This PR fixes it by extending the primitive parameter handling method to take care of CharSequence parameter type as String object.
=> Auto-fuzz: Add CharSequence parameters handling

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp, src/fuzz_introspector/html_report.py
The current way we extract function names from arguments in LLVM is
rarely successful. This is because the names attached to the LLVM
Argument objects are empty, likely removed during the compilation
process. This adds an option for looking at debug information to spot
the right argument name.
Ref: https://github.com/ossf/fuzz-introspector/issues/1175
=> Use debug info for func args

tools/auto-fuzz/fuzz_driver_generation_jvm.py
The newly implement filtering logic for auto-fuzz in #1156 and #1161 add in more filtering to reduce the size of those method lists. But some of the logic actually avoid them to go deep into all the methods in the data.yaml file. This PR fixes some of the filtering logic to allow it to explore the full data.yaml list if possible.
=> Auto-fuzz: Fix filtering problem

src/fuzz_introspector/analyses/annotated_cfg.py
This is because I noticed some values were not always set in the fuzzer-profile function list, and accummulated-total-complexity in particular. Also outputs the raw function name.
=> annotated-cfg: extract function objects from merged project

src/fuzz_introspector/html_report.py
Ref: https://github.com/ossf/fuzz-introspector/issues/1187
=> output-json: write arg types as array of string, not string

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
Extends to recognizing bool, float, double, short and void.
=> frontends: llvm: extend type recognition

src/fuzz_introspector/analyses/annotated_cfg.py
Refines the definition of a top level target. To be a top level target a callsite should:
1. Have it so the destination function is located in source code corresponding to a file different than the fuzzer and one of the following:
1.a) Have its parent callsite in the fuzzer, i.e. transition from files.
1.b) Have call depth 1, which signals it's directly called from LLVMFuzzerTestOneInput and we know parent then is in the fuzzer source file.
There will still be some cases where it may not be trivial to identify the target if the fuzzer has another file with fuzzer-helpers. This becomes particularly difficult if the fuzzers are part of the upstream repository since we won't be able to distinguish fuzzer/non-fuzzer files -- without necessarily hacky heuristics such as "is the file under …
=> analyses: annotated-cfg: refine top-level API definition

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py
By default, gradle will discover toolchain path automatically, this may affect the correct jdk version detecting logic in auto-fuzz because gradle may detect the wrong version of JDK. This PR fixes the gradle build parameter by disabling the auto toolchain discovery of the gradle build and manually providing the JDK path to the gradle build system to avoid wrong java version detected.
=> Auto-fuzz: Fix gradle build toolchain discovery

doc/LocalBuild.md, doc/sphinx/source/installation-instructions/installation.rst
Minor changes after running into issues following the installation instructions here: https://fuzz-introspector.readthedocs.io/en/latest/installation-instructions/installation.html. Using the main branch of LLVM doesn't work, as much has changed, and the patches don't apply. Given OSS-Fuzz uses the LLVM 15 branch, it seemed reasonable to pin to that (can also drop to 14). LLVM 15 requires a `DCMAKE_BUILD_TYPE` to be specificed when configuring, given that 14 defaulted to `Debug` if unset, I've used that here. Also fix the name of the patch-file.
=> doc: installation doc fixes

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
It is discovered that Jazzer allows using custom methods with FuzzTest annotation to indicate the method to be fuzzed in addition to the default fuzzerTestOneInput method. The current JVM frontend logic fails to discover these custom methods and causes some projects using the annotation approach to fail to generate fuzzer profile for fuzz-introspector build. This PR fixes the frontend to add in annotation scanning to look for possible fuzzing methods if fuzzerTestOneInput is not found in the fuzzer class.
Example project: https://github.com/google/oss-fuzz/tree/master/projects/apache-cxf
=> Java-frontend: Fix entry method discovery

src/fuzz_introspector/utils.py
This has significant impact on speeding up `.yaml` loading. The `.yaml` files are often quite large and a bottleneck when running analyses.
In my experiment it takes e.g. the `htslib` `.yaml` file loading time down to ~2 seconds from ~2 minutes.
Requires the `libyaml-dev` package is installed
=> utils: enable c-based loading of yaml files

src/fuzz_introspector/analysis.py, src/fuzz_introspector/datatypes/project_profile.py
`for fd_k, fd in proj_profile.all_functions.items():` is expensive. This PR removes it from a loop when overlaying callgraph with coverage data.
=> project-profile: add an additional fd cache

tools/auto-fuzz/manager.py
In #1160, self-contained JDK support for Auto-fuzz has been added. But there is a bug in path variable definition which makes Auto-fuzz manager use the default JDK in the running environment rather than the chosen OpenJDK retrieved during runtime. This PR fixes that setting bugs to make Auto-fuzz self-contained and support different JDK versions.
=> Auto-fuzz: Fix jvm path bug

tools/auto-fuzz/manager.py
The python3 zipfile package does not preserve the file permissions. This PR fixes those logic by changing them into simple call process unzip functions.
=> Auto-fuzz: Fix zipfile bug

src/fuzz_introspector/analyses/calltree_analysis.py
The current logic fails to display the name of the constructor for jvm project because the method name returned by Soot is <init> or <cinit> for class constructors and browsers treat it as a general html tag. This PR adds additional logic to encode the < and > character to its entity name &lt; and &gt;  for correct display in the html.
=> JVM: Fix constructor display for jvm project

tools/web-fuzzing-introspection/app/webapp/routes.py
This happened today since a project was removed from OSS-Fuzz. The result was that the language of the project was lost, but we still had data on the project. In this case we will avoid these projects.
=> webapp: handle cases where language is not in dict

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py, tools/auto-fuzz/oss_fuzz_manager.py, tools/auto-fuzz/templates/jvm-ant/Dockerfile-template, tools/auto-fuzz/templates/jvm-gradle/Dockerfile-template, tools/auto-fuzz/templates/jvm-gradle/build.sh-template, tools/auto-fuzz/templates/jvm-maven/Dockerfile-template, tools/auto-fuzz/templates/jvm-maven/build.sh-template
This PR changes the logic for project building and static analysis before the fuzzer generation process. The new logic removes the project-building process from manager.py. Instead, it detects the language and project build type at the beginning and generates the base-autofuzz directory. The generated base-autofuzz directory is then passed to oss-fuzz for project building and save all the build-jar files for later use. This makes all the build project make use of the existing oss-fuzz settings and avoid the need to rebuild the process when testing each of the generated fuzzer integrations.
The old flow for the auto-fuzz manager.py
1. **Build the target project in the local environment.**
2. **Run static analysis using the local build of the target project.**
3. Create the necessary files …
=> Auto-fuzz: Adopt OSS-Fuzz for project build and avoid multiple build for the same project

tools/auto-fuzz/manager.py
The `run_on_projects` and `benchmark_on_projects` functions have similar logics but different parameters. This PR combines them to make the code better to read.
=> Auto-fuzz: Combine run_on_projects and benchmark_on_projects functions

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
Ref: https://github.com/google/oss-fuzz/issues/10970
We're likely still 1 day behind "today" when looking on the webapp at introspector.oss-fuzz.com. I'd like to keep it this way since we need to guarantee the DB collector runs at a point where all the coverage/introspector runs on OSS-Fuzz are done for the day and for some of the projects the runtime for that is many hours.
=> webapp: adjust DB creator to most recent date

tools/auto-fuzz/base_files.py, tools/auto-fuzz/fuzz_driver_generation_java.py, tools/auto-fuzz/manager.py, tools/auto-fuzz/oss_fuzz_project.py, tools/auto-fuzz/utils.py
This PR fixes the inconsistency language naming, in which "jvm" and "java" are used interchangeably. The new version changes all the use of "jvm" to "java" to keep it consistent throughout the code. This PR also modifies the language-specific branch in the main method of the manager.py.
=> Auto-fuzz: Fix Inconsistence language naming and fix project discovery logic.

tools/auto-fuzz/base_files.py, tools/auto-fuzz/constants.py, tools/auto-fuzz/manager.py, tools/auto-fuzz/utils.py
This PR removes the logic for downloading all supported versions of the JDK packages. Instead, only the required version of the JDK package is downloaded. This PR also generalises some of the preparation logic before static analysis to reduce language branching in the code.
=> Auto-fuzz: Reduce language branching logic and remove unused JDK

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py, tools/auto-fuzz/templates/java-introspector/Dockerfile-template, tools/auto-fuzz/templates/java-introspector/build.sh-template, tools/auto-fuzz/utils.py
This PR changes the logic for static analysis of the Java project. Instead of running the static analysis in the local environment, the new logic builds an OSS-Fuzz directory to run the static analysis for the Java project in the OSS-Fuzz docker image. This allows more flexibility in the settings and dependencies that are required for the Java static analysis without the need to load and depend on the settings in the local environment. The next step is to make this part generalize for all languages.
=> Auto-fuzz: Add oss-fuzz docker support for java static analysis

tools/auto-fuzz/base_files.py, tools/auto-fuzz/manager.py, tools/auto-fuzz/templates/java-ant/Dockerfile-template, tools/auto-fuzz/templates/java-ant/build.sh-template, tools/auto-fuzz/templates/java-gradle/Dockerfile-template, tools/auto-fuzz/templates/java-gradle/build.sh-template, tools/auto-fuzz/templates/java-introspector/Dockerfile-template, tools/auto-fuzz/templates/java-introspector/build.sh-template, tools/auto-fuzz/templates/java-maven/Dockerfile-template, tools/auto-fuzz/templates/java-maven/build.sh-template, tools/auto-fuzz/templates/python-introspector/Dockerfile-template
In the current logic, the Java project build and static analysis are separated into two steps and two OSS-Fuzz project copy and build is needed. This PR combines the project build and static analysis of Java to a single OSS-Fuzz project build to remove unnecessary executions and prepare for generalizing the static analysis step.
=> Auto Fuzz: Combine java build and static analysis

tools/auto-fuzz/manager.py, tools/auto-fuzz/utils.py
This PR makes use of the new constants properties and OSS-Fuzz templates for different languages to perform project build and static analysis of the target project in one OSS-Fuzz run. It removes the need to have separate language branches for the static analysis process. It also removes the need to rebuild project in later testing process by reusing some build files (currently only for java).
=> Auto-fuzz: Generalise and combine static analysis of multiple languages

tools/auto-fuzz/utils.py
This PR fixes a bug in retrieving a list of target project urls from provided `--target` argument.
=> Auto-fuzz: Fix bug in target file retrieval

tools/auto-fuzz/manager.py
Currently, the logic searches for build jar files from the OSS-Fuzz out directory after the project build and static analysis. As all project build and static analysis are done by using an OSS-Fuzz project with the name "base-autofuzz", the jar files in the $OUT directory will be accidentally used by the next project if it is not cleaned up after static analysis. This could cause errors if some project fails the static analysis because of errors in the jar files. This PR fixes the process by adding $OUT directory cleaning logic after static analysis to ensure static analysis of each project is done with a clean $OUT directory.
=> Auto-fuzz: Clean build directory for OSS-Fuzz after static analysis

frontends/python/prepare_fuzz_imports.py
Similar fix to what we have done with code coverage: https://github.com/google/oss-fuzz/pull/10409
Ref: https://github.com/google/oss-fuzz/pull/11150
=> frontends: python: adjust python importer for 3.9

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp, tools/auto-fuzz/c-cpp/build-generator.py
Adds setup such that the c/cpp now has a working PoC generating valid and good fuzzers for a simple project.
One of the changes needed for this is making some of fuzz introspector's functionality work with non-fuzzer binaries, i.e. to analyze libraries using the program analysis for fuzz introspector. There'll probably be more changes/improvements to this analysis.
The code is rough but am making a PR considering it now works. Will adjust in follow-up PR.s
When run on https://github.com/salzaverde/cppsimpleuri generates OSS-Fuzz integrations such as:
1)
`build.sh`:
```sh
#!/bin/bash
rm -rf //src/test-fuzz-build-1
cp -rf /src/cppsimpleuri /src/test-fuzz-build-1
cd /src/test-fuzz-build-1
mkdir fuzz-build
cd fuzz-build
cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CXX_FLAGS="$CXXFLAGS" ../
make || …
```
=> auto-fuzz: add poc for c-cpp fuzzer

tools/auto-fuzz/fuzzer_generator/fuzz_driver_generation_python.py, tools/auto-fuzz/manager.py, tools/auto-fuzz/objects/oss_fuzz_project.py, tools/auto-fuzz/templates/python-introspector/fuzz_1.py, tools/auto-fuzz/templates/python/fuzz_1.py
This PR fixes a few problems (as follows) for auto-fuzz generation on python project.
1. Wrong line indentation for generated fuzz_1.py
2. Missing license in fuzz_1.py template
3. Empty import statement for some heuristics
4. Incomplete exception list ending with comma
5. Wrong template files used after static analysis
6. Wrong stripping of class path.
=> Auto-fuzz: Fix problem for python fuzzer generation

tools/auto-fuzz/fuzzer_generator/fuzz_driver_generation_java.py
Following #1292, this PR continue to refine the heuristics for java fuzzer generation which include the following changes.
1. Merge heuristic 7 to heuristic 1 and 2.
2. Merge heuristic 8 to heuristic 2.
3. Merge heuristic 9 to heuristic 2.
4. Remove heuristic 10 and related logic because it handles class object parameters which are not possible to retrieve from the current Java frontend using Soot, which makes the fuzzers generated by this heuristic always fail.
5. Rename heuristic 11 to heuristic 3.
This is the last PR for heuristics refinement. As a result, there are only 3 heuristics left. Heuristic 1 targets all static methods in the target project. Heuristic 2 targets all non-static methods in the target project with different consideration of object creation approaches (old …
=> Auto-fuzz: Refine heuristics for java fuzzer generation

frontends/java/src/main/java/ossf/fuzz/introspector/soot/SootSceneTransformer.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/utils/CalltreeUtils.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionConfig.java
Following #1294, this PR continues to reorganize the java frontend code by moving FunctionConfig utils function back to the yaml class and fixes the related method calling.
=> Java frontend: extract function config methods

frontends/java/src/main/java/ossf/fuzz/introspector/soot/SootSceneTransformer.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/utils/CalculationUtils.java
Following #1296, this PR continues to revamp Java frontend code. This PR extract calculation related methods to separate utils package.
=> Java-frontend: Extract calculation related method

tools/web-fuzzing-introspection/app/webapp/templates/projects-overview.html
This adds a percentage sign in the projects overview to indicate the unit used.
=> webapp: add proper suffix

frontends/java/src/main/java/ossf/fuzz/introspector/soot/SootSceneTransformer.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/utils/BlockGraphInfoUtils.java
Following #1297, this PR continue to revamp the Java-frontend code. This PR extract block graph information retrieving methods to utils package.
=> Java-frontend: Extract block graph related methods

frontends/java/src/main/java/ossf/fuzz/introspector/soot/SootSceneTransformer.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionConfig.java
This PR follows #1298. It reorganise code in SootSceneTransformer class.
=> Java-frontend: Reorganise code for SootSceneTransformer

tools/auto-fuzz/fuzzer_generator/fuzz_driver_generation_java.py, tools/auto-fuzz/fuzzer_generator/fuzz_driver_generation_python.py, tools/auto-fuzz/manager.py, tools/auto-fuzz/objects/fuzz_target.py
This is the first PR aiming to move the fuzzer_generator process into docker containers. This PR adds additional functionality to allow serialising and deserialising of FuzzTarget object. This setting allows the fuzzer_generator of different language to store the result in a file (instead of directly returning a python list for possible targets) for the manager to process which make the fuzzer_generator possible to work in a docker image in later PRs.
=> Auto-fuzz: Add serialising and deserialising for FuzzTarget object.

tools/auto-fuzz/oss_fuzz_manager.py
This PR fixes an indentation bug when `log_dir` is `None`.
=> Auto-fuzz: Fix indentation bug

tools/auto-fuzz/templates/base_files.py, tools/auto-fuzz/templates/fuzzer-generator/Dockerfile-template, tools/auto-fuzz/templates/fuzzer-generator/build.py-template, tools/auto-fuzz/templates/fuzzer-generator/project.yaml
This PR adds a new OSS-Fuzz base files template for fuzzer generation process. The new logics in the later PR uses the new template to run fuzzer generators for different language in the OSS-Fuzz docker container.
=> Auto-fuzz: Add new OSS-Fuzz template files for fuzzer generation

tools/auto-fuzz/README.md, tools/auto-fuzz/fuzzer_generator/fuzz_driver_generation_java.py, tools/auto-fuzz/fuzzer_generator/fuzz_driver_generation_python.py, tools/auto-fuzz/manager.py, tools/auto-fuzz/utils.py
Following #1312, this PR uses the newly created OSS-Fuzz base file templates to run the fuzzer generation process. This eliminate the need to install separate virtual environment and dependencies for the Auto-fuzz user.
This PR needs rebase after #1312 is merged in.
=> Auto-Fuzz: Use OSS-Fuzz docker container to complete fuzzer generation

tools/auto-fuzz/manager.py, tools/auto-fuzz/oss_fuzz_manager.py
This PR adds in project cleaning for the build_jar directory which are used to avoid rebuilding of projects. This PR also adds in logic to mute the oss_fuzz_manager calls to OSS-Fuzz.
=> Auto-fuzz: Add project clean and mute log

tools/auto-fuzz/fuzzer_generator/fuzz_driver_generation_java.py
There is a bug in the fuzzer generation for java. There is a missing semi-colon in the code which makes fuzzer fails it is not the last statement in the fuzzer program. This PR fixes it.
=> Auto-fuzz: Fix semi-colon missing bug

tools/auto-fuzz/templates/java-ant/build.sh-template, tools/auto-fuzz/templates/java-gradle/build.sh-template, tools/auto-fuzz/templates/java-maven/build.sh-template
In #1269, each Java target project are only build once before static analysis and all the build jar files are reused. The logic does not exclude the Fuzz.jar for storing the class file of the compiled plain Fuzz.java used in the static analysis. Thus the Fuzz.jar will also be copied to the generated folder for each of the possible targets and include in the class path for executing the generated Fuzzer. Since the Fuzz.jar appears early in the classpath list, the Fuzz.class inside the jar file are always used instead of the Fuzz.class compiled lively for the generated Fuzz.java. This cause the fuzzer validation stage always getting the result of fuzzing the plain Fuzz.java instead of the result of running the generated fuzzers. This PR fixes the bug by excluding the Fuzz.jar during the …
=> Auto-fuzz: Fix duplicate fuzzer bug

tools/web-fuzzing-introspection/app/webapp/routes.py, tools/web-fuzzing-introspection/app/webapp/templates/api.html
Somehow these names where missed twice in the refactoring;
- #1322 
- #1319 
Ref: #1318
=> web_app: Fix inconsistent naming for project-summary endpoint

tools/web-fuzzing-introspection/app/static/assets/db/.gitignore, tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
This makes all introspector data available through the API, which can be useful for experimenation and exploration. Discussed in https://github.com/ossf/fuzz-introspector/issues/1323
Ref:
https://github.com/ossf/fuzz-introspector/issues/1323#issuecomment-1824807425
=> webapp: save Fuzz Introspector reports in a .zip file

tools/web-fuzzing-introspection/app/webapp/routes.py, tools/web-fuzzing-introspection/app/webapp/templates/project-profile.html
This is useful for when projects no longer have working coverage builds, then we still have links to old coverage reports.
=> webapp: show links to old coverage reports

tools/web-fuzzing-introspection/app/webapp/routes.py, tools/web-fuzzing-introspection/app/webapp/templates/project-profile.html, tools/web-fuzzing-introspection/app/webapp/templates/projects-overview.html
This includes projects that do not have an up-to-date coverage build, meaning their data will be out of date. However, this makes it a lot easier to track all projects, and even projects without code coverage builds may have valuable historical data.
=> webapp: show all projects with data in profile-overview

src/fuzz_introspector/html_report.py
We have callsites for each function with respect to what functions they are calling. However, it's currently not output to `summary.json`. This fixes it. 
Ref: https://github.com/ossf/fuzz-introspector/issues/1343
=> json-reporting: add callsites dictionary to output

frontends/java/src/main/java/ossf/fuzz/introspector/soot/SootSceneTransformer.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/utils/SinkDiscoveryUtils.java
This PR adds additional logic to the custom SootSceneTransformer to save the full project class-method map. The full project class-method map is needed to discover the call paths to sink methods in later enhancement PRs. This PR also adds an additional utility class for discovering all sink methods that are existed in the target project, no matter if it is statically reached by the fuzzers or not.
=> Java-frontend: Save full project class-method map

src/fuzz_introspector/analyses/sinks_analyser.py
This PR is the third PR for revamping the Sink Analyser. This PR changes the logic for call path discovery and generation. The new logic aims to discover all possible call paths to the target sink functions if no fuzzers statically reach the target sink functions.
=> Sink Analyser: Change callpath discovery logic and generation

tools/web-fuzzing-introspection/app/webapp/routes.py, tools/web-fuzzing-introspection/app/webapp/templates/project-profile.html
Follow-up to https://github.com/ossf/fuzz-introspector/pull/1355 where we now also make the report links available
=> webapp: provide links to most recent FI report

frontends/java/src/main/java/ossf/fuzz/introspector/soot/SootSceneTransformer.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/utils/BlockGraphInfoUtils.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionElement.java, tests/java/test11/.config
This PR fixes a bug in handling method names. The method name stored in the functionReached field of the YAML is not compatible with the functionName field, this causes some undiscovered functions reached in the searching process. This PR unify the method names for both field.
=> Java-frontend: Fix method name bug

src/fuzz_introspector/analyses/sinks_analyser.py, src/fuzz_introspector/analysis.py, src/fuzz_introspector/html_report.py
In the current logic, all analysers are executed during the post-processing period no matter if it is active or not. The only difference is that the html string result is included in the report.html while the html string result for those inactive analysers is discarded. This could result in additional actions for some of the analysers. For example, the sink analyser will generate a set of call path html files during analysing process and if the sink analyser is not active, those generated call path html files are not used and become redundant. This PR fixes the base AnalysisInterface class by adding a flag to indicate if an HTML display is needed for a specific analyser, the individual analyser can determine what to do with that flag and avoid redundant processes if html display is not …
=> Analyser: Add flag for html display of analyser

frontends/java/src/main/java/ossf/fuzz/introspector/soot/SootSceneTransformer.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/utils/CalltreeUtils.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionElement.java
This PR adds base Java method and class information even if the frontend code is not run by autofuzz. This set of base information helps the sink analyser filter out unreachable APIs for sink functions/methods called path generation.
=> Java-frontend: Add base java info

src/fuzz_introspector/analyses/sinks_analyser.py, src/fuzz_introspector/constants.py, src/fuzz_introspector/datatypes/function_profile.py
Following #1358 and #1359, this PR further reduce possible redundant in sink function callpath generations by an additional filtering. From #1359, base accessible information for java methods is provided from the frontend result. This PR adds a new filter to avoid generating callpaths HTML files for inaccessible callpaths, that is callpaths start with methods that are not directly callable by users. These inaccessible call paths are filtered out to reduce the number of possible call paths for each sink function discovered. This PR also change the max count for call path generation per sink functions to a configurable value in constants.py and significantly decreases the default value to 2. This could help avoid flooding a long list of possible call paths which are useless for analysis …
=> Sink analyser: Filter inaccessible callpath

frontends/java/src/main/java/ossf/fuzz/introspector/soot/SootSceneTransformer.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/utils/BlockGraphInfoUtils.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/utils/CalltreeUtils.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/utils/SinkDiscoveryUtils.java
This PR refines the Java frontend to include those sink methods exist in the target project but not statically reachable from any fuzzers. The methods in the project that reaches those sink methods are also included for reference.
=> Java-frontend: add non-reachable sink methods

tests/cpp-simple-example-1/fuzzer.cpp
This is to make it easier to test some cpp introspection that needs to deconstruct how cpp classes are defined.
=> tests: add field to class in cpp

src/fuzz_introspector/analyses/sinks_analyser.py
This PR fixes the description of the Sink Analyser.
=> Sink Analyser: Fix description

src/fuzz_introspector/analyses/sinks_analyser.py
This PR removes duplication of blocker functions.
=> Sink Analyser: Filter duplicate blockers

src/fuzz_introspector/analyses/sinks_analyser.py
This PR reoganizes the display of CWE tables and remove empty tables.
**This PR needs rebase after #1369 is merged.**
=> Sink Analyser: Fix CWE table display

src/fuzz_introspector/analyses/sinks_analyser.py
This PR adds logic to filter invalid call paths and blocker functions that are initiated from fuzzer classes.
**This PR needs rebase after #1370 is merged.**
=> Sink Analyser: Filter false positive

tests/simple-non-fuzz-test-0/.gitignore, tests/simple-non-fuzz-test-0/build_all.sh, tests/simple-non-fuzz-test-0/fake-test.c
Recently the option of analyzing non-fuzzer binaries was added [here](https://github.com/ossf/fuzz-introspector/pull/1280).
This adds a test for this logic.
=> tests: add non-fuzzer test

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
This is to make sure the configs are set if we analyze the code in non-fuzzer mode
=> frontends: llvm: enable configs earlier

tools/auto-fuzz/post_process.py
This PR fixes a bug in the post-processing `run` command. The post-processing logic uses `range(int)` to loop through the directory and `range(int)` will only loop from `0` to `int - 1`, thus the results from the last idx directory are missed. If there is only one result directory, it will not be displayed at all. This PR fixes the logic by adding a flag to indicate if any result directory exists, if yes, loop through the max idx number + 1 to make the post-processing work for all existing directories.
=> Auto-fuzz: Fix post processing bug

tools/auto-fuzz/constants.py
This PR adds more jdk version support for Java project build. The logic first tries JDK15 which is the default version used in the OSS-Fuzz Java Docker image. If the project fails to build with JDK-15, the logic will try the JDK version range from JDK21 down to JDK8 until one of the build success and exits.
This is the first PR for revamping the java project auto-building.
=> Auto-fuzz: Add more jdk version support

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
We shouldn't store these on the webapp, but rather keep the webapp as light as possible to make deployments easier.
Instead, we could offer a simple script that downloads all of the reports. The downside of this is that it will take time for consumers.
=> webapp: do not dump introspector reports do disk

src/fuzz_introspector/analysis.py
and avoid return value in funcname
=> func-sig: handle namespaced non-class functions 

src/fuzz_introspector/debug_info.py
This caused there to be no types available in the APIs on the webapp.
=> debug_info: fix bug that excludes all types

oss_fuzz_integration/oss-fuzz-patches.diff, src/fuzz_introspector/analysis.py, src/fuzz_introspector/data_loader.py, src/fuzz_introspector/debug_info.py, src/fuzz_introspector/html_report.py
This replaces the existing debug data handling. We now rely on yaml formats rather than the ad-hoc approach previously. Currently both are in place but we should switch to the new one.
=> core: add structured debug info handling for function signatures

src/fuzz_introspector/analysis.py
This caused some issues when matching functions from core FI to functions from debug information.
=> core: normalize file paths when matching debug information

tests/simple-example-0/build_all.sh, tests/simple-example-0/build_cov.sh
Otherwise you'll see: `clang: error: unknown argument: '-flegacy-pass-manager'` when running through `localbuild.md` and things wont work as expected. LLVM 18 has been used since #1440.
=> examples: remove `-flegacy-pass-manager` usage

src/fuzz_introspector/debug_info.py
The data looks e.g. 
```
"94352041631088": {
"raw-types": [
"DW_TAG_structure_type",
"sam_hrec_type_s"
],
"string_type": "sam_hrec_type_s",
"is-struct": true,
"struct-elems": [
{
"addr": 94352041608544,
"elem_name": "next",
"elem_friendly_type": "sam_hrec_type_s *"
},
{
"addr": 94352041608672,
"elem_name": "prev",
"elem_friendly_type": "sam_hrec_type_s *"
},
{
"addr": 94352041608800,
"elem_name": "global_next",
"elem_friendly_type": "sam_hrec_type_s *"
},
{
"addr": 94352041608928,
"elem_name": "global_prev",
"elem_friendly_type": "sam_hrec_type_s *"
},
{
"addr": 94352041609312,
"elem_name": "tag",
"elem_friendly_type": "sam_hrec_tag_t *"
},
{
"addr": 94352041609440,
"elem_name": "type",
"elem_friendly_type": "khint32_t"
}
],
"is-enum": false,
"enum-elems": []
},
"94352041608544": { …
```
=> core: addr-indexed type information file

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
This is useful when you e.g. want to analyse a single .bc file, which seems more meaningful now that we also extract debug symbols and output data about each function in the .bc that can be input to program analysis tooling.
=> frontends: llvm: make it possible to force llvm analysis

src/fuzz_introspector/analyses/optimal_targets.py
The optimal targets analysis identifies a set of functions that together will cover a large part of the project under analysis. It would be nice to expose these to [oss-fuzz-gen](https://github.com/google/oss-fuzz-gen) so the auto-fuzz generation can optimally cover a project.
This change exposes the optimal targets analysis to `summary.json` so the web app can capture it.
=> analysis: expose optimal targets to summary.json

oss_fuzz_integration/oss-fuzz-patches.diff
To the latest clang-18 upgrade on the OSS-Fuzz side. We no longer need the temporary clang-18 upgrade here
=> oss-fuzz: update patches

src/fuzz_introspector/analyses/sinks_analyser.py, src/fuzz_introspector/analysis.py, src/fuzz_introspector/datatypes/function_profile.py, src/fuzz_introspector/html_report.py, tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py, tools/web-fuzzing-introspection/app/webapp/__init__.py, tools/web-fuzzing-introspection/app/webapp/models.py, tools/web-fuzzing-introspection/app/webapp/routes.py
Some methods in a JVM project could be inaccessible because of different reasons. Also, the present of sink analyser tool also requires adding information of some sink methods in the JVM library for processing. This PR adds extra properties in the FunctionProfile to identify if the method is publicly accessible, belongs to the JVM base library or belongs to a Enum classes. Different logic is then using these new properties to consider if some of those special methods needed to be ignored. 
The following changes  have been made.
1. Add three additional boolean properties in FunctionProfile, the values of the properties is determined by the JavaMethodDetails in the data.yaml file for Java project, and default value is used for non-Java project which should not affect the logic.
2. Add the …
=> [JVM] Add logic for filtering inaccessible and special methods

src/fuzz_introspector/analysis.py
We need to include `struct` in the name when used.
=> analysis: add `struct` to types when observed

oss_fuzz_integration/runner.py
This makes it possible to run introspector runs and use them in oss-fuzz-gen without having the webserver shown.
=> oss-fuzz: enable avoiding webserver for introspector runs

scripts/oss-fuzz-gen-e2e/build_all.sh, scripts/oss-fuzz-gen-e2e/run_all.sh
Adds scripts needed for easily running an OSS-Fuzz-gen end-to-end run. This means a single script for:
1) Building and running the fuzzers of a project to collect a fresh
coverage report a fresh introspector report.
2) Creating a new local version of the webapp database such that
OSS-Fuzz-gen can use the local API with the fresh data.
3) Running of an OSS-Fuzz-gen experiment.
=> scripts: add oss-fuzz-gen end-to-end set up

tools/web-fuzzing-introspection/app/static/assets/db/must_include_small.config, tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
This may be enabled later. It's currently not used by any apps (e.g. oss-fuzz-gen), and it's taking up a lot of storage.
=> webapp: disable dumping type info json files

src/main.py
The results should not go in the main report file anymore (`summary.json`) but should be place in individual files. Disabling for now to prepare for this.
=> disable sink analyzer by default

frontends/java/oss-fuzz-main.py
This PR changes the default value for source directory when calling the Java frontend of fuzz-introspector. It is understand that the source directory can be found in `$OUT/$SRC` in the base runner docker when introspector is running, this PR changes the default value to that directory for source searching if it does exist.
=> [Java] Add default for project source

src/fuzz_introspector/constants.py, src/fuzz_introspector/datatypes/fuzzer_profile.py, src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/html_report.py, src/fuzz_introspector/json_report.py, tools/web-fuzzing-introspection/app/static/assets/db/oss_fuzz.py, tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py, tools/web-fuzzing-introspection/app/webapp/__init__.py, tools/web-fuzzing-introspection/app/webapp/data_storage.py, tools/web-fuzzing-introspection/app/webapp/routes.py
This PR aims to store constructor information separately for java projects. In original code, constructors of java proejcts are ignored in the all_functions dictionary. Instead of ignoring them, now these constructors (in FunctionProfile format) are stored in a separate dict and are then processed separately. Lastly, these processed constructors are then added into the summary.json as other normal functions for further process.
=> Fix constructor display in summary.json

tools/web-fuzzing-introspection/app/webapp/routes.py
The `append` taints the list -- it should be `extend`. But even so, we do not want to `extend` as this simply continues to grow. We want to re-assign to a new variable in this case.
=> webapp: fix bug that taints all_functions

tools/web-fuzzing-introspection/app/main.py
This PR fixes a possible wrong variable type for port because os.environ always return a dict with string keys and values.
=> webapp: Fix wrong port type bug

tools/web-fuzzing-introspection/app/static/assets/db/oss_fuzz.py
This PR fixes a bug in extract_new_introspector_constructors() which calls to a wrong url variable.
=> webapp: Fix bug for wrong variable use

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR fixes some possible unbound variable. By the logic, project could be None and that cause the access of project attribute result in error. This PR fixes that.
=> webapp: Fix possible none project type

tools/web-fuzzing-introspection/app/webapp/routes.py
The get_build_status_of_project(str) function could return None type and cause the further access to the attributes of the bs object fails. This PR fixes the problem by adding a None check and return error before it is accessed.
=> webapp: Fix possible unbound bs variable

scripts/oss-fuzz-gen-e2e/web_run_all.sh
Adding one more runner script for oss-fuzz-gen. This is quite similar to the existing (could probably be merged later) but avoids running the projects in a local oss-fuzz first. Makes it quicker to test when there is no need to rerun the fuzz-introspector oss-fuzz runs.
Also extends it with options to make it easier test wider in oss-fuzz-gen.
=> oss-fuzz-gen: add one more runner script

tools/web-fuzzing-introspection/app/webapp/models.py, tools/web-fuzzing-introspection/app/webapp/routes.py
This PR fixes the wrong overwrite for the __dict__ attribute. It is an attribute instead of function.
=> Fix wrong overwrite of __dict__ attribute

tools/web-fuzzing-introspection/app/webapp/routes.py
In #1562, a new class property `project_repository` for the models.Project class has been added. Also, a new mandatory argument is added to the class constructor in order to set the value. But that PR does not fixed the call in routes.py and could cause error because it is a mandatory argument. This PR fixes by adding the None value to the constructor call.
=> webapp: Fix missing arguments for model Project constructor

.github/workflows/webapp-mypy.yml, tools/web-fuzzing-introspection/.pyrightconfig.json
This PR adds a new CI for running mypy and pyright tool on the webapp tool. It could helps to detect possible typing and formatting problems. 
This PR targets #1560.
As this PR enforce a new checking on webapp, the code needed to be fixed. Thus this PR should only be merged in after #1564 #1565 #1566 #1567 #1568 #1569 #1570 #1577 are all merged in. These PRs fix the preliminary set of problems and bugs when applying this new CI.
=> Add mypy / pyright to a new CI for webapp tool

tools/web-fuzzing-introspection/app/webapp/routes.py
There is a bug in route.py for API /project-profile. The list of function of interest at the bottom of the page has a set of wrong coverage url which the initial is repeated and cause link error. This PR fixes the problem by removing the redundant string concatenation in the coverage url saving.
=> webapp: Fix wrong coverage url

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR fixes a bug in oracle_3 function where the all_functions argument is being overwritten at the beginning accidentally.
=> webapp: Fix argument overwritten bug

tools/web-fuzzing-introspection/app/webapp/routes.py
The request parameter `begin_line` and `end_line` for the api `/api/project-source-code` is passed directly to `int()` without checking which could throw an unexpected ValueError if non-valid string is provided. This PR fixes that by capturing the possible ValueError and return an error message json instead.
=> webapp: Fix possible ValueError on invalid parameter

tools/web-fuzzing-introspection/app/webapp/routes.py
If the provided project name is invalid, the target_project will be None and this will cause subsequent action in oracle_2 to process all functions for all projects because none of the project name matches. This create a possible DoS situation. This PR adds a None type checking and return an error message if target project not found.
=> webapp: None type bug create possible DoS

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR temporary disabled api `/api/addr-to-recursive-dwarf-info` to avoid internal server error because of missing type json. This type json is temporary disabled for saving storage space in the server.
=> webapp: Temporary disable API to avoid errors

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR fixes the None type checking by changing them to the recommended `is None` and `is not None` approach to avoid  `__eq__()` pollution. This is part of the work to fulfil the type checking when type is added in #1583.
=> webapp: Use recommended None checking method

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR adds a None type checking to ensure datestr must not be None. This is part of the work to fulfil the type checking when type is added in https://github.com/ossf/fuzz-introspector/pull/1601.
=> webapp: Ensure datestr is not None

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR fixes the None type checking for latest_introspector_datestr to ensure it has been checked for all branches. This is part of the work to fulfil the type checking when type is added in https://github.com/ossf/fuzz-introspector/pull/1601.
=> webapp: Ensure None checking for all cases

scripts/oss-fuzz-gen-e2e/build_all.sh
The `build_all.py` installs the dependencies for the fuzz-introspector in the virtual environment. But it misses the installation of the dependencies from the webapp which is also needed for running the oss-fuzz-gen script. This PR fixes that by adding an additional requirement installation statement in `build_all.py` to avoid execution error in the `run_all.sh` when some dependencies specifically for the webapp (like flask) is missing. This PR also changed the python3.11 to the general python3 to allow backward compatibility.
=> oss-fuzz-gen-script: Fix missing dependency

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR fixes the typing for the lines variable to ensure it must be integer before use. This is part of the work to fulfil the type checking when type is added in #1601.
=> webapp: Ensure int typing for the lines

tools/web-fuzzing-introspection/app/webapp/models.py, tools/web-fuzzing-introspection/app/webapp/routes.py
In #1584, the 3 default values in routes.py for initialize an empty models.Project object has been changed from None to empty Dict and string for fulfilling later type checking by mypy. But this change accidentally break some of the projects. Some projects (Either a wrong project or we only have a build status for it) will call this code to generate an empty project for further process. And the rendering template in template/project_profile.html actually consider if these arguments are None in order to determine if data should be retrieved from it (a Dict). Thus changing them to an empty Dict and trying accessing its content with an non-exist key cause the rendering to throw an exception. This PR fixes that by reverting them to default None value. To fulfil the mypy check, this PR also …
=> webapp: Fix bug in wrong empty checking

tools/web-fuzzing-introspection/app/webapp/models.py
It is found that the default value for reached_by_fuzzers of the Function object is wrong at the beginning and that cause the typing added in #1600 also wrong. This PR fixes both the typing and default value of the reached_by_fuzzers in the Function object.
=> webapp: Fix type error bug

scripts/oss-fuzz-gen-e2e/run_all.sh
The building and executing of fuzzers in the target projects may break the display encoding because of random character use in some of the fuzzers. The broken text encoding could affect the later oss-fuzz-gen execution. This PR fixes that by adding a reset command after each project introspector run to recover from possible display text encoding breaking problem.
=> Add reset for each introspector run

tools/web-fuzzing-introspection/app/webapp/routes.py
In #1610, the support for excluding static functions in oracles has been added. The static function checking is supported by the is_static function. The is_static function takes in a source's begin and end line information and invokes the extract_lines_from_source_code function to extract the source for the target function to determine if it is a static function or not. Although the logic has checked if the begin src line is larger than the total source line to avoid index overflow, there is a missing check for a negative begin src line which causes a possible index underflow and results in an Internal Server Error when querying the oracle with `exclude-static-functions=True`
This will happen because in #1555, the webapp has introduced JVM constructors as part of the function candidates, …
=> [webapp] Fix possible index error for oracles

frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionConfig.java
There is a mechanism in FunctionConfig to check whether a function exists in the list before adding it to avoid duplication. However, there is a bug in which setFunctionElements does not check for duplication when renewing the function list. This makes the final output data.yaml file contains quite some amount of duplicated data. This PR fixes that and the size of data.yaml for the Java project should be significantly decreased.
=> [Java-frontend] Fix duplication bug

frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionElement.java
In #1396, a new variable functionLinenumberEnd is added to indicate the possible ending line number of specific functions/methods in the source file. The Java frontend does not comply with this new element and always has the functionLinenumberEnd equal to -1. 
To accommodate additional API to retrieve the real method source location for oss-fuzz-gen cross reference, it is necessary to know both the starting line number and ending line number of a method to retrieve the source code for reference. 
This PR fixes the Java frontend logic to calculate the ending line number using the data contained in the active body of the SootMethod. Then the ending line number is added to the function elements and output in the data.yaml file for fuzz-introspector to process. If the logic fails to retrieve …
=> [Java-frontend] Add functionLinenumberEnd to methods

tools/web-fuzzing-introspection/app/webapp/routes.py
The static checks is expensive (we should probably push this into the frontends), and having it before e.g. checking if function's project is the same as the target project caused a significant slowdown. This delays the check to the very end for performance reasons.
=> webapp: delay static checking for performance reasons

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR fixes the `/api/function-source-code` API to accommodate the Java project. This is needed because the `function_filename` field for each Java method in the webapp only stores the class name of the target method. Thus transformation is needed to locate the path of the needed source file.vv
=> webapp: Fix function-source-code api to accommodate java source files

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR fixes the wrong `src_end` value returned by the `/api/function-source-code` api in the webapp.
=> webapp: Fix wrong src_end return bug

src/fuzz_introspector/analysis.py, src/fuzz_introspector/debug_info.py, src/fuzz_introspector/html_report.py
In https://github.com/google/oss-fuzz-gen/pull/370 some harnesses were found to have a lot of unnecessary header files included in the prompts. This is an effort to fix this by identifying where functions are declared in header files, such that we can narrow it down further which files to include.
=> core: find where functions are declared in header files

tools/web-fuzzing-introspection/app/webapp/routes.py
The experiment in https://github.com/google/oss-fuzz-gen/pull/370 showed some large sample references in some of the targets. Setting a limit here to avoid this.
=> webapp: limit size of sample references

src/fuzz_introspector/html_report.py, src/fuzz_introspector/utils.py
This PR adds a new function in the `utils.py` for copying Java source files to the output location to allow the webapp API to retrieve them. The newly added function is called at the end of the HTML report creation. Only those source files that match the methods will be copied.
=> Java: Copy java source code

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR fixes a bug in src_end handling. The src_end variable should only add 10 when it is less than or equal to the src begin, which indicates that the src_end is not provided correctly.
=> webapp: fix bug in src_end handling

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR adds new api for querying all the existing source file paths. This new API could help oss-fuzz-gen to understand what candidate is in scope of the project and filter out bad candidates for prompts and harnesses generation.
=> webapp: Add new api to query all source paths exist

src/fuzz_introspector/html_report.py
The logic handling JSON output for JVM constructors has some missing and wrong data. This PR fixes that to ensure correct information is stored in the output JSON file for JVM constructors.
=> Java: Fix data for JVM constructors

tools/web-fuzzing-introspection/app/webapp/routes.py
The PR fixes the logic for get_function_from_func_signature function to also consider possible jvm constructors.
=> webapp: Fix function to consider constructor signature

src/fuzz_introspector/html_report.py
This PR adds a missing property in the JSON report for Java constructors introduced in #1629.
=> Java: Fix bug in Json report Java JVM constructor

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
The new format is used by almost al projects now, so it's spamming unnecessarily at this point. Removing to make logs clearer
=> web: avoid excessive logging

tools/web-fuzzing-introspection/app/webapp/helper/function_helper.py
This PR adds additional filtering for the function list returned by the all-public-candidates api. The new filtering logic filters some method name that is possibly unrelated to the project.
=> webapp: Add filters for excluded function name

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py, tools/web-fuzzing-introspection/app/webapp/__init__.py, tools/web-fuzzing-introspection/app/webapp/helper/function_helper.py, tools/web-fuzzing-introspection/app/webapp/models.py
This PR follows #1648. It adds the new java method static properties to the oracle API's output.
=> webapp: Add static information to function model

tools/web-fuzzing-introspection/app/webapp/helper/function_helper.py, tools/web-fuzzing-introspection/app/webapp/routes.py
This PR unifies the return function dict list of all oracle to avoid missing some important keys for oss-fuzz-gen.
=> webapp: Unify the output of all oracle

tools/web-fuzzing-introspection/app/webapp/routes.py
In #1623, changes have been made for source code querying API to accommodate Java projects. The changes are only done in a single API but all other APIs required source code querying is not changed. This causes the logic can only accommodate Java projects in a single API. This PR moves the Java-specific logic for source code querying into the underlying source code querying function to accommodate all APIs for Java project source code querying.
=> webapp: Fix bug for handling jvm source file path

tools/web-fuzzing-introspection/app/webapp/routes.py
The `get_functions_of_interest` function is supposed to return a list of functions that are ordered by high cyclomatic complexity in descending order and runtime coverage in ascending order. This ordering ensures that the functions with high cyclomatic complexity and low coverage always come first in the list. It is found that the ordering is wrong by sorting both parameters in descending order. Although it does not affect the content of the resulting list, the order in the list is wrong and possibly affects OSS-Fuzz-gen's process if limitation is applied. This PR fixes that by making sure the runtime coverage is ordered in ascending order.
=> webapp: Fix ordering bug for far-reach-but-low-coverage oracle API

src/fuzz_introspector/code_coverage.py, src/fuzz_introspector/datatypes/fuzzer_profile.py, src/fuzz_introspector/utils.py, src/test/test_code_coverage.py
It is found that the code coverage report calculation for JVM does not reflect the real data correctly. After some analysis of the code, it is believed that the current coverage calculation and extraction from the jacoco.xml only consider items in terms of source files but not methods. This cause separate methods inherit a wrong coverage calculation. This PR proposes a revamp on the coverage calculation for JVM projects to consider cov_map on separate methods instead of the whole source files. This is necessary to retrieve correct coverage information for each methods and that information is needed for further post-processing and the candidate choosing process for oss-fuzz-gen.
=> Fix coverage calculation for JVM projects

src/fuzz_introspector/code_coverage.py
This PR fixes a bug in code coverage calculation for JVM project when source code file attribute is not found in the jacoco.xml file. This PR adds fail safe and checking to ensure the process continue even if the source code file attribute is missing.
=> Fix bug in coverage processing for invalid jacoco.xml

src/fuzz_introspector/html_report.py
This PR fixes a typo in the creation of the json file for java constructors. The bug makes the calldepth in the output constructor json becomes a list instead of integer.
=> Java: Fix bug for typo in constructor calldepth

frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionElement.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/JavaMethodInfo.java, src/fuzz_introspector/datatypes/function_profile.py, src/fuzz_introspector/html_report.py, tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py, tools/web-fuzzing-introspection/app/webapp/__init__.py, tools/web-fuzzing-introspection/app/webapp/helper/function_helper.py, tools/web-fuzzing-introspection/app/webapp/models.py
This PR adds a new "need_close" property to the functions for supporting the oss-fuzz-gen prompt generation of JVM projects. This could avoid false positive OOM happening on fuzzers generated by LLM.
=> JVM-webapp: Add close property

tools/web-fuzzing-introspection/app/webapp/helper/function_helper.py, tools/web-fuzzing-introspection/app/webapp/routes.py
This PR adds a new API endpoint for retrieving JVM-method-specific properties. It also removes the returning of these properties from the original API calls to reduce the size of the response for other APIs.
=> webapp: Add API for retrieving JVM properties of methods

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
To avoid exhausting memory on smaller machines
=> web: reduce number of parallel runs during db creation

tools/web-fuzzing-introspection/app/webapp/routes.py
this is to avoid OOMs and long processing time
=> webapp: simplify getting frontpage stats

tools/web-fuzzing-introspection/app/webapp/__init__.py, tools/web-fuzzing-introspection/app/webapp/data_storage.py, tools/web-fuzzing-introspection/app/webapp/routes.py
This is to avoid having both file stored on the filesystem as well as in dictionaries during production. The current file-system only approach is causing significant delays making introspector.oss-fuzz.com unresponsive
=> webapp: force caching of functions

src/fuzz_introspector/analysis.py
Identify tests based on their basename rather than the directory name. The goal is to find tests located in source folders with e.g. a relevant prefix or suffix.
=> analysis: extend test identification

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR fixes an issue with non-unified target file strings. For JVM projects, the target file string is a path of the source file within the package directory, which does not start with a '/'. This behaviour differs from other project languages like C/C++, where the path always starts with a '/'. This PR unifies the behaviour to allow the logic to handle both cases successfully.
=> webapp: Fix and unify source file path

tools/web-fuzzing-introspection/app/webapp/models.py
The frontend of FI failed to extract signatures for functions in a Python project. This results in N/A for the function signature field of all functions in the project, affecting the further processing of the web app and OFG. This PR fixes the issue by setting the function signature to the function name by default whenever the signature is missing.
=> webapp: Handles missing function signature

tools/web-fuzzing-introspection/app/webapp/helper/function_helper.py
It was found that some OFG logic for Python requires the project name where a function belongs to determine if the function should be included in a fuzzer. This PR adds the necessary information to the function dictionary, returning it for APIs that require function information.
=> webapp: Add project property to function details return

tools/web-fuzzing-introspection/app/static/assets/db/oss_fuzz.py, tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
Enables loading using the current logic in case some projects only succeeded with light introspector. The next step is to load in the light introspector data to the webapp as well.
=> webapp: local: enable loading in context of light introspector

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
Some problems may occur if some weird compiler optimisations changes source code locations. This is particularly seen when analysing kernel drivers.
=> frontend: llvm: narrow calltree node duplicate check

src/fuzz_introspector/cfg_load.py
This helps kernel driver analysis where we may not always have a calltree, since we don't have an entrypoint at first.
=> cfg_load: return empty list instead of throwing exception

tools/web-fuzzing-introspection/app/main.py, tools/web-fuzzing-introspection/app/webapp/routes.py, tools/web-fuzzing-introspection/requirements.txt
Introduces API documentation with flask smorest. This has been applied to a single API for now to introduce the concept. Follow-up PR will happen with all APIs.
=> webapp: enable automated API documentation

frontends/rust/rust_function_analyser/src/analyse.rs, frontends/rust/rust_function_analyser/src/call_tree.rs
This PR fixes the logic and adds more visit implementations to enable the Rust frontend to discover nested or chained function/method calls within the `fuzz_target` macro of the fuzzing harness.
=> [Rust] Fix function/method discovery from harness

frontends/rust/rust_function_analyser/src/analyse.rs, frontends/rust/rust_function_analyser/src/call_tree.rs
This PR fixes the calltree discovery logic to correctly interpret function calls initiated from fuzzing harness for rust frontend.
=> [Rust]: Fix calltree discovery logic

frontends/rust/rust_function_analyser/src/analyse.rs
This PR fixes the rust frontend function/method discovery logic by adding back some missing handling of certain expression type. including conditions in certain statement and block of codes.
The problem mentioned in #1826 where certain functions/methods in unsafe block are missing has been solved. Here is the new call tree in the generated data file for parse_response_multspaces with all the functions/methods call in the unsafe block being discovered.
```
Call tree
fuzz_target /src/httparse/fuzz/fuzz_targets/parse_request_multspaces.rs linenumber=-1
Request::new /src/httparse/fuzz/fuzz_targets/parse_request_multspaces.rs linenumber=7
httparse::ParserConfig::default /src/httparse/fuzz/fuzz_targets/parse_request_multspaces.rs linenumber=8 …
```
=> [Rust] Fix missing expression in function/method discovery process

frontends/rust/rust_function_analyser/src/analyse.rs
This PR fixes the branch file discovery to also analyse branching in other Expr in addition to the original ExprIf. Currently it supports ExprIf ExprLoop ExprMatch ExprForLoop ExprWhile.
=> [Rust] Add branch profile discovery for other branching Expr

oss_fuzz_integration/oss-fuzz-patches.diff
This PR fixes a wrong rustflag used for rust frontend build making all the debug span information missing. After the update the calltree generated in FI report contains correct linkage of functions and line number.
=> [Rust] Fix wrong rust flag for introspector

tools/web-fuzzing-introspection/app/webapp/routes.py
OSS-Fuzz and OSS-Fuzz-Gen use "JVM" instead of "Java" for all types of JVM projects. This PR updates the database-language-stats API to duplicate the "Java" result with the "JVM" tag, ensuring consistency with the language settings used by OSS-Fuzz and OSS-Fuzz-Gen.
The result in "Java" tag is kept for supporting future use.
=> [webapp] Match java result to jvm for OFG

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR fixes two bugs.
1) For the source path, it could be class name or java source file path. The transformation only needed when it is a java class name. This PR fixes it to only do the replacement when it is not a file path ends with .java.
2) When project_info retrieve an empty coverage_data (for failed coverage build), the direct map retrieval will result in error. This PR fixes that by adding an empty check before the use of the map data.
=> webapp: Fix bug for wrong java path and empty coverage report

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
For the local db building approach, it is found that the project language is all set to C++. This PR fixes that by geting the correct language for webapp processing.
=> webapp: Fix wrong language used for db building

oss_fuzz_integration/oss-fuzz-patches.diff
This PR fixes the inspector copying in the oss-fuzz-patches.diff to ensure the inspector directory path is not duplicated for rust projects.
=> [Rust] Fix diff for inspector directory copying

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR revise the exclusion of irrelevant tests and add in java specific logic to exclude source files that does not related to the project or without importing any public classes from the project.
=> webapp: Filter irrelevant tests

tools/web-fuzzing-introspection/app/webapp/routes.py
A bug has been identified in the `extract_lines_from_source_code` function. The `raw_source` is retrieved using either the `extract_introspector_raw_source_code` or `_light_extract_introspector_raw_source_code` function. A check is performed after the source code extraction to ensure that subsequent processing occurs only if the source code has been successfully extracted.
However, the check only verifies for a `NoneType` value and does not account for an empty string. This oversight constitutes a bug because, unlike `_light_extract_introspector_raw_source_code`, the `extract_introspector_raw_source_code` function returns an empty string rather than `None` when it fails to extract the source code.
As a result, an empty source code returned by `extract_introspector_raw_source_code` is …
=> webapp: Fix wrong empty raw_source checking

src/fuzz_introspector/frontends/src/frontend_c.py, src/fuzz_introspector/frontends/src/oss_fuzz.py
Force  the use of the fuzz introspector library as a package. This should be done forcing `python3 -m pip install .` in the fuzz introspector `src` dir.
=> core: frontend: force pkg inclusion

src/pyproject.toml
This PR removes unnecessary package which requires libgraphviz-dev.
=> FI: Remove unnecessary package

oss_fuzz_integration/oss-fuzz-patches.diff, src/fuzz_introspector/utils.py
For go coverage report, it only contains a single page and use an existing javascript to change and display the chosen source file coverage. 
This PR fixes the coverage report by adding additional java script logic to accept file tag from the url and automatically change to show the correct source file.
This PR also change the logic for FI to determine the correct file tag for a specific function call site in the call tree to allow displaying the correct source code coverage from the coverage report.
=> [Go] Fix link for coverage report

src/fuzz_introspector/frontends/frontend_jvm.py, src/fuzz_introspector/frontends/oss_fuzz.py
This PR refines logic for new jvm frontend to add in more properties.
=> [JVM] Fix new jvm frontend

src/fuzz_introspector/analysis.py, src/fuzz_introspector/data_loader.py, src/fuzz_introspector/datatypes/fuzzer_profile.py, src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/frontends/oss_fuzz.py
supersedes: https://github.com/ossf/fuzz-introspector/pull/1926
=> core: enable using FI against projects without harnesses

oss_fuzz_integration/oss-fuzz-patches.diff
This PR fixes a bug in the oss-fuzz patch for jvm-tree-sitter frontend that the entrypoint is missing from the command.
=> frontend-jvm: Fix bug on missing entrypoint in oss-fuzz patch

src/fuzz_introspector/datatypes/fuzzer_profile.py, src/fuzz_introspector/frontends/frontend_go.py, src/fuzz_introspector/frontends/frontend_jvm.py, src/fuzz_introspector/frontends/frontend_rust.py, src/fuzz_introspector/frontends/oss_fuzz.py
This PR fixes a bug for missing fuzzer name/path in the tree-sitter frontend for go/rust/jvm.
=> frontend: Fix bug on missing fuzzer name/path

src/fuzz_introspector/frontends/frontend_cpp.py, src/test/test_frontends_cpp.py
This PR fixes the frontend_cpp by handling explicit default constructor calls that are missing before.
=> [Frontend-CPP] Add handling of default constructor call

src/fuzz_introspector/frontends/frontend_c.py, src/fuzz_introspector/frontends/frontend_cpp.py, src/fuzz_introspector/frontends/oss_fuzz.py, src/test/data/source-code/cpp/test-project-5/test.cpp, src/test/data/source-code/cpp/test-project-5/test.hpp, src/test/test_frontends_c.py, src/test/test_frontends_cpp.py
This PR fixes the unit test for c/cpp frontend. It also fixes a bug in the get_reachable_functions which recursive calls is not handled correctly.
=> [CPP/C-frontend] Fix unit test

src/test/data/source-code/jvm/test-project-8/variable/B.java, src/test/data/source-code/jvm/test-project-8/variable/Fuzzer.java, src/test/data/source-code/jvm/test-project-8/variable/test/A.java, src/test/test_frontends_jvm.py
This PR adds another test for invocation from parameter instance, aiming to test the ability to determine variable object type from parameters and general import statements.
=> [Frontend-jvm] Add parameters invocation test

src/test/data/source-code/rust/test-project-4/fuzzer.rs, src/test/test_frontends_rust.py
This PR adds a new test project for frontend rust on unreachable functions and path splitting from match statements.
=> [Frontend-Rust] Add test for unreached functions and match path splitting

src/fuzz_introspector/frontends/frontend_jvm.py, src/test/data/source-code/jvm/test-project-9/multiple/FuzzerOne.java, src/test/data/source-code/jvm/test-project-9/multiple/FuzzerTwo.java, src/test/data/source-code/jvm/test-project-9/multiple/SimpleClass.java, src/test/test_frontends_jvm.py
This PR add a new unit testing for jvm frontend with multiple fuzzing entry points. This PR also fixes a bug on class name duplication on some methods.
=> [Frontend-JVM] Add unit test for multiple entry points

src/fuzz_introspector/frontends/frontend_go.py, src/test/data/source-code/go/test-project-1/fuzzer.go, src/test/test_frontends_go.py
This PR add unit test for go. It also add in some template unit test to avoid conflicts in later PRs.
=> [Frontend-go] Add unit test for golang

src/fuzz_introspector/frontends/frontend_go.py, src/test/data/source-code/go/test-project-3/fuzzer.go, src/test/test_frontends_go.py
This PR fixes the logic to allow detection of type for short variable declaration. This is necessary to allow tracing the correct function callsites. A unit testing contains 3 methods with the same name declared in different structs helps to test the correctness of type detection.
Additional detection of other object declaration approach will be added in later PR.
=> [Frontend-go] Add unit test for object type detect and fix logic

src/fuzz_introspector/frontends/frontend_go.py, src/test/data/source-code/go/test-project-3/fuzzer.go, src/test/data/source-code/go/test-project-4/fuzzer.go, src/test/test_frontends_go.py
This PR add in the final bit for type detection on index/slicing expression, together with a new unit test to test for that.
=> [Frontend-go] Add unit test 4 with fixes on index/slicing expression type detection

src/fuzz_introspector/frontends/frontend_c.py, src/fuzz_introspector/frontends/frontend_cpp.py, src/fuzz_introspector/frontends/frontend_go.py, src/fuzz_introspector/frontends/frontend_jvm.py, src/fuzz_introspector/frontends/frontend_rust.py, src/fuzz_introspector/frontends/oss_fuzz.py
This PR generalise the source code discovery logic to remove duplicated code from different languages.
=> [Frontend] Generalise source code discovery

src/fuzz_introspector/frontends/datatypes.py, src/fuzz_introspector/frontends/frontend_c.py, src/fuzz_introspector/frontends/frontend_cpp.py, src/fuzz_introspector/frontends/frontend_go.py, src/fuzz_introspector/frontends/frontend_jvm.py, src/fuzz_introspector/frontends/frontend_rust.py, src/fuzz_introspector/frontends/oss_fuzz.py, src/test/test_frontends_jvm.py
This PR create a generalise project class for all different language.
=> [Frontend] Generalise project class

src/fuzz_introspector/frontends/datatypes.py, src/fuzz_introspector/frontends/frontend_c.py, src/fuzz_introspector/frontends/frontend_cpp.py, src/fuzz_introspector/frontends/frontend_go.py, src/fuzz_introspector/frontends/frontend_jvm.py, src/fuzz_introspector/frontends/frontend_rust.py, src/fuzz_introspector/frontends/oss_fuzz.py
This PR generalise the SourceCodeFile classes and simplify some of the frontend logic.
=> [Frontend] Generalise SourceCodeFile class

src/fuzz_introspector/frontends/frontend_jvm.py
This PR fixes a bug in the generalisation of the Project class. The default fuzzer entry point is used and create confusion on calltree extraction because it does not contains the necessary class information. This PR fixes that by forcing it to retrieve the needed JavaMethod instance for entry methods.
=> [Frontend-jvm] Fix bug in incomplete entrypoint confusion

src/fuzz_introspector/frontends/frontend_jvm.py, src/fuzz_introspector/utils.py, tools/web-fuzzing-introspection/app/webapp/helper/function_helper.py
This PR fixes the function_source_file properties in FunctionProfile class for JVM project. The original frontend for JVM use the function source file to store the class name of the function. this is because we does not have ways to locate the original source file name and path from class files as each class file only contains a single class.  Multiple classes defined in the same source file are compiled as separate class files. Thus the original logic for JVM have specific handling for function source file properties since it contains different information comparing to other language. The new tree-sitter frontend for JVM can now correctly obtained the source file name and path for a function, thus this PR fixes the logic to make JVM use the properties to correctly store the source file …
=> [JVM] Fix jvm function source file

src/fuzz_introspector/analysis.py, src/fuzz_introspector/commands.py
This PR fixes a bug in the SourceCodeLineAnalyser which does not handles the case of exceptions thrown from missing fuzzing entrypoints.
=> Analyser: Fix unexpected exit from coverage extraction

src/fuzz_introspector/analyses/__init__.py, src/fuzz_introspector/analyses/far_reach_low_coverage_analyser.py, src/fuzz_introspector/analysis.py, src/fuzz_introspector/cli.py, src/fuzz_introspector/commands.py
This PR adds a new analyser far reach low coverage which is ported from the webapp tool.
=> Analyser: Add far reach low coverage analyser

src/fuzz_introspector/frontends/datatypes.py
This PR disable the unused variable and unncessary pass checking in the frontend datatypes which contains only general class for language frontend. This PR also fixes other pylint error in the code.
=> pyline: Fix pylint error for frontend datatypes

src/fuzz_introspector/frontends/frontend_cpp.py
For py-tree-sitter.Node class, the text attribute is defined as `Optional[bytes]` thus it is necessary to check if it is None before calling `decode()` on it to avoid possible runtime exception and mypy errors. This PR fixes this typing problem in newly introduced code from #2011.
=> mypy: fix typing error for tree-sitter.Node.text

src/fuzz_introspector/analyses/__init__.py, src/fuzz_introspector/analyses/public_candidate_analyser.py, src/fuzz_introspector/cli.py, src/fuzz_introspector/commands.py
This PR adds a new standalone analyser porting from webapp's all-public-candidates API.
=> Analyser: Add new standalone analyser for all-public-candidates

src/fuzz_introspector/frontends/frontend_cpp.py, src/fuzz_introspector/frontends/frontend_rust.py
This PR unifies the src_line string formatting and fix a bug in wrong interpretation of detailed callsites source for frontend rust.
=> Fix bug in wrong detailed callsites

src/fuzz_introspector/analyses/far_reach_low_coverage_analyser.py, src/fuzz_introspector/cli.py, src/fuzz_introspector/commands.py
This PR adds the handling of the interesting function checking from far-reach-low-cov-fuzz-keyword into the FarReachLowCoverage analyser because they have similar logic.
=> Analyser: Add handling of far-reach-low-coverage-with-fuzz-keyword

src/fuzz_introspector/cfg_load.py, src/fuzz_introspector/diff_report.py
This PR fixes pylint error for cfg_load and diff_report module.
=> pylint: Fix pylint error for cfg_load and diff_report

oss_fuzz_integration/oss-fuzz-patches.diff
We can now run both light and regular introspector. Light will only be used if main introspector fails.
=> oss-fuzz: fix patches

src/fuzz_introspector/frontends/frontend_jvm.py, src/fuzz_introspector/frontends/frontend_rust.py
This PR fixes a bug in frontend_jvm and frontend_rust where an additional unused argument is required for the analyse_source_file function which has been removed from other frontend.
=> frontend: Fix bug on wrong additional argument

src/fuzz_introspector/frontends/frontend_jvm.py
This PR fixes a bug in frontend_jvm where a node type checking contains a typo and cause the checking skipped unexpectedly.
=> frontend: Fix typo bug in node type checking

.github/workflows/mypy.yml, src/fuzz_introspector/frontends/frontend_cpp.py
After changing FI to module based operation, the mypy CI fails to check on the module because the module is not installed. This PR fixes the mypy CI to install the FI modules before the checking to ensure the mypy CI picks up typing errors in the FI modules, including the tree-sitter frontend. This PR also fixes the mypy errors in frontend_cpp to pass the mypy check.
=> mypy: Fix mypy CI

src/fuzz_introspector/analyses/far_reach_low_coverage_analyser.py, src/fuzz_introspector/cli.py, src/fuzz_introspector/commands.py
This PR port the easy-params-far-reach api from webapp to analyser.
=> Analyser: Additional parameter for easy-params-far-reach api porting

src/fuzz_introspector/frontends/datatypes.py, src/fuzz_introspector/frontends/frontend_cpp.py, src/fuzz_introspector/frontends/frontend_jvm.py, src/fuzz_introspector/frontends/frontend_rust.py
The all_functions properties in project for different language  is needed for OFG process for all languages. This PR makes the property global for all language frontend project.
=> frontend: Add global all_functions properties for frontend project

src/fuzz_introspector/datatypes/fuzzer_profile.py
For the new FI, it supports analysis on non-fuzzing project. This PR fixes a bug in the handling of fuzzing profile where an unexpected KeyError throws when fuzzing method is not specified.
=> JVM/Go: Fix key error for project without fuzzing method

src/fuzz_introspector/frontends/frontend_jvm.py
This PR adds back the sig property in JVM frontend JavaMethod class. It also adds a new helper function function_source_code_as_text for OFG from scratch process.
=> frontend/jvm: Add sig property and helper function for frontend jvm

src/fuzz_introspector/frontends/datatypes.py, src/fuzz_introspector/frontends/frontend_cpp.py
Cross reference retrieval logic originally from frontend_cpp is required by all languages in OFG from scratch approach. This PR makes that function globally available for all language frontends.
=> frontend: Make get_cross_references globally for all language frontend

src/fuzz_introspector/frontends/oss_fuzz.py
When generalising the excluded directories into oss-fuzz, there is a missed consideration that fuzzing harnesses of Rust projects are normally located within the fuzz_target directory which are accidentally excluded by the generalised setting. This PR fixes that.
=> Frontend: Fix bug on exclude directories

src/fuzz_introspector/frontends/frontend_go.py, src/fuzz_introspector/frontends/frontend_rust.py
Add missing helper function function_source_code_as_text to frontend_go and frontend_rust.
=> frontend: Add missing helper function for go and rust

oss_fuzz_integration/oss-fuzz-patches.diff
In the latest FI operation, the main function in frontend/oss-fuzz has been removed and it required the CLI to activate the frontend. But the oss-fuzz patch does not reflect that correctly thus the patched compile script failed to execute the frontend for JVM/Rust correctly. This PR fixes the patch to allow a full run (instead of sole report running) for Rust and JVM projects.
=> Fix oss-fuzz patch

src/fuzz_introspector/utils.py
This PR fixes a bugs for jvm source code copying. When the full execution is done without the need of source file copying, the source copying logic will copied 0 files and the dumping of index.json will be failed since the path is unaccessible. This PR fixes that by only activating the dumping of index.json if file coping are done.
=> JVM: Fix bug when no source file is copied

src/fuzz_introspector/frontends/datatypes.py, src/fuzz_introspector/frontends/frontend_c.py, src/fuzz_introspector/frontends/frontend_cpp.py, src/fuzz_introspector/frontends/frontend_go.py, src/fuzz_introspector/frontends/frontend_jvm.py, src/fuzz_introspector/frontends/frontend_rust.py
This PR fixes the frontend for other language, following the C++ approach to allow retrieving in-memory report yaml directly without the need to dump it to intermediate location if the full process is executed. It only generalises those functions to allow better reuse and refactoring later.
=> frontend: Allow returning frontend yaml directly

doc/sphinx/source/installation-instructions/installation.rst, src/fuzz_introspector/analysis.py
The Sphinx documentation is not up to date. We no longer use LLVM 15.x but rather LLVM 18.x
Furthermore, it's easier to just use the provided helper script.
Ref: https://github.com/ossf/fuzz-introspector/issues/1841
=> sphinx-doc: update documentation

src/fuzz_introspector/frontends/datatypes.py, src/fuzz_introspector/frontends/frontend_c.py
This is causing issues in particular in C frontend because we avoid dumping data that is related to harness files. We need this data for the post processing to work.
We should refactor things though, so we don't have so much duplicate data.
=> core: frontends: always generate report

oss_fuzz_integration/oss-fuzz-patches.diff
This PR fixes the oss-fuzz-patch for golang which fixes a bug of missed inspector directory copy.
=> oss-fuzz-integration: Fix oss-fuzz patch

src/fuzz_introspector/frontends/frontend_go.py
This PR fixes the function_name property for golang in the frontend to unify with other languages.
=> frontend: Unify function name property for golang

oss_fuzz_integration/oss-fuzz-patches.diff
This PR fixes the patch for copying fuzz.cov of golang projects to unify with coverage report handling in OFG.
=> oss-fuzz: Fix patch for golang

doc/sphinx/source/installation-instructions/installation.rst
This PR fix is to address the issue #1841. @DavidKorczynski has updated the installation section of Sphinx documentation. However, the shell does not remain in the `work` directory after executing the script `build_all.sh`. Hence, I have added the command `cd work` to ensure the subsequent processes can be executed correctly. This approach maintains consistency with the command style in Option 2.
=> Fix: Missing command in the installation section of sphinx-doc

src/fuzz_introspector/cli.py
This PR fixes a bug in wrong default coverage url for end-to-end run in the cli.
=> cli: Fix default coverage url for end-to-end run

src/fuzz_introspector/analyses/annotated_cfg.py, src/fuzz_introspector/analyses/far_reach_low_coverage_analyser.py, src/fuzz_introspector/analyses/source_code_line_analyser.py
This PR fixes pylint problem for some analysis.
=> pylint: Fix pylint for analyses

src/fuzz_introspector/analyses/bug_digestor.py, src/fuzz_introspector/analyses/engine_input.py, src/fuzz_introspector/analyses/optimal_targets.py, src/fuzz_introspector/analyses/public_candidate_analyser.py
This PR fixes mroe pylint errors.
=> Fix pylint

README.md, api_test.sh, ci_checks.sh, code_checks.sh
This adds/updates CI scripts for linting and api tests.
I worry that having separate scripts will cause a mismatch with the github actions in the future. I think a cleaner solution would be to call the scripts instead. For example call `./code_checks.sh` instead of the actions/commands starting at this point (after setting up the environment completely): https://github.com/ossf/fuzz-introspector/blob/main/.github/workflows/main.yml#L16
=> Add CI scripts and update readme.

tools/web-fuzzing-introspection/app/static/assets/db/oss_fuzz.py, tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py, tools/web-fuzzing-introspection/app/webapp/__init__.py, tools/web-fuzzing-introspection/app/webapp/models.py, tools/web-fuzzing-introspection/app/webapp/routes.py, tools/web-fuzzing-introspection/app/webapp/templates/project-profile.html
Adds per fuzzer summary.json (based on `https://storage.googleapis.com/oss-fuzz-coverage/{0}/reports-by-target/{1}/{2}/linux/summary.json`) to the project timestamp data and generates per fuzzer coverage plots for the project overview, example below.
This PR is mainly to understand if an approach like this would be acceptable, though to implement some metrics in https://github.com/ossf/fuzz-introspector/issues/2054 it is probably needed to have a separate stage that takes a look at project data over time and not only in report generation. 
Still this PR [addresses an issue](https://github.com/ossf/fuzz-introspector/issues/1338) but it might take too much screen space (especially for large numbers of fuzzers), it might also require too much storage space, data ingress and runtime for data …
=> per fuzzer coverage information in project overview

src/fuzz_introspector/analyses/metadata.py
The 'fuzzerLogFile-<idx>-<id>.data' (.yaml) files can have a random id, add their names to make it easy to find them from the summary.json. Do the same for covreport which can have multiple files per fuzzer.
This change will make it much easier to implement analyses based on fuzzerLogFiles for the webapp.
=> Include metadata file names in summary.json.

src/fuzz_introspector/html_report.py
This PR fixes a bug on wrong file paths used to process source file copying for JVM projects. This issue causes some of the source files in JVM projects failed to copy to the needed location for further process, including webapps and OFG.
=> JVM: Fix source file name bug

src/fuzz_introspector/analysis.py
This PR fixes the logic below in test file extraction to fix bug and to enhance performance.
1) Merged directory and file discovery into a single loop for improved performance.
2) Avoided adding the root directory by skipping empty path components during directory splitting. (i.e. directory start with `/` will always return an empty string at the beginning of the splited list and cause root directory `/` been added wrongly to the `all_directories` variable)
3) Enhanced performance by skipping hidden directories (those starting with a dot).
4) Ensured only directories within the specified base directory are included.
5) Introduced a flag to enable or disable the copying of test files.
=> test_extraction: Fix bug and combine loop

src/fuzz_introspector/analyses/__init__.py, src/fuzz_introspector/analyses/test_file_analyser.py, src/fuzz_introspector/cli.py, src/fuzz_introspector/commands.py
This PR adds a new TestFileAnalyser to discover possible test and example files for the project in a standalone analysis run. The analyser will be extended to get cross reference and function matching in later PRs.
=> test_file_analyser: Initialise standalone test file analyser

src/fuzz_introspector/analyses/test_file_analyser.py
This PR fixes the logic of the test file analyser for non-standalone runs. Since some projects do not include the complete source code within the Introspector project as a result of test files are being ignored during the general report run. This PR introduces an additional round of frontend runs to ensure the required test files are present before proceeding with the analysis. It also improves the source path discovery logic when paths are not explicitly provided, by identifying the common path among existing source files and including the mandatory `/src` path if it exists. These changes enhance compatibility with both OSS-Fuzz report runs and standalone analysis runs.
=> analyser: Fix logic of test file analyser for non standalone run

src/fuzz_introspector/analyses/test_file_analyser.py
This PR fixes the TestFileAnalyser to ensure consistent directory scanning and prevent related errors. It also addresses an issue where some source code was not copied during the LLVM compilation process, resulting in missing test files in the output.
=> analyser: Fix directory inconsistency

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR fixes a bug where the second argument functions is incorrectly parsed and cause it always fall back to getting all test sources cross refernce.
=> webapp: Fix argument bugs

src/fuzz_introspector/frontends/datatypes.py, src/fuzz_introspector/frontends/frontend_c.py, src/fuzz_introspector/frontends/oss_fuzz.py
This PR adds the extraction of 5 custom type definition (Preproc definition, structs, typedef, union and enum) for c project in the tree-sitter frontend.
=> frontend-c: Add custom type extraction

src/fuzz_introspector/frontends/frontend_c.py
This PR fixes the tree-sitter frontend logic to include all type definition extracted from the source code for C projects.
=> frontend-c: Fix typedef output type for c project

src/fuzz_introspector/analyses/test_file_analyser.py
When following the example of "using fuzz-introspector w/o oss-fuzz", at the final step
```sh
python3 ../../../src/main.py report --target-dir=. --correlation-file=./exe_to_fuzz_introspector_logs.yaml
```
I got the following error:
```sh
debug info file: %s /home/cc/fuzz-introspector/tests/simple-example-0/work/../work/fuzzerLogFile-0-xvPezDK7xM.data.debug_info
debug info file: %s /home/cc/fuzz-introspector/tests/simple-example-0/work/../work/fuzzerLogFile-0-xvPezDK7xM.data.debug_all_types
debug info file: %s /home/cc/fuzz-introspector/tests/simple-example-0/work/../work/fuzzerLogFile-0-xvPezDK7xM.data.debug_all_functions
Traceback (most recent call last):
File "/home/cc/fuzz-introspector/tests/simple-example-0/work/../../../src/main.py", line 25, in <module>
main()
File …
```
=> fix(analyser): update path handling in `TestFileAnalyser`

src/fuzz_introspector/datatypes/function_profile.py
This PR adds handling of the newly extracted assert statements in the FI backend function profiles. Currently only works for C projects, all other projects will result in empty list.
=> FI-datatype: Add handling of assert statements in FI

src/fuzz_introspector/analyses/test_file_analyser.py
This PR fixes a bug in test_file_analyser where the wrong base folder is used during the second run of the Tree-sitter frontend for discovering test files, causing empty fuzzing profiles during the analysis stage of a general project run.
=> analyser: Fix bug in base directory setting

src/fuzz_introspector/frontends/frontend_c_cpp.py
This PR adds cache to get_function_node in C/Cpp frontend and replace recursion in callsites extraction process with the TreeSitter cursor to increase processing speed.
=> frontend-c-cpp: Fix slow recursion and add function node cache

src/fuzz_introspector/analyses/__init__.py, src/fuzz_introspector/analyses/frontend_analyser.py, src/fuzz_introspector/cli.py, src/fuzz_introspector/commands.py, tools/web-fuzzing-introspection/app/static/assets/db/oss_fuzz.py
This PR renames test-file-analyser to frontend-analyser. The analyser performs a second run of the frontend to generate the necessary data from frontend extraction if any data were skipped due to the LTO approach. The output from the second run is stored in a separate subdirectory. This PR also updates the web app to search the subdirectory for the required JSON data, but only if it does not already exist in the base directory.
=> frontend-analyser: Fix frontend lto process

tools/web-fuzzing-introspection/requirements.txt
Fix pip install error
```log
python3 -m pip install -r ./tools/web-fuzzing-introspection/requirements.txt
Collecting click==8.1.3 (from -r ./tools/web-fuzzing-introspection/requirements.txt (line 1))
Using cached click-8.1.3-py3-none-any.whl.metadata (3.2 kB)
Collecting Flask==3.0.2 (from -r ./tools/web-fuzzing-introspection/requirements.txt (line 2))
Using cached flask-3.0.2-py3-none-any.whl.metadata (3.6 kB)
Collecting itsdangerous==2.1.2 (from -r ./tools/web-fuzzing-introspection/requirements.txt (line 3))
Using cached itsdangerous-2.1.2-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: Jinja2==3.1.6 in ./scripts/oss-fuzz-gen-e2e/workdir/.venv/lib/python3.12/site-packages (from -r ./tools/web-fuzzing-introspection/requirements.txt (line 4)) (3.1.6)
Collecting …
```
=> support python 3.12

src/fuzz_introspector/frontends/frontend_c_cpp.py, src/fuzz_introspector/frontends/frontend_go.py, src/fuzz_introspector/frontends/frontend_jvm.py, src/fuzz_introspector/frontends/frontend_rust.py, src/test/data/source-code/c/unicode-error/simple.c, src/test/data/source-code/cpp/unicode-error/simple.cpp, src/test/data/source-code/go/unicode-error/simple.go, src/test/data/source-code/jvm/unicode-error/simple.java, src/test/data/source-code/rust/unicode-error/simple.rs, src/test/test_frontends_unicode.py
This PR adds fail safe configuration for the tree-sitter node text decoding and **ignore error character** that could cause UnicodeDecodeError. A new unit testing has been added to check for unexpected UnicodeDecodeError.
=> frontend: Add fail safe configuration for tree-sitter node text decode

src/fuzz_introspector/frontends/frontend_c_cpp.py
Currently, type aliases in the C/C++ frontend are being incorrectly ignored. As a result, some `typedef` declarations for structs or unions that are redefined under a different alias are missing from the final output. This PR corrects the typedef extraction logic in the C/C++ frontend to ensure that such type aliases are included.
For example, in the following case, the struct `abc` is correctly extracted, but the alias `ddd` for `struct abc` is missing from the result:
```c
struct abc {
int aaa;
};
typedef struct abc ddd;
```
=> frontend: Fix type alias extraction

tools/web-fuzzing-introspection/app/webapp/routes.py
This is a fix to the tests cross reference extration using function name to avoid partial match of function name which returns wrong information. The provided function name is handled, demangled to ensure the exact match of function name.
=> webapp: Fix function name matching for tests xref

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR fixes a API return mismatch for `full-type-definition` api.
=> webapp: Fix api mismatch

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR updates `project-tests-for-functions` API to support an additional details query parameter, which returns detailed test cross-reference information, in addition to the original default behaviour of returning only a list of test cross-reference files.
=> webapp: Fix tests xref API to support xref details query
