oss_fuzz_integration/build_patched_oss_fuzz.sh, oss_fuzz_integration/oss-fuzz-patches.diff
This is needed to include fixes from Nov 15 (example: https://github.com/google/oss-fuzz/commit/e23200e1e4bdd9247d3ef5797e9ff9c472054894)
=> Bump to more recent OSS-Fuzz

oss_fuzz_integration/build_patched_oss_fuzz.sh, oss_fuzz_integration/oss-fuzz-patches.diff
On the cloud build the covreport is generated by OSS-Fuzz, so I added a customized line to copy it to introspector's dir. This fixes the coloring issue on the portal.
=> Upstream changes in compile script

post-processing/fuzz_html.py
I noticed reports after Feb 14th were missing analyses section. This fixes it.
=> Fix missing html body for analyses section

post-processing/fuzz_html.py, post-processing/styling/styles.css
Adds boxes for https://github.com/ossf/fuzz-introspector/issues/46
=> Addd high-level description boxes

post-processing/styling/styles.css
Fixes https://github.com/ossf/fuzz-introspector/issues/47
=> make table of contents scrollable

post-processing/fuzz_html.py, post-processing/styling/styles.css
Fixes https://github.com/ossf/fuzz-introspector/issues/61
=> Don't overflow code blocks in tables

post-processing/fuzz_html.py, post-processing/styling/calltree.js, post-processing/styling/styles.css
Makes each node in the calltree expandable and collapsible.
This PR adds a the BeautifulSoup dependency to prettify the html of the calltree.
=> Make calltree expandable

post-processing/fuzz_html.py, post-processing/styling/styles.css
Improves the UI of the report page by:
- wrapping each main section in boxes
- adding graphs in the top to display stats instead of in plain text format.
=> Report UI improvements

post-processing/fuzz_html.py, post-processing/styling/custom.js, post-processing/styling/styles.css
PoC. It still needs a bit of work.
=> Show in menu where you are in the report

post-processing/styling/styles.css
Should fix https://github.com/ossf/fuzz-introspector/issues/102
=> Fix calltree coverage colors

post-processing/fuzz_html.py, post-processing/styling/styles.css
The sidebar is not being used, so this PR removes it.
=> Remove sidebar in calltree

llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
Ref: https://github.com/ossf/fuzz-introspector/issues/107
=> llvm: limit functions included in analysis

post-processing/styling/calltree.js, post-processing/styling/styles.css
The final PR to close https://github.com/ossf/fuzz-introspector/issues/73
=> Add symbol to show that calltree node can be expanded

llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
=> llvm: add configuration file

oss_fuzz_integration/oss-fuzz-patches.diff
=> oss-fuzz: use default fuzz-introspector config

llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
=> llvm: enable default config unless env var is set

post-processing/styling/calltree.js
Fixes https://github.com/ossf/fuzz-introspector/issues/109
=> Add link from caltree to report

post-processing/fuzz_html.py, post-processing/styling/calltree.js, post-processing/styling/styles.css
Fixes https://github.com/ossf/fuzz-introspector/issues/110
=> Add lines in calltree to show fuzz blockers

llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
=> llvm: subsitute old function avoidance with new logic

oss_fuzz_integration/oss-fuzz-patches.diff
Ref: https://github.com/ossf/fuzz-introspector/issues/131
CC @Navidem
=> oss-fuzz: force no inlining

oss_fuzz_integration/build_patched_oss_fuzz.sh, oss_fuzz_integration/oss-fuzz-patches.diff
Ref: https://github.com/ossf/fuzz-introspector/issues/67
=> oss-fuzz: unify patching with upstream oss-fuzz

post-processing/styling/calltree.js
Fixes https://github.com/ossf/fuzz-introspector/issues/150
=> Fix back button url

post-processing/styling/calltree.js
Closes https://github.com/ossf/fuzz-introspector/issues/129
=> Add feature to collapse by function name

doc/Glossary.md
Ref: https://github.com/ossf/fuzz-introspector/issues/113
=> doc: add glossary start

post-processing/fuzz_html.py
Ref:
https://github.com/ossf/fuzz-introspector/issues/60#issuecomment-1077032191
=> html: reduce columns in function table

post-processing/fuzz_html.py
Ref: https://github.com/ossf/fuzz-introspector/pull/161
=> post-process: correct links in fuzz blocker table

post-processing/fuzz_html.py
Noticed that there are a bunch of un-used args being passed around in fuzz_html.py. Removed most of them. The code works after these on my local instance. @DavidKorczynski please take a look too.
=> Doing a clean-up in fuzz_html.py

post-processing/fuzz_html.py
Ref: https://github.com/ossf/fuzz-introspector/issues/167
=> post-process: remove synthetic fuzzers by default

llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
In addition to the exclusion by source file:
Ref: https://github.com/ossf/fuzz-introspector/issues/177
=> llvm: enable exclusion by source file and use regex

doc/Config.md
Ref: https://github.com/ossf/fuzz-introspector/issues/113
=> doc: add config description

post-processing/fuzz_html.py
Ref: https://github.com/ossf/fuzz-introspector/issues/128
=> calltree: add fuzz blockers to tree page

oss_fuzz_integration/get_full_coverage.py, oss_fuzz_integration/run_both.sh
This is dependent on https://github.com/google/oss-fuzz/pull/7505 in
order to be working.
=> oss-fuzz: update helper scripts

post-processing/analyses/fuzz_engine_input.py, post-processing/analyses/fuzz_optimal_coverage_analysis.py, post-processing/analyses/fuzz_optimal_targets.py, post-processing/fuzz_analysis.py, post-processing/fuzz_html.py
This is to move towards a plugin-style architecture where each analysis
is a plugin and the core is an api-style to make rapid analysis
feasible.
=> post-process: refactor to enable analyses to be independent

post-processing/analyses/fuzz_runtime_coverage_analysis.py, post-processing/fuzz_analysis.py, post-processing/fuzz_cov_load.py, post-processing/fuzz_html.py
Ref: https://github.com/ossf/fuzz-introspector/issues/218
=> post-process: refine coverage hit logic

post-processing/fuzz_html.py
Makes the argument types collapsible as well and refactors the code
appropriately.
=> post-process: fix collapsible elements in function

post-processing/analyses/fuzz_calltree_analysis.py, post-processing/fuzz_html.py
Ref: https://github.com/ossf/fuzz-introspector/issues/229
=> post-process: refactor calltree out of html

post-processing/fuzz_analysis.py, post-processing/fuzz_cov_load.py, post-processing/fuzz_data_loader.py
An issue occurred where the number of reachable functions that was also covered functions would be 100% even though not all reachable functions were covered. This fixes it as well as simplifies some of the logic surrounding this code.
=> post-process: fix coverage issues

post-processing/analyses/fuzz_calltree_analysis.py, post-processing/styling/calltree.js, post-processing/styling/styles.css
As mentioned in https://github.com/ossf/fuzz-introspector/pull/240#issuecomment-1111412391
=> calltree: Move indeces to the left

post-processing/styling/calltree.js
Fixes https://github.com/ossf/fuzz-introspector/issues/232
=> calltree: fix scrolling issue

post-processing/analyses/fuzz_engine_input.py
Ref:
https://github.com/ossf/fuzz-introspector/pull/252#issuecomment-1122651603
=> fuzz-engine-input: demangle func names

post-processing/analyses/fuzz_runtime_coverage_analysis.py
Add a new column that shows which fuzzers reach each of the functions with high complexity but low runtime coverage.
Also refactors some of the code and adds static types.
=> analyses: extend and refactor runtime coverage

post-processing/analyses/fuzz_engine_input.py
Bug fix when there are no fuzz blockers, which results in an erroneous string concatenation
=> post-process: bug fix

post-processing/analyses/fuzz_bug_digestor.py, post-processing/analyses/fuzz_calltree_analysis.py, post-processing/analyses/fuzz_engine_input.py, post-processing/analyses/fuzz_optimal_targets.py, post-processing/analyses/fuzz_runtime_coverage_analysis.py, post-processing/fuzz_analysis.py, post-processing/fuzz_cfg_load.py, post-processing/fuzz_cov_load.py, post-processing/fuzz_data_loader.py, post-processing/fuzz_html.py, post-processing/fuzz_html_helpers.py, post-processing/fuzz_utils.py
The goal is to enable better prediction of bugs and make the code more
readable.
Ref: https://github.com/ossf/fuzz-introspector/issues/262
=> post-process: add static typing to lot of codebase

post-processing/analyses/fuzz_calltree_analysis.py, post-processing/analyses/fuzz_engine_input.py
main point is to statically type `get_fuzz_blockers` but the PR includes some styling too.
=> calltree analysis: statically type

oss_fuzz_integration/project-checker.py, oss_fuzz_integration/test_projects.sh
Ref: https://github.com/ossf/fuzz-introspector/issues/41
=> test: oss-fuzz: add leveldb specs

post-processing/fuzz_analysis.py, post-processing/fuzz_data_loader.py
This PR addresses leftover comments from #269
=> Store branch blockers in summary file

post-processing/styling/styles.css
Switches the purple icons for arrows in the calltree.
=> calltree: use arrows to show collapsed lines

post-processing/fuzz_html.py
Fixes: https://github.com/ossf/fuzz-introspector/issues/283
=> post-process: refine calltree overview image

post-processing/fuzz_analysis.py
Temporarily fixes https://github.com/ossf/fuzz-introspector/issues/285
but this should not be considered a permanent fix.
=> post-process: tmp bug fix

post-processing/fuzz_analysis.py
Ref: https://github.com/ossf/fuzz-introspector/issues/288
=> post-processing: catch invalid dictionary accesses

post-processing/fuzz_html.py
Fixes: https://github.com/ossf/fuzz-introspector/issues/274
=> post-process: substite filepath to fuzzer key for bitmap

oss_fuzz_integration/test_projects.sh
To prevent regression of:
https://github.com/ossf/fuzz-introspector/issues/288
Ref: https://github.com/ossf/fuzz-introspector/issues/41
=> test: add wuffs to oss-fuzz testing

frontends/python/main.py
This matches `main.py` to the changes in https://github.com/AdaLogics/PyCG/commit/0aefe877ce0c7995ad29ab1e104007900eaee544
=> frontends: python: update to new cg extraction data

frontends/python/main.py
Outputs the data from the static module into data format that is
accepted by the post-processing backend of fuzz-introspector.
I have verified locally this works, i.e. the HTML reports can be
generated, using a slightly modified version of post-processing. The
diffs needed here will be pushed next (after cleanup).
=> frontends: python: enable fuzz-introspector compliant output

frontends/python/main.py
This will fill out the functions-reached and reached-by-functions in
data used by the post-processing. This will start to get the analysis
properly going, e.g. statistics etc.
=> frontends: python: add reachables extraction logic

oss_fuzz_integration/get_full_coverage.py
This makes it a bit easier to modify the code for others
=> oss-fuzz-integration: refactor get_full_coverage

post-processing/analyses/fuzz_optimal_targets.py
Fixes: https://github.com/ossf/fuzz-introspector/issues/307
=> post-process: fix coverage link

frontends/python/main.py, tests/python/run_tests.sh
This makes it easier to include more files in the AST generation.
=> frontend: python: enable scanning of additional libraries

post-processing/fuzz_analysis.py
Fixes the issue mentioned at https://github.com/ossf/fuzz-introspector/issues/312#issuecomment-1151473456
The code was incorrectly using reachability instead of coverage hit.
=> Identify hit functions via coverage

requirements.txt
Ref: https://github.com/ossf/fuzz-introspector/pull/318
=> requirements.txt: add psutil

frontends/python/main.py
This is maturing and code quality should follow.
=> frontends: python: refactor handler script

oss_fuzz_integration/README.md, oss_fuzz_integration/get_full_coverage.py, oss_fuzz_integration/run_both.sh
Ref: https://github.com/ossf/fuzz-introspector/issues/302
=> oss-fuzz: make multiple jobs optional

post-processing/fuzz_html.py, post-processing/main.py
Ref: https://github.com/ossf/fuzz-introspector/issues/317
=> post-process: add project title to report

post-processing/fuzz_analysis.py, post-processing/fuzz_data_loader.py
Here we differentiate between not covered complexity vs reachable complexity:
If a branch side takes us to not-yet-covered complex function, then it is very interesting
If a branch side does not explore not-yet-covered complex function, but can reach complex functions, then this is still better than a branch side taking us to no complex function. In other words, going to an already-covered complex function has potential to explore new states as we are going there from a new angle.
=> Differentiate between not covered vs reachable complexity

post-processing/main.py
This is done by way of a dedicated environment variable FUZZ_LOGLEVEL
=> post-process: enable setting log level

post-processing/analyses/fuzz_runtime_coverage_analysis.py, post-processing/fuzz_analysis.py
Refactoring the code and also removes an old function from
fuzz_analysis.py
=> analysis: refactor runtime coverage analysis

post-processing/analyses/fuzz_filepath_analyser.py, post-processing/fuzz_analysis.py, post-processing/main.py
Ref: https://github.com/ossf/fuzz-introspector/issues/263
=> post-process: add filepath analysis

post-processing/analyses/fuzz_calltree_analysis.py, post-processing/analyses/fuzz_optimal_targets.py, post-processing/analyses/fuzz_runtime_coverage_analysis.py, post-processing/fuzz_html.py
I asked our technical writer to take a pass on the portal.
=> Fix typos and clarify sentences

post-processing/fuzz_html.py, post-processing/fuzz_html_helpers.py, post-processing/styling/styles.css
1. Overall minor change of colors here and there.
2. Change styling of tables
3. Add button in left side with link to coverage
Preview:
=> Report page: Improve UI

post-processing/fuzz_analysis.py
=> Use file path instead of file name in branch blocker class

src/fuzz_introspector/datatypes/fuzzer_profile.py, src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/utils.py
=> src: refactoring

src/fuzz_introspector/datatypes/project_profile.py
- Fix comment
- Prefix internals functions
- Put internal functions at end of file
=> project_profile: refactor

src/test/fuzz/.gitignore, src/test/fuzz/fuzz_report_generation.py
This fuzzer should exercise the vast majority of the code.
=> test: fuzz: add fuzzer that hits report command

src/fuzz_introspector/cfg_load.py, src/fuzz_introspector/data_loader.py, src/fuzz_introspector/datatypes/fuzzer_profile.py, src/fuzz_introspector/utils.py
Fixes issues caught by fuzz_report_generation.
=> Add error checking

src/fuzz_introspector/styling/calltree.js
This PR gets rid of the loop in `getCollapsibleFunctions()` through all calltree nodes. 
It is solved by merging the loop with another one that also loops through all calltree nodes.
=> Calltree UI: Remove loop through all nodes

src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/styling/calltree.js
=> Calltree: make expand/collapse faster

.github/workflows/testing.yml
Adds unit testing in the CI.
Ref: https://github.com/ossf/fuzz-introspector/issues/41
=> CI: add unit testing

oss_fuzz_integration/project_checker.py, oss_fuzz_integration/test_projects.py
Adds test for checking the URLs in the portal, as requested in #362
=> Add test for URL sanity

src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/styling/calltree.js, src/fuzz_introspector/styling/styles.css
Positions the image with CSS to make it more stable.
=> Improve positioning of calltree overview image

README.md, doc/ExampleOutput.md, doc/Features.md, doc/LocalBuild.md
Simplify and modularise the Github documentation. See https://github.com/DavidKorczynski/fuzz-introspector-2/tree/doc-update-3 for reference
=> Doc: update readme structure

src/fuzz_introspector/analysis.py
This is an alternative to #409 addressing #356
=> Use merged profile to access all_function and use total_complexity

doc/LanguageImplementation.md
Fixes: https://github.com/ossf/fuzz-introspector/issues/414
=> doc: Add documentation for integrating new language

src/fuzz_introspector/analysis.py, src/fuzz_introspector/constants.py, src/fuzz_introspector/html_report.py
Fixes: https://github.com/ossf/fuzz-introspector/issues/406
=> report: add numeric representation of calltree

src/fuzz_introspector/analysis.py, src/fuzz_introspector/datatypes/branch_profile.py, src/fuzz_introspector/datatypes/function_profile.py, src/fuzz_introspector/utils.py
Fixed multiple issues with function name mangling causing branch blocker detection failure to load correct function profile. More details re https://github.com/ossf/fuzz-introspector/issues/312#issuecomment-1203274901
=> Fix function name inconsistency across coverage and profile

src/fuzz_introspector/html_helpers.py
Fixes: https://github.com/ossf/fuzz-introspector/issues/427
=> html: fix coverage URLs

src/fuzz_introspector/analysis.py, src/fuzz_introspector/code_coverage.py
In a C/C++ coverage report the line info is categorized based on the function name. This PR checks if a line in a given function is hit or not.
Fixes #441
=> Check for the line hit for fall through branch sides

.github/workflows/testing.yml, requirements.txt
=> Unittest CI: Generate and display coverage report

build_all.sh, doc/LocalBuild.md
and also update doc/LocalBuild.md.
Some scripts are still out of sync with the new layout and the documentation but they can probably be fixed later.
=> build_all: make the custom clang buildable again

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
Extract callsite information about each callsite found in the module.
This is in contrast to existing logic that only extracts callsite
information about callsite in the calltree.
Needed for: https://github.com/ossf/fuzz-introspector/issues/447
Perhaps down the line it makes sense to remove calltree creation logic
to outside the LLVM module and instead rely on data extracted like this.
=> frontends: llvm: extract all callsite information

src/fuzz_introspector/styling/styles.css
=> Fix per-fuzzer coverage dropdown issue

src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/utils.py, src/test/test_utils.py
=> Fix refine_path bug: Use python os library and change logic

src/fuzz_introspector/datatypes/project_profile.py
Add missing path indicator "/"
Fixes: #455
=> Refine-path bug: 

src/fuzz_introspector/analyses/function_call_analyser.py
Adds filtering in function call analyser to look for specific sinks.
=> plugins: refine function call analyser

frontends/python/main.py
Fix bug for creating new Third Party API call coverage analyser.
Solve a bug for: #447
=> Fix bug in function profile changes

.github/workflows/cflite_pr.yml
=> Fix fuzzer CI starting criteria

src/fuzz_introspector/html_report.py
Simplifies the calltree section in an effort to reduce noise in the
reports
=> html_report: refine the calltree section

oss_fuzz_integration/oss-fuzz-patches.diff
=> oss-fuzz: update patches for python integration

oss_fuzz_integration/get_full_coverage.py
Adds the possibility to specify --corpus-dir to get_full_coverage.py.
Example usage: `../run_both.sh htslib 5 --corpus-dir=./corpus-11`
The folderp pointed to by --corpus-dir must have the same structure as
it would under build/corpus/proj_name/..
=> oss-fuzz: make it possible to specify corpus

src/fuzz_introspector/code_coverage.py
Fixes: https://github.com/ossf/fuzz-introspector/issues/492
=> src: only use relevant coverage profiles

src/fuzz_introspector/analysis.py
=> Write all branch blockers to the summary

src/fuzz_introspector/analysis.py
Addresses https://github.com/ossf/fuzz-introspector/issues/312#issuecomment-1244788743
=> Use a blocklist to skip functions for branch complexity

.github/workflows/scorecards-analysis.yml
=> Fix scorecard CI failures.

README.md
Included Scorecard badge
Signed-off-by: Naveen <172697+naveensrinivasan@users.noreply.github.com>
=> Update README.md to include scorecard badge

oss_fuzz_integration/runner.py
Downloads the public OSS-Fuzz corpus for a project in coverage or introspector modes when --download-public-corpus is passed.
Fixes: https://github.com/ossf/fuzz-introspector/issues/452
=> oss-fuzz: enable downloading public OSS-Fuzz corpus

oss_fuzz_integration/runner.py
This is in preparation of fixing
https://github.com/ossf/fuzz-introspector/issues/486
=> oss-fuzz: enable running without coverage collection

src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/analyses/runtime_coverage_analysis.py, src/fuzz_introspector/commands.py, src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/html_report.py
Fixes: https://github.com/ossf/fuzz-introspector/issues/486
=> avoid displaying coverage analysis when no coverage

doc/CaseStudies.md
Signed-off-by: Julien Voisin <jvoisin@google.com>
=> Add a case study about `file`

src/fuzz_introspector/data_loader.py, src/fuzz_introspector/datatypes/fuzzer_profile.py
=> data_loader: minor refactoring

oss_fuzz_integration/README.md
Signed-off-by: Thuan Pham <thuan.pham@unimelb.edu.au>
=> Fix wrong script name

frontends/python/main.py, src/fuzz_introspector/code_coverage.py, src/fuzz_introspector/datatypes/fuzzer_profile.py
Ref:
https://github.com/AdaLogics/PyCG/commit/e2a1e2a6fe32dd597e31de7e41b3f17c1c703ed7
More work to come here
=> frontend: python: load lines for the asts in each function

src/fuzz_introspector/styling/custom.js
=> Enable selecting rows in functions table

.github/workflows/cflite_pr.yml, .github/workflows/codeql.yml, .github/workflows/depsreview.yaml
To follow security best practices.
=> ci: pin dependencies

frontends/java/soot/pom.xml, frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionElement.java
Related to step 3 of Issue #536
=> [Java-Integration]: Match callgraph display to fuzz-introspector

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
=> llvm: enable setting log leve from env

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
=> frontends: llvm: cleanup allocated memory

frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
Related to Step 3~4 of issue #536 
=> Fix callgraph and extra info logic

oss_fuzz_integration/oss-fuzz-patches.diff
For easy testing of Soot build CG generation process on oss-fuzz project.
Related to Step 4~5 of Issue #536 
=> [Java-Integration]: Link project jackson-databind for fuzz-introspector

oss_fuzz_integration/oss-fuzz-patches.diff
Fix bug in PR #572 
Related to Step 4~5 of Issue #536 
=> [Java Integration]: Fix bug

src/fuzz_introspector/datatypes/function_profile.py, src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/utils.py
There is some work to do here, since we have blocking in arbitrary places and this should be centralised. I will open an issue on that next.
=> Refine reachability and all-project functions table

oss_fuzz_integration/oss-fuzz-patches.diff
Recent updates in project/jackson-databind/build.sh causes a diff issue
=> oss-fuzz: fix patch

oss_fuzz_integration/oss-fuzz-patches.diff
Following https://github.com/google/oss-fuzz/pull/8865
=> oss-fuzz: update diffs

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
@Navidem Could you review?
Signed-off-by: AdamKorcz <adam@adalogics.com>
=> remove debugging

oss_fuzz_integration/oss-fuzz-jvm-build-patches.diff
Related to step 4 of issue #536 
=> [Java-Integration]: Add patch to build.sh for jvm project

tests/java/runTest.sh, tests/java/test1/.config, tests/java/test10/.config, tests/java/test11/.config, tests/java/test12/.config, tests/java/test12/TestFuzzer.java, tests/java/test12/build.sh, tests/java/test13/.config, tests/java/test14/.config, tests/java/test2/.config, tests/java/test3/.config, tests/java/test4/.config, tests/java/test5/.config, tests/java/test6/.config, tests/java/test7/.config, tests/java/test8/.config, tests/java/test9/.config
Fix test cases config and add batch testing for the soot CFG generation code.
Related to Step 4~5 of issue #536
=> [Java Integration] - Jvm test case

frontends/python/main.py
This enables more data to be included in the static analysis, which is needed to produce reports for google cloud projects amongst others.
=> frontends: python: scan file tree instead of one up

src/fuzz_introspector/data_loader.py
Ref: https://github.com/ossf/fuzz-introspector/issues/585
=> data_loader: multi-thread profile loading.

frontends/java/README.md, frontends/java/soot/run.sh, frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/yaml/BranchProfile.java, frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/yaml/BranchSide.java, frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionConfig.java, frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionElement.java, frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/yaml/FuzzerConfig.java, oss_fuzz_integration/oss-fuzz-jvm-build-patches.diff, tests/java/runTest.sh
Step 5~6 of issue #536 
Trying to match the output of soot with the frontends code of fuzz-introspector.
=> [Java-Integration]: Match frontends

src/fuzz_introspector/code_coverage.py, src/fuzz_introspector/utils.py
=> switch some logging from info to debug

doc/CaseStudies.md
Signed-off-by: Steven Wirsz <swirsz@gmail.com>
=> Add case study for bzip2

src/fuzz_introspector/utils.py
Needed for projects that have "linux" in the name.
Fixes: https://github.com/ossf/fuzz-introspector/issues/598
=> utils: fix per-target coverage link

oss_fuzz_integration/oss-fuzz-patches.diff
This is no longer needed due to the recent Python improvements.
=> oss-fuzz: cleanup .diff

src/fuzz_introspector/code_coverage.py, src/fuzz_introspector/datatypes/fuzzer_profile.py
=> convert more logging from info to debug

frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, oss_fuzz_integration/oss-fuzz-jvm-build-patches.diff
Fix bug left in PR #588 
Related to issue #536
=> [Java-Integration]: Fix bug

src/fuzz_introspector/utils.py, src/test/test_utils.py
Ref: https://github.com/ossf/fuzz-introspector/issues/598
=> tests: add url per-target testcase

frontends/java/soot/run.sh, frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, src/fuzz_introspector/analyses/engine_input.py, src/fuzz_introspector/analysis.py, src/fuzz_introspector/cfg_load.py, src/fuzz_introspector/datatypes/function_profile.py, src/fuzz_introspector/datatypes/fuzzer_profile.py, src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/html_helpers.py, src/fuzz_introspector/html_report.py, src/fuzz_introspector/utils.py
Create jvm branch for handling jvm based project on fuzz-introspector html report generation.
Related to issue #536
=> [Java-Integration]: Create Jvm branch for fuzz-introspector html report

frontends/python/prepare_fuzz_imports.py
Fixes an issue from several oss-fuzz projects, e.g.
- https://oss-fuzz-build-logs.storage.googleapis.com/log-0f66f5ea-f573-49c3-92f7-b348dbe63f56.txt
g-api-python-firestore and mako are example projects affected.
=> frontend: python: fix call instruction resolution

frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
Fix error logic for standard library exclusion.
Related to issue https://github.com/ossf/fuzz-introspector/issues/536
Fixing bugs from PR https://github.com/ossf/fuzz-introspector/pull/604
=> [Java Integration]: Fix error logic for standard library exclusion

frontends/java/soot/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java, src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/cfg_load.py, src/fuzz_introspector/datatypes/fuzzer_profile.py
Fix error logic to allow proper display of call graph for JVM branch
Related to issue #536 
Fixing bugs from PR #604
=> [Java-integration]: Fix Callgraph display

README.md
This is to make it easier for users to get a quick understanding of the support for the languages.
Signed-off-by: DavidKorczynski <david@adalogics.com>
=> README: add some links to projects of different languages

.github/workflows/google-java.yml, .github/workflows/jvm-test.yml, .github/workflows/main.yml, .github/workflows/mypy.yml, .github/workflows/testing.yml
Perform some CI only on pull request.
=> Fix CI running criteria

src/fuzz_introspector/datatypes/fuzzer_profile.py, src/fuzz_introspector/html_helpers.py
Fix wrong jvm call site link resolve.
Solving issue #629 
=> [JVM Bug] Fix link resolve

src/fuzz_introspector/datatypes/fuzzer_profile.py, src/fuzz_introspector/utils.py
=> [JVM issue] Add code to patch line number of jacoco source report

src/fuzz_introspector/datatypes/fuzzer_profile.py
Fixing callsite link error mentioned in #629 
=> [Java issue] Fix subclass link bug

frontends/python/main.py
=> frontends: python: refine cli

.github/workflows/jvm-unit-test.yml, frontends/java/pom.xml, frontends/java/run.sh, frontends/java/src/test/java/ossf/fuzz/intropsector/soot/CustomSenceTransformerTest.java
Create basic test CI and add in sample junit class for demonstration of CI unit testing / building testing on java frontends code. Will add in more Junit test case later.
Related to one of the request changes mentioned in Issue #629.
=> [JVM issue] Add unit test / build test CI

oss_fuzz_integration/runner.py
It should make it possible to build FI reports for projects with relatively new fuzz targets whose corpora haven't been made public yet.
Fixes
```
Fuzz targets: ['test_blkid_fuzz', 'test_mount_fuzz', 'test_last_fuzz', 'test_fdisk_script_fuzz']
--2022-11-29 14:05:25--  https://storage.googleapis.com/util-linux-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/util-linux_test_blkid_fuzz/public.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 64.233.165.128, 64.233.161.128, 74.125.131.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|64.233.165.128|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-11-29 14:05:26 ERROR 403: Forbidden.
Traceback (most recent call last):
File …
```
=> runner: ignore failed attempts to download corpora

oss_fuzz_integration/runner.py
Further patch additional location missed from PR #640 , related to dead link mentioned in issue #629.
=> [JVM Issue] Patch missing dead link

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
Add logic to sort class name
Fix error logic which accidentally exclude wanted classes
Related to issue #629
=> [JVM Issue] Fix logic

oss_fuzz_integration/runner.py
=> JVM-Issue: Fix bug for wrong link removal

oss_fuzz_integration/runner.py
Fix reversed logic bug
Related to issue #629 
=> Java-Issue: Fix logic bug

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp, src/fuzz_introspector/analysis.py, src/fuzz_introspector/datatypes/branch_profile.py, src/test/test_branch_profile.py
Refactor the branch profiler to accept multi-way branches.
This PR prepares for adding the switch statements support.
=> Generalize branch profiler

src/test/test_code_coverage.py
=> Unit-Testing: Add new test case for jvm code coverage

src/test/test_jvm_report_generation.py
Fix bugs from PR #663
Issue #630 
=> Unit Testing: Fix bug

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp, src/fuzz_introspector/analysis.py, src/fuzz_introspector/code_coverage.py, src/test/data/sample_cov.covreport, src/test/test_code_coverage.py
Following #657, this PR adds support for switch statements when identifying branch blockers.
=> Support Switch Statements for branch blockers

src/fuzz_introspector/code_coverage.py, src/test/data/sample_cov.covreport, src/test/test_code_coverage.py
Fixes #672
Signed-off-by: Navid Emamdoost <navid.emamdoost@gmail.com>
=> Load coverage hitcount

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
This is particularly focused on tracing which files/classes/methods are used/discarded for analysis. This is useful in a context of e.g. https://github.com/ossf/fuzz-introspector/issues/683
Ref: https://github.com/ossf/fuzz-introspector/issues/681
=> frontends: java: add improve logging

src/fuzz_introspector/json_report.py
=> json_report: bug fix

src/fuzz_introspector/analysis.py
Addressing https://github.com/google/oss-fuzz/issues/9209#issuecomment-1352241356
A replacement for temporary solution in #691
Signed-off-by: Navid Emamdoost <navid.emamdoost@gmail.com>
=> Add sanity checks to capture potential out-of bounds index

src/fuzz_introspector/code_coverage.py, src/test/data/sample_cov.covreport, src/test/test_code_coverage.py
Signed-off-by: Navid Emamdoost <navid.emamdoost@gmail.com>
=> Support loading coverage lines with billions hitcount

src/fuzz_introspector/analyses/engine_input.py, src/main.py
=> Json report: Add json code generation for engine analyser

.github/workflows/cflite_pr.yml, .github/workflows/codeql.yml, .github/workflows/google-java.yml, .github/workflows/scorecards-analysis.yml
The workflow of this repository is to do everything through pull requests.
=> workflows: run only on pull, not push

src/fuzz_introspector/analyses/sinks_analyser.py
Fix bug on function name comparison.
Issue #670 
=> Sink Coverage: Fix naming bug for sink analyser

.clusterfuzzlite/build.sh, .github/workflows/cflite_pr.yml, src/test/fuzz/test_fuzz_cfg_load.py, src/test/fuzz/test_fuzz_report_generation.py
Avoid instrumenting in reproducer runs.
=> test: fuzz: use hack to make CIFuzz able to reproduce

src/fuzz_introspector/analyses/sinks_analyser.py
Fix logic to display fuzzer coverage of sink method.
Issue #670 
=> Sink Coverage Report: Fix fuzzer coverage logic

.clusterfuzzlite/build.sh, .github/workflows/cflite_pr.yml, src/fuzz_introspector/html_report.py, src/test/fuzz/test_fuzz_report_generation.py
=> speed up cifuzz build

oss_fuzz_integration/test_projects.py
=> oss-fuzz: extend test_projects.py to handle failing coverage builds

tests/java/test11/TestFuzzer.java
=> Unit testing: Fix formatting

frontends/java/oss-fuzz-main.py
Fix bug of missing single quote for string with semicolon.
=> jvm implementation: Fix bug

src/fuzz_introspector/analyses/sinks_analyser.py
Fix bug of empty call site handling.
=> Sink Analyser: Fix empty callsite bug

oss_fuzz_integration/README.md
To reflect the latest changes in OSS-Fuzz `infra/helper.py`.
=> Update instructions for using with OSS-Fuzz

src/fuzz_introspector/analyses/sinks_analyser.py, src/fuzz_introspector/utils.py
Fix sink and all other function naming
=> Sink Coverage Fix naming issue

doc/sphinx/source/analyses.rst, doc/sphinx/source/core.rst, doc/sphinx/source/profiles.rst
=> doc: improve sphinx docs

build_all.sh
=> build_all: remove unused directories in binutils

code_checks.sh
=> fix code_checks to work with most recent set up

src/fuzz_introspector/analyses/sinks_analyser.py
=> Sink analser: Fix typo and add missing identification information for sink functions

doc/sphinx/source/oss-fuzz/index.rst
=> docs: sphinx: add OSS-Fuzz guides

src/fuzz_introspector/html_report.py
=> html_report: improve coverage percentage ui

doc/sphinx/source/user-guides/index.rst
=> doc: sphinx: minor nits

src/fuzz_introspector/analyses/sinks_analyser.py, src/fuzz_introspector/datatypes/function_profile.py, src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/utils.py
=> Sink Analyser: Showing callpath for sink functions

doc/sphinx/source/user-guides/comparing-introspector-reports.rst
=> doc: sphinx: add user guide for report diffing

doc/sphinx/source/index.rst, doc/sphinx/source/user-guides/index.rst
=> docs: sphinx: improve wording

frontends/java/oss-fuzz-main.py
=> Fix OSS-Fuzz call for Java

src/fuzz_introspector/analyses/sinks_analyser.py, src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/utils.py
=> Sink Analyser: Pretty print callpath result

src/fuzz_introspector/analyses/sinks_analyser.py
Let's not show the HTML for now unless in development. It's still WIP. Also removes some sinks as I think they will provide too much noise for now.
=> sink analyser: silence HTML for now and refine

README.md
Signed-off-by: DavidKorczynski <david@adalogics.com>
=> README: update docs description

src/fuzz_introspector/analyses/sinks_analyser.py, src/fuzz_introspector/utils.py
Fix empty callpath index out of bound bug.
=> Sink analyser: Fix index out of bound bug

src/fuzz_introspector/analyses/sinks_analyser.py
=> Sink Analyser: Fix typo

frontends/python/main.py
=> frontends: python: extract classes and inheritance information

.github/workflows/main.yml, requirements.txt, src/fuzz_introspector/analyses/__init__.py, src/fuzz_introspector/analyses/bug_digestor.py, src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/analyses/driver_synthesizer.py, src/fuzz_introspector/analyses/engine_input.py, src/fuzz_introspector/analyses/filepath_analyser.py, src/fuzz_introspector/analyses/function_call_analyser.py, src/fuzz_introspector/analyses/metadata.py, src/fuzz_introspector/analyses/optimal_targets.py, src/fuzz_introspector/analyses/runtime_coverage_analysis.py, src/fuzz_introspector/analyses/sinks_analyser.py
Flake8 and mypy are doing nice jobs, but we would like more strict code formatting to ensure consistency.
=> CI: add yapf python formatter for analyses

src/fuzz_introspector/analyses/bug_digestor.py, src/fuzz_introspector/analyses/driver_synthesizer.py, src/fuzz_introspector/analyses/engine_input.py, src/fuzz_introspector/analyses/filepath_analyser.py, src/fuzz_introspector/analyses/function_call_analyser.py, src/fuzz_introspector/analyses/metadata.py, src/fuzz_introspector/analyses/optimal_targets.py, src/fuzz_introspector/analyses/runtime_coverage_analysis.py, src/fuzz_introspector/analyses/sinks_analyser.py, src/fuzz_introspector/html_helpers.py, src/fuzz_introspector/html_report.py
=> add heading enum

src/fuzz_introspector/analyses/bug_digestor.py, src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/analyses/driver_synthesizer.py, src/fuzz_introspector/analyses/engine_input.py, src/fuzz_introspector/analyses/filepath_analyser.py, src/fuzz_introspector/analyses/function_call_analyser.py, src/fuzz_introspector/analyses/metadata.py, src/fuzz_introspector/analyses/optimal_targets.py, src/fuzz_introspector/analyses/runtime_coverage_analysis.py, src/fuzz_introspector/analyses/sinks_analyser.py, src/fuzz_introspector/analysis.py, src/fuzz_introspector/html_helpers.py, src/fuzz_introspector/html_report.py
To make the code more readable
=> Make table of content class type rather than list

.github/workflows/main.yml, src/fuzz_introspector/analysis.py, src/fuzz_introspector/cfg_load.py, src/fuzz_introspector/code_coverage.py, src/fuzz_introspector/commands.py, src/fuzz_introspector/constants.py, src/fuzz_introspector/data_loader.py, src/fuzz_introspector/datatypes/branch_profile.py, src/fuzz_introspector/datatypes/bug.py, src/fuzz_introspector/datatypes/function_profile.py, src/fuzz_introspector/datatypes/fuzzer_profile.py, src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/diff_report.py, src/fuzz_introspector/html_helpers.py, src/fuzz_introspector/html_report.py, src/fuzz_introspector/json_report.py, src/fuzz_introspector/utils.py
=> make main directory follow yapf code style

src/fuzz_introspector/datatypes/project_profile.py
Ref: https://github.com/ossf/fuzz-introspector/issues/796
=> project-profile: include more data in summary output

src/fuzz_introspector/datatypes/project_profile.py
=> project-profile: minor refactoring

src/fuzz_introspector/datatypes/project_profile.py
=> project-profile: write target language to output json

doc/sphinx/source/user-guides/analyse-sink-function.rst
=> sphinx: Fix typo

oss_fuzz_integration/project_checker.py
=> oss-fuzz integration: clean up project checker

src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/analyses/optimal_targets.py, src/fuzz_introspector/commands.py, src/fuzz_introspector/constants.py, src/fuzz_introspector/html_report.py, src/fuzz_introspector/json_report.py, tools/auto-fuzz/manager.py
This is needed for converting it into a library.
Ref: https://github.com/ossf/fuzz-introspector/issues/835
=> only dump files when needed

src/fuzz_introspector/constants.py, src/fuzz_introspector/html_report.py
Code simplification and refactoring.
Working towards https://github.com/ossf/fuzz-introspector/issues/835
=> html_report: refactor

src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/html_report.py
=> html-report: simplify percentage graph creations

src/fuzz_introspector/html_helpers.py, src/fuzz_introspector/html_report.py
=> html-report: simply and refactor

src/fuzz_introspector/analyses/optimal_targets.py, src/fuzz_introspector/constants.py, src/fuzz_introspector/html_report.py, src/fuzz_introspector/styling/__init__.py
=> make style files into constants

src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/analyses/function_call_analyser.py, src/fuzz_introspector/analyses/sinks_analyser.py, src/fuzz_introspector/analysis.py, src/fuzz_introspector/datatypes/fuzzer_profile.py, src/fuzz_introspector/html_report.py
Removing non-html logic from `html_report.py` and refactoring.
=> refactoring and cleaning up

tools/auto-fuzz/base_files.py, tools/auto-fuzz/constants.py, tools/auto-fuzz/fuzz_driver_generation_jvm.py, tools/auto-fuzz/manager.py
Generalize some of the function for multiple language of the auto fuzzer generation tool.
Add in JVM branch for the auto fuzzer generation tool.
=> Autofuzz: JVM branch

src/fuzz_introspector/html_report.py
=> html-report: minor refactoring

src/fuzz_introspector/html_constants.py, src/fuzz_introspector/html_helpers.py, src/fuzz_introspector/html_report.py
Reduce complexity of `html_report.py`
=> html-report: refactoring

src/fuzz_introspector/datatypes/fuzzer_profile.py, src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/html_helpers.py, src/fuzz_introspector/html_report.py
Preparing for https://github.com/ossf/fuzz-introspector/issues/835
=> refactoring

tools/auto-fuzz/README.md
Fix command arguments and description.
=> Auto-fuzz Fix readme

tools/auto-fuzz/fuzz_driver_generation_jvm.py, tools/auto-fuzz/manager.py
Following the change in PR #875, this PR create heuristic 8 to handle non-static method calls which use enum object as part of its arguments.
=> Auto-fuzz: Heuristic8 for java

tools/auto-fuzz/manager.py
Fix wrong permission for gradle wrapper for gradle project.
=> Auto-fuzz: Fix permission error

src/fuzz_introspector/html_helpers.py, src/fuzz_introspector/html_report.py
simplifying the code in preparation of https://github.com/ossf/fuzz-introspector/issues/835
=> html-report: refactor

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Fix map retrieval type error in handling enum checking.
=> Auto-fuzz: Fix type bug

src/fuzz_introspector/analyses/calltree_analysis.py, src/fuzz_introspector/analyses/sinks_analyser.py, src/fuzz_introspector/html_helpers.py, src/fuzz_introspector/html_report.py
=> htlm-report: refactor

tools/auto-fuzz/base_files.py, tools/auto-fuzz/fuzz_driver_generation_jvm.py
Some of the object creation can be done by referring to public static final class variable defined in that class. These methods allow the class developer to create some default settings objects. Following PR #889, this additional information is provided and this PR applies them for object creation in the new heuristic 9 in order to make use of default of preconfigured objects from their original class.
=> Auto-fuzz: Add Heuristic 9 for java

src/fuzz_introspector/analysis.py, src/fuzz_introspector/commands.py, src/fuzz_introspector/html_report.py
The goal is to make all of the features accessible without generating the HTML report.
Ref: https://github.com/ossf/fuzz-introspector/issues/835
=> introduce a new analysis abstraction

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Fix bug of missing handling of possible none type object.
=> Auto-fuzz: Fix None type bug

src/fuzz_introspector/data_loader.py
The existing multiprocessing is based on threads and due to Python GIL it seems that they do not actually use multi-processing. Switching this so it becomes true multi-processing.
=> data_loader: fix multi-processing

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Fix bug for missing possible_target parameter for one of the function call.
=> Auto-fuzz: Fix missing parameter bug

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Fix missing arguments for function call.
=> Auto-fuzz: Fix missing arguments

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Fix error is missed check for enum object handling.
=> Auto-fuzz: Fix missing check for enum object

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Fix a bug for wrong variable name used.
=> Auto-fuzz: Fix wrong variable name bug

tools/auto-fuzz/manager.py
Fix logic for subfolder searching for build property.
=> Auto-fuzz: Fix logic for searching subfolder

tools/auto-fuzz/manager.py
Fix sub-directory searching for some non-standard project setting.
=> Auto-fuzz: Fix logic for subdirectory searching

tools/auto-fuzz/manager.py
Fix wrong condition on jar searching.
=> Auto-fuzz: Fix wrong jar searching bug

tools/auto-fuzz/fuzz_driver_generation_jvm.py
As java frontend logic will take all classes in dependency for data.yaml generation which the auto-fuzz generation is based on. Thus the resulting fuzzer generated by the java heuristic includes lots of the methods in the dependencies instead of the target project. This PR adds in filtering logic to check if the source file for the class of a specific method does exist in the target project directory. If not, it is filtered out and not handled by the fuzzer generation process.
=> Auto-fuzz: Add target method filter

tools/auto-fuzz/base_files.py
This PR makes changes in the base builder and base fuzzer for the java fuzzer generation process to prepare for the merging operation which could have multiple fuzzers generated in separate folder merge into a single folder with many fuzzer class and a single build script and docker file.
=> Auto-fuzz: Fix base file for java

tools/auto-fuzz/manager.py, tools/auto-fuzz/post_process.py
This PR changes the logic for the folder merging operation to support java projects.
=> Auto-fuzz: Add merge logic for java project

tools/web-fuzzing-introspection/app/site/models.py, tools/web-fuzzing-introspection/app/site/routes.py, tools/web-fuzzing-introspection/app/site/templates/project-profile.html
keeping as draft -- will go over this again tomorrow
=> web-app: convert .svg figures to javascript plots

tools/web-fuzzing-introspection/app/site/models.py, tools/web-fuzzing-introspection/app/site/routes.py, tools/web-fuzzing-introspection/app/site/templates/function-profile.html, tools/web-fuzzing-introspection/app/site/templates/function-search.html, tools/web-fuzzing-introspection/app/site/templates/index.html, tools/web-fuzzing-introspection/app/site/templates/project-profile.html, tools/web-fuzzing-introspection/app/site/templates/projects-overview.html, tools/web-fuzzing-introspection/app/site/test_data.py
keeping as draft for now as I'll apply a similar pattern for all the other relevant places.
=> webapp: add project timestamp modelling

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Filtering demo classes and methods.
=> Auto-fuzz: Filter demo classes and methods

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Heuristic 1 is used to generate fuzzers for all static method which could be merged into a single fuzzing target. This PR merge all possible static public methods in the project to one single fuzzer output target.
=> Auto-fuzz: Merge heuristic 1

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Fix logic and bug for the following:
- Ignore non-public / non-concrete classes, following changes in #993 
- Fix bug for array handling
- Fix size for primitive array
- Add primitive type checking method
- Fix error when no object creation is found
- Fix exception catching order
=> Auto-fuzz: Fix bug and logic

src/fuzz_introspector/datatypes/project_profile.py
Fixes: https://github.com/ossf/fuzz-introspector/issues/973
=> project-profile: fix code coverage summary calculation

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
- Make it multithreaded
- Do not process all components when not needing them. We only need full details about functions and branch blockers for the last analysis.
=> webapp: make db creator faster

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
The logic for merging method omitted some of the deeper method call. This PR fixes the merging logic.
=> Java frontend: Fix logic for method merging

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
Java frontend uses a StringBuilder to store up the full string of the call tree when it extracts that information recursively from the Soot Calltree object. It will then write the string in the StringBuilder to the data file. But if the call tree is so large, the StringBuilder will reach its maximum capacity and throw a HeapOverflowError. This PR changes the logic by writing the call tree line directly to the file without pile them up in the StringBuilder. This could solve the possible HeapOverflowError for project with large and long call tree.
=> Java frontend: Fix java heap overflow

tools/auto-fuzz/fuzz_driver_generation_jvm.py
This PR fixes a bug on wrong object calling for class field retrieval and saving.
=> Auto-fuzz: Fix object error

tools/auto-fuzz/fuzz_driver_generation_jvm.py
This PR fixes a bug on wrong max target control in fuzzer generation heuristic method.
=> Auto-fuzz: Fix bug in max target control

tools/auto-fuzz/README.md
This PR adds the description of the benchmark option into the README.
=> Add benchmark option desciprtion to README

tools/auto-fuzz/fuzz_driver_generation_jvm.py
This PR fixes the logic for discovering method that needed to be filtered.
=> Auto-Fuzz: Fix logic in filtering

tools/auto-fuzz/fuzz_driver_generation_jvm.py, tools/auto-fuzz/post_process.py
This PR fixes a bug in handling array type during fuzzer generation and post processing.
=> Auto-Fuzz: Fix logic for array type

tools/web-fuzzing-introspection/app/static/assets/db/.gitignore, tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py, tools/web-fuzzing-introspection/app/webapp/routes.py, tools/web-fuzzing-introspection/app/webapp/templates/project-profile.html
This allows removing the github cache as well.
=> webapp: use cache from introspector.oss-fuzz.com and minor bug fix

frontends/java/src/main/java/ossf/fuzz/introspector/soot/CallGraphGenerator.java
As mentioned in https://github.com/soot-oss/soot/issues/1200. it is possible to get a RuntimeException when some virtual interface method is being invoked. The soot version we use will still have this problem. Fortunately it is happened in the stage after our main analysing logic. Thus it is OK to ignore it if we confirm the analysis has completed. This PR fixes the logic to capture the exception and only throw it out if the analysis is not completed.
=> Java-Frontend: Fix possible runtime exception after analysis

tools/auto-fuzz/post_process.py
This PR fixes the post processing of auto-fuzz. A new function "csv" is added. When calling
```
python3 ./post_processing.py csv
```
The post processing with generate a list of csv result which contains where is the fail, and the top fuzzer stats.
=> Auto-Fuzz: Fix post processing

tools/auto-fuzz/post_process.py
This PR fixes the csv result of post processing.
=> Auto-Fuzz: Fix csv result

tools/auto-fuzz/base_files.py
This PR fixes possible errors in project build property discovery.
=> Auto-fuzz: Fix base build file

tools/auto-fuzz/base_files.py
This PR fixes the base file of the generated fuzzing project.
=> Auto-fuzz: Fix base file

tools/auto-fuzz/fuzz_driver_generation_jvm.py
This PR fixes the method extraction and filtering logic to avoid flooding the memory with too much data when handling big project.
=> Auto-fuzz: Fix method extraction and filtering

tools/auto-fuzz/base_files.py, tools/auto-fuzz/fuzz_driver_generation_jvm.py
This PR fixes the auto-fuzz logic to consider File or Path type parameters and include preparation of files in the code logic.
=> Auto-fuzz: Add file or path handling

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Fix bug for wrong parameter name.
=> Auto-fuzz: Fix name bug

tools/auto-fuzz/base_files.py, tools/auto-fuzz/constants.py, tools/auto-fuzz/manager.py
This PR fixes the ant build and jar discovery to accomondate multiple java version support in #1160.
=> Auto-fuzz: Fix ant build and jar discovery

tools/auto-fuzz/fuzz_driver_generation_jvm.py
Fix filtering logic to avoid NoneType calling error and extract some wanted target from the list.
=> Auto-fuzz: Fix filtering logic problem

tools/auto-fuzz/fuzz_driver_generation_jvm.py
This PR fixes a bug in determine if filtering is needed for method candidates.
=> Auto-Fuzz: Fix generate heuristic bug

src/main.py
This will enable some more projects to build, e.g. libpg_query: https://oss-fuzz-build-logs.storage.googleapis.com/log-3a897689-9d22-4170-bc0d-df398a74de61.txt
=> core: set deeper recursion limit

src/fuzz_introspector/analysis.py, src/fuzz_introspector/data_loader.py, src/fuzz_introspector/datatypes/fuzzer_profile.py
This should help speed up the post processing when a given project has a lot of fuzzers
Ref: https://github.com/ossf/fuzz-introspector/issues/585
CC @jonathanmetzman
=> post-process: enable multi processing in various places

tools/auto-fuzz/manager.py
This PR fixes an executable problem of maven build.
=> Auto-fuzz: Fix maven executable problem

tools/web-fuzzing-introspection/app/webapp/routes.py, tools/web-fuzzing-introspection/app/webapp/templates/api.html, tools/web-fuzzing-introspection/app/webapp/templates/base.html
=> webapp: add API page

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py, tools/web-fuzzing-introspection/app/webapp/__init__.py, tools/web-fuzzing-introspection/app/webapp/models.py, tools/web-fuzzing-introspection/app/webapp/routes.py
Adds additional information to the branch blocker API
=> webapp: extend branch blocker API

tools/web-fuzzing-introspection/app/webapp/routes.py, tools/web-fuzzing-introspection/app/webapp/templates/project-profile.html
This is an effort to show minor insights from fuzz introspector on the project profile page. I think the key is here to only show the best advice.
=> webapp: show top functions to fuzz on project page

tools/auto-fuzz/manager.py, tools/auto-fuzz/templates/jvm-ant/build.sh-template, tools/auto-fuzz/templates/jvm-gradle/build.sh-template, tools/auto-fuzz/templates/jvm-maven/build.sh-template
This PR removes the fuzzer build logics from manager.py and reuse the project build jar for static analysis.
=> Auto-fuzz: Remove fuzzer build in manager.py

tools/auto-fuzz/base_files.py, tools/auto-fuzz/templates/python-introspector/build.sh-template, tools/auto-fuzz/templates/python-introspector/fuzz_1.py, tools/auto-fuzz/templates/python-introspector/project.yaml
This PR adds oss-fuzz templates for python static analysis using fuzz-introspector.
=> Auto-fuzz: Add template for python static analysis

tools/auto-fuzz/fuzzer_generator/fuzz_driver_generation_java.py, tools/auto-fuzz/fuzzer_generator/fuzz_driver_generation_python.py, tools/auto-fuzz/objects/fuzz_target.py
This PR is not working and still need bug fixing.
=> Auto-Fuzz: Extract Fuzz Target from generator

tools/auto-fuzz/c-cpp/build-generator.py
Compartmentalise things more, with the goal of making it easier to add features in some part of the pipeline. Still stuff to do here in follow-up PRs
=> auto-fuzz: refactor c/cpp

tools/auto-fuzz/fuzzer_generator/fuzz_driver_generation_java.py
The heuristic 2~4 of the auto-fuzz fuzzer generation for Java projects are very similar. All of them target non-static methods in the project which requires object creation before the target method call. The only difference between the three heuristics is the approach they use for object creation. Given the similarity of the three heuristics, this PR combines them into a single heuristic which includes all three approaches of target object creation to reduce code redundancy.
=> Auto-fuzz: Combine heuristic 2-4 for java fuzzer generation

tools/auto-fuzz/fuzzer_generator/fuzz_driver_generation_java.py
Following #1291, this PR further merges heuristic 2 and 6 to reduce code redundancy.
=> Auto-fuzz: Combine heuristic 2 and 6 for Java fuzzer generation

frontends/java/src/main/java/ossf/fuzz/introspector/soot/utils/CalculationUtils.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/utils/CalltreeUtils.java
This PR adds comments to utils method in utils classes.
=> Java-frontend: Add comments to Utils classes

frontends/java/src/main/java/ossf/fuzz/introspector/soot/SootSceneTransformer.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/utils/EdgeUtils.java, tests/java/test11/.config
This PR follows #1301. This PR extract the final bit of those utils method to utils package.
=> Java-frontend: Extract method for edge processing

tools/web-fuzzing-introspection/app/webapp/routes.py, tools/web-fuzzing-introspection/app/webapp/templates/target-oracle.html
This heuristic shows a target based on argument types (char*, int) which are often used in functions which handles a given buffer with a size argument. Has roughly 200 hits for the dataset.
=> webapp: add new heuristic

tools/auto-fuzz/fuzzer_generator/docker/Dockerfile
This PR creates a dockerfile for building a custom docker image. The custom docker image will be used for the fuzzer generator for different language to avoid the need to installed specific python package.
=> Auto-fuzz: Create dockerfile for fuzzer generator

tools/web-fuzzing-introspection/app/webapp/templates/target-oracle.html
This exists in various places, will address them later though.
=> webapp: fix accummulate --> accumulate typo

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py, tools/web-fuzzing-introspection/app/webapp/routes.py, tools/web-fuzzing-introspection/app/webapp/templates/api.html
A few names where missed in the #1319 refactor. This should complete the refactor.
Ref: #1318
=> web_app: Fix inconsistent naming

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py, tools/web-fuzzing-introspection/app/webapp/routes.py, tools/web-fuzzing-introspection/app/webapp/templates/api.html, tools/web-fuzzing-introspection/app/webapp/templates/project-profile.html
Ref: https://github.com/ossf/fuzz-introspector/issues/1318#issuecomment-1825153926
=> webapp: api: fix typo: src_file -> source_file

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
Ref: https://github.com/ossf/fuzz-introspector/issues/1335
=> webapp: ues gh cache to restore history

src/fuzz_introspector/analyses/sinks_analyser.py
This PR is the second PR for revamping the Sink Analyser. This PR changes the logic to analyse all CWE in the data list for the given project.
=> Sink analyser: support multiple CWE sink function analyse

src/fuzz_introspector/analyses/sinks_analyser.py
This PR fixes the callgraph handling and generation logic to avoid duplicated callgraph generation.
=> Sink Analyser: Fix redundant callgraph

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
`clang-format -i ./frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp`
=> frontends: llvm: fix formatting

src/fuzz_introspector/analysis.py, src/fuzz_introspector/constants.py
For projects with debug information copy the source code files to a dedicated folder.
Minor bug fixes.
=> src: copy source files to report directory

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
Fixes: https://github.com/ossf/fuzz-introspector/issues/1390
=> frontends: llvm: extract more types

src/fuzz_introspector/datatypes/function_profile.py, src/fuzz_introspector/html_report.py
This was added in the frontend, but had not yet propagated to the post processing part.
=> summar.json: add function line number endings

tools/auto-fuzz/fuzzer_generator/fuzz_driver_generation_python.py, tools/auto-fuzz/templates/fuzzer-generator/Dockerfile-template
This PR fixes a bug in fuzzer generation for python project which missed an import statement causing python auto-fuzz failing.
=> Auto-fuzz: Fix python generation bug

tools/auto-fuzz/README.md, tools/auto-fuzz/post_process.py
=> Auto-fuzz: Fix README.md and make command for post-process.py mandatory

tools/oss-fuzz-scanner/post_processor_lib.py
This was made possible with the recent fuzz introspector oss-fuzz bump
=> oss-fuzz-scanner: use precise function line numbers

tools/web-fuzzing-introspection/app/static/assets/db/constants.py, tools/web-fuzzing-introspection/app/static/assets/db/oss_fuzz.py, tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
Make the code more modular, e.g. logic can be shared between modules/other tools as well.
=> webapp: refactor to modularize

tools/web-fuzzing-introspection/app/static/assets/db/oss_fuzz.py, tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
Refactor the DB creation and fix a bug when extracting project language (introduced yesterday).
=> web: refactor and bug fix

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
To follow is adjustment of APIs
=> webapp: introduce function signature as unique key

tools/web-fuzzing-introspection/app/webapp/__init__.py, tools/web-fuzzing-introspection/app/webapp/models.py, tools/web-fuzzing-introspection/app/webapp/routes.py
Keeping it as draft until the rest of the APIs are migrated
=> webapp: introduce function signature as key in APIs

tools/web-fuzzing-introspection/app/static/assets/db/oss_fuzz.py, tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py, tools/web-fuzzing-introspection/app/webapp/routes.py
Enable lookups of the raw DWARF debug information.
=> webapp: add API for recursive DWARF debug lookup

doc/sphinx/source/conf.py
Per the [formation instructions ](https://docs.google.com/document/d/12CUj2FbMzdYS34jVfLBVgV39xyeMcs13np-h28qe19M/edit) we need to also make sure the copywriter is correct on the website.
=> Added new copywrite

frontends/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp
Adds analysis of  composite types to extract e.g. size of arrays and identification of base types for arrays. Base types are now always set for a debug element, where previously they weren't and local variable values could carry over.
=> frontends: llvm: debug info: improve analysis of derived types

tools/auto-fuzz/constants.py, tools/auto-fuzz/fuzzer_generator/fuzz_driver_generation_java.py, tools/auto-fuzz/manager.py, tools/auto-fuzz/utils.py
`generate_possible_targets` now takes an additional argument
=> auto-fuzz: fix java build

tools/auto-fuzz/constants.py, tools/auto-fuzz/fuzzer_generator/fuzz_driver_generation_java.py
Also adds a heuristic that does some basic filtering, e.g. force analysis of functions with specific names.
=> auto-fuzz: java: extend with additional prompt

tools/web-fuzzing-introspection/app/webapp/routes.py
Previously it only looked for the `parse`, this extends it to additional fuzz keywords
=> web: extend oracle 1

src/fuzz_introspector/analysis.py, src/fuzz_introspector/debug_info.py
Fixes: https://github.com/google/oss-fuzz/issues/11706
=> debug_info: cleanup expensive loop

tools/web-fuzzing-introspection/app/main.py, tools/web-fuzzing-introspection/app/static/assets/db/oss_fuzz.py, tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py, tools/web-fuzzing-introspection/app/webapp/routes.py
This is to make it easier to test changes and how they impact oss-fuzz-gen.
=> Enable web-app to be run against local OSS-Fuzz

src/fuzz_introspector/analysis.py, src/fuzz_introspector/constants.py, src/fuzz_introspector/datatypes/project_profile.py, src/fuzz_introspector/html_report.py, src/fuzz_introspector/json_report.py, tools/web-fuzzing-introspection/app/static/assets/db/oss_fuzz.py, tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
This will improve the speed of creating the DB in the webapp significantly, since we don't always have to download large summary.json files.
=> separate all function list out from `summary.json`

scripts/oss-fuzz-gen-e2e/run_all.sh
This causes issues with reusing of containers.
=> oss-fuzz-gen-e2e: ensure no parallel executions

tools/web-fuzzing-introspection/app/webapp/routes.py
Add an API to the webapp for querying constructors of project.
=> [webapp] Add constructor api

frontends/java/pom.xml, frontends/java/src/main/java/ossf/fuzz/introspector/soot/SootSceneTransformer.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/utils/GenericUtils.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionElement.java, frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/JavaMethodInfo.java
This PR aims to analyse the java source file and locate any generic types of method arguments and return value. This could help further process and understanding of the method.
=> Add possible generic types of java methods

tools/web-fuzzing-introspection/app/static/assets/db/oss_fuzz.py, tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py, tools/web-fuzzing-introspection/app/webapp/__init__.py, tools/web-fuzzing-introspection/app/webapp/models.py, tools/web-fuzzing-introspection/app/webapp/routes.py
Extract the data and make it available as an API as well
=> webapp: expose project repository

tools/web-fuzzing-introspection/app/webapp/__init__.py, tools/web-fuzzing-introspection/app/webapp/routes.py
This PR removes two undefined functions called.
=> webapp: Remove undefined functions

tools/web-fuzzing-introspection/app/webapp/data_storage.py
Add typing hints for the data storage list.
=> webapp: Add typing for data storage list

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR tries to remove redundant variables in the code to avoid confusion. This is part of the work to fulfil the type checking when type is added in #1583.
=> webapp: Remove redundant variables

tools/web-fuzzing-introspection/app/static/assets/db/launch_minor_oss_fuzz.sh
Also only analyse a single day
=> webapp: make launch_minor start from today's date

tools/web-fuzzing-introspection/app/webapp/__init__.py, tools/web-fuzzing-introspection/app/webapp/data_storage.py
This PR adds typing in `__init__.py` and `data_storage.py`. This PR is one of the smaller PR separated from #1583.
=> webapp: Add typing to __init__.py and data_storage.py

tools/web-fuzzing-introspection/app/webapp/models.py
This PR adds typing to models.py. This PR is one of the smaller PR separated from #1583.
=> webapp: Add typing to models.py

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR fixes more None type checking introduced by recent PRs. This is part of the work to fulfil the type checking when type is added in #1601.
=> webapp: Fix more None type checking

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR removes an unused function. This function has been moved to function_helper in #1558 and should be removed.
=> webapp: Remove unused function

frontends/java/src/main/java/ossf/fuzz/introspector/soot/yaml/FunctionElement.java, src/fuzz_introspector/datatypes/function_profile.py, src/fuzz_introspector/html_report.py
This PR adds exceptions in the json output for all functions and constructors.
=> Java: Add exceptions information of methods

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py, tools/web-fuzzing-introspection/app/webapp/__init__.py, tools/web-fuzzing-introspection/app/webapp/helper/function_helper.py, tools/web-fuzzing-introspection/app/webapp/models.py
This PR adds logic to retrieve exceptions information from fuzz-introspector json output and add them to the function models for further process and output.
=> webapp: Add exceptions handling to function model

src/fuzz_introspector/datatypes/function_profile.py, src/fuzz_introspector/html_report.py
This PR adds additional java method static information into the resulting json report.
=> JVM: Add static information for methods

tools/web-fuzzing-introspection/app/webapp/__init__.py, tools/web-fuzzing-introspection/app/webapp/helper/function_helper.py, tools/web-fuzzing-introspection/app/webapp/routes.py
This PR adds a new API for searching functions that return a given variable type. This could provide more information for oss-fuzz-gen prompt generation on how to create certain needed object for fuzzing.
=> webapp: Add new API for searching functions that return needed variable type

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
Improves performance using lookups instead
=> webappp: remove double for loop in db creation

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
Also optimize some json calls into orjson calls
=> webapp: add timed logging to DB creation

src/fuzz_introspector/analysis.py, src/fuzz_introspector/constants.py, src/fuzz_introspector/html_report.py
First go keeping it as simple as possible
Ref: https://github.com/google/oss-fuzz-gen/issues/494
=> core: find and store test files

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR fixes the source code retrieval functions when line_begin and line_end is invalid or undefined.
=> webapp: Fix source code retrieving logic

tools/web-fuzzing-introspection/app/webapp/data_storage.py, tools/web-fuzzing-introspection/app/webapp/routes.py
=> web: remove many uses of get_all_functions

tools/web-fuzzing-introspection/app/webapp/data_storage.py
We do not want to use these functions anymore anyways. They are too resource intensive.
=> web: clean up unused functions

scripts/oss-fuzz-gen-e2e/README.md
Give details on how to use `web_run_all.sh`
=> oss-fuzz-gen: extend README

src/fuzz_introspector/analysis.py
Avoid some bazel-specific conditions
=> analysis: add another disabled test dir

tools/web-fuzzing-introspection/requirements.txt
=> webapp: update requests

src/fuzz_introspector/analysis.py, src/fuzz_introspector/constants.py, src/fuzz_introspector/html_report.py
This will help detect targets for e.g. Bazel builds.
=> add logic to extracting all sources from a project

src/fuzz_introspector/analysis.py, src/fuzz_introspector/html_report.py, src/fuzz_introspector/utils.py
This PR extracts a list of test and example source files from JVM projects and copy them to the inspector report for reference.
=> JVM: Copy test source files to inspector report

tools/web-fuzzing-introspection/app/webapp/helper/function_helper.py, tools/web-fuzzing-introspection/app/webapp/routes.py
This PR adds a new API for querying all publicly accessible classes of a project.
=> webapp: Add api for querying all public classes of projects

src/fuzz_introspector/analysis.py, src/fuzz_introspector/html_report.py, src/fuzz_introspector/utils.py
This PR fixes the logic of the extract_all_sources function to also handles source files for other languages.
=> Python/JVM: Copy source files for python project

tools/web-fuzzing-introspection/app/webapp/routes.py
This is based on file extension counting.
Ref: https://github.com/google/oss-fuzz-gen/pull/643
=> webapp: add API for getting project language

.pylintrc
Follows the OFG style, with a few changes e.g. indentation
=> add pylint

oss_fuzz_integration/oss-fuzz-patches.diff
=> oss-fuzz: fix patches

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
=> webdb: simplify web db creator

oss_fuzz_integration/build_all_custom_images.sh
This PR fixes a naming bug of the jvm docker image build in OSS-Fuzz-integration script.
=> OSS-Fuzz-Integration: Fix naming bug

frontends/rust/rust_function_analyser/src/main.rs
Fix a bug that wrong env crate has been used in main.rs.
=> [Rust]: Fix bug

src/fuzz_introspector/analysis.py, src/fuzz_introspector/code_coverage.py, src/fuzz_introspector/json_report.py
=> core: minor styling

frontends/light/install-deps.sh, frontends/light/src/main.py
Adds pure static analysis frontend. More work to do here, but the direction seems clear.
=> frontends: add light initial set up

oss_fuzz_integration/oss-fuzz-patches.diff, src/fuzz_introspector/analysis.py, src/fuzz_introspector/commands.py, src/main.py
This PR fixes the light analysis to include other language supported by FI.
=> Add light analysis for other language

tools/web-fuzzing-introspection/app/webapp/helper/function_helper.py
This PR fixes a bug for the all-public-classes api to remove inner class inclusion.
=> webapp: Fix bugs on inner class name

tools/web-fuzzing-introspection/app/webapp/helper/function_helper.py
This PR fixes the public class extraction to exclude non-class names from the set.
=> webapp: Fix public class extraction

src/fuzz_introspector/analyses/annotated_cfg.py
Correctly identify path of fuzzers for JVM project in annotated-cfg dict.
=> [JVM] Fix source file searching for jvm

src/fuzz_introspector/frontends/src/frontend_c.py, src/fuzz_introspector/frontends/src/frontend_cpp.py, src/fuzz_introspector/frontends/src/oss_fuzz.py, src/pyproject.toml
Still a lot of work to do for cpp
=> light: introduce poc cpp

src/fuzz_introspector/frontends/src/frontend_cpp.py
including scope identification
=> light: improve cpp calltree extraction

oss_fuzz_integration/oss-fuzz-patches.diff
This PR fixes the oss-fuzz-path after changes in OSS-Fuzz compile script.
=> Fix oss-fuzz patch

src/fuzz_introspector/frontends/src/oss_fuzz.py
This is to do such that other tools can easily use `oss_fuzz.analyse_folder` and call into the fuzz introspector frontend, without using the CLI.
=> core: frontend: make oss_fuzz entrypoint API friendly

src/fuzz_introspector/frontends/src/frontend_go.py, src/fuzz_introspector/frontends/src/oss_fuzz.py
This PR fixes the output for go frontend.
=> [Go] Fix frontend output

oss_fuzz_integration/build_all_custom_images.sh, oss_fuzz_integration/build_post_processing.sh, oss_fuzz_integration/oss-fuzz-patches.diff
This PR fixes the patch and oss-fuzz-integration for golang project.
=> [Go] Fix oss-fuzz-integration for go

src/fuzz_introspector/frontends/oss_fuzz.py
This PR fixes a missing change from #1889.
=> core: frontend: Fix bug in frontend

src/fuzz_introspector/frontends/frontend_cpp.py
=> core: cpp frontend

src/fuzz_introspector/frontends/oss_fuzz.py
This PR simplify the logic for c calltree generation.
=> [frontend] Simplify redundant logic for C calltree

src/fuzz_introspector/frontends/oss_fuzz.py, src/fuzz_introspector/utils.py
=> [Go] Fix call tree go

src/fuzz_introspector/analysis.py
This PR adds handling of source file copying for golang.
=> [Go] Add go extension to source file copying

oss_fuzz_integration/oss-fuzz-patches.diff, src/fuzz_introspector/frontends/core.py, src/fuzz_introspector/frontends/frontend_jvm.py, src/fuzz_introspector/frontends/oss_fuzz.py, src/pyproject.toml
This is the preliminary approach to create the jvm frontend with the tree-sitter.
**This PR is still in progress and not yet ready for review.**
=> Frontend-JVM: Add new frontend for jvm using tree-sitter

src/fuzz_introspector/code_coverage.py, src/fuzz_introspector/datatypes/fuzzer_profile.py
This PR fixes the backend entrypoint identification for supporting new JVM frontend.
=> [JVM] Fix entry method discovery

oss_fuzz_integration/oss-fuzz-patches.diff
This PR fixes the oss-fuzz-patch to accommodate the test for new JVM frontend.
=> [JVM] Fix oss-fuzz-patch for new jvm frontend

src/fuzz_introspector/frontends/frontend_jvm.py, src/main.py
This PR fixes the frontend_jvm to match the mypy CI  checking requirements.
=> [JVM] Fix mypy error for frontend-jvm

src/fuzz_introspector/analysis.py, src/fuzz_introspector/datatypes/function_profile.py, src/fuzz_introspector/html_report.py
This PR fixes the signature extraction directly from data yaml files if exists.
=> Add function signature

src/fuzz_introspector/frontends/frontend_cpp.py, src/fuzz_introspector/frontends/oss_fuzz.py
This PR fixes the tree-sitter frontend for cpp project.
**This PR is still in progress and are not yet ready for review.**
=> frontend-cpp: Fix tree-sitter frontend for cpp

tests/tree-sitter-frontend/cpp/test-project-2/crossfile.cpp, tests/tree-sitter-frontend/cpp/test-project-2/fuzzer.cpp, tests/tree-sitter-frontend/cpp/test-project-2/recursive.cpp, tests/tree-sitter-frontend/cpp/test-project-2/sample.h, tests/tree-sitter-frontend/cpp/test-project-3/deep_chain.cpp, tests/tree-sitter-frontend/cpp/test-project-3/deep_chain.hpp, tests/tree-sitter-frontend/cpp/test-project-4/deep_nested.cc, tests/tree-sitter-frontend/cpp/test-project-4/deep_nested.hpp, tests/tree-sitter-frontend/test-tree-sitter-frontend.py
This PR adds 3 more testing project for tree-sitter frontend unit test in C++.
=> [CI] Add more CI unit test for tree-sitter frontend (C++)

.gitignore, src/fuzz_introspector/frontends/frontend_cpp.py, src/fuzz_introspector/frontends/oss_fuzz.py, src/test/test_tree_sitter_frontend.py
This should be propagated in the other languages as well, but will do that in follow-up PRs in the coming days.
=> core: tests: do not dump files during tests

src/fuzz_introspector/frontends/frontend_rust.py, src/test/data/source-code/rust/test-project-1/fuzzer.rs, src/test/test_frontends_rust.py
This PR adds in the unit testing logic for rust tree-sitter frontend.
=> [Frontend-rust] Add unit test for rust

src/.vscode/settings.json, src/fuzz_introspector/frontends/frontend_cpp.py, src/test/data/source-code/cpp/test-project-6/sample.cpp, src/test/test_frontends_cpp.py
Capture namespace and class more accurately
=> core: frontends: cpp: improve scoping analysis

src/fuzz_introspector/frontends/frontend_rust.py, src/test/data/source-code/rust/test-project-1/fuzzer.rs, src/test/data/source-code/rust/test-project-2/fuzzer.rs, src/test/data/source-code/rust/test-project-2/math.rs, src/test/test_frontends_rust.py
This PR adds in one more rust unit testing sample and fix a bug on missed handling of macro_definition on top of macro invocation.
=> [Frontend-Rust] More rust testing

src/fuzz_introspector/frontends/frontend_cpp.py
Add support for mixing C files in cpp projects
=> core: frontends: cpp: support mixing C files

src/test/data/source-code/rust/test-project-5/fuzzer.rs, src/test/data/source-code/rust/test-project-5/recursive.rs, src/test/test_frontends_rust.py
This PR adds unit test for recursive and triat implementation for frontend rust.
=> [Frontend-Rust] Add test for recursive and triat implementation

src/fuzz_introspector/frontends/frontend_cpp.py, src/test/data/source-code/cpp/test-project-7/sample.h, src/test/data/source-code/cpp/test-project-7/sample1.cpp, src/test/data/source-code/cpp/test-project-7/sample2.cpp, src/test/test_frontends_cpp.py
we had a regression on this recently but this fixes it.
=> core: frontends: cpp: fix handling multiple harnesses in one

src/test/data/source-code/rust/test-project-8/combination.rs, src/test/data/source-code/rust/test-project-8/fuzzer.rs, src/test/test_frontends_rust.py
This PR adds a complex combined unit test for rust tree-sitter frontend.
=> [Frontend-rust] Add combined unit test for rust

src/fuzz_introspector/frontends/frontend_rust.py, src/test/data/source-code/rust/test-project-9/fuzzer_one.rs, src/test/data/source-code/rust/test-project-9/fuzzer_two.rs, src/test/test_frontends_rust.py
This PR adds a new set of unit test for rust frontend with multiple entrypoints. This PR also fixes a bugs in handling multiple entry points.
=> [Frontend-Rust] Add unit test for multiple entry points and fix bug

src/fuzz_introspector/frontends/frontend_go.py, src/test/data/source-code/go/test-project-2/fuzzer.go, src/test/test_frontends_go.py
This PR adds in a second unit test on function call identification from variable types. It also revamp the frontend for go to add in variable type determination for identifying the correct function calls.
=> [Frontend-go] Add unit test and fix bug on variable naming

src/fuzz_introspector/frontends/frontend_go.py, src/test/data/source-code/go/test-project-5/fuzzer.go, src/test/test_frontends_go.py
This PR adds a new unit test on shared interface object type detection.
=> [Frontend-go] Add interface unit test

src/fuzz_introspector/analyses/optimal_targets.py, src/fuzz_introspector/commands.py, src/fuzz_introspector/frontends/frontend_c.py
Extracted the linenumber from the wrong node
=> core: frontends: c: fix line number for functions and add basic block counter

src/test/data/source-code/go/test-project-7/fuzzer.go, src/test/data/source-code/go/test-project-7/package/package.go, src/test/test_frontends_go.py
This PR adds an unit test for cross file module function call.
=> [Frontend-go] Add unit-test for cross file module call

src/test/data/source-code/go/test-project-9/fuzzer_one.go, src/test/data/source-code/go/test-project-9/fuzzer_two.go, src/test/data/source-code/go/test-project-9/others.go, src/test/test_frontends_go.py
This PR adds new unit test of multiple entry points for golang.
=> [Frontend-go] Unit test for multiple entry point

src/test/data/source-code/go/test-project-8/fuzzer.go, src/test/test_frontends_go.py
Add new unit test for combined example.
=> [Frontend-go] Add unit testing on combined sample

tools/web-fuzzing-introspection/app/static/assets/db/web_db_creator_from_summary.py
We have a regression causing projects not to be analysed. This fixes it.
=> web: adjust DB creation

src/fuzz_introspector/utils.py
Fix PyLint for fuzz_introspector/utils.py
=> [CI] Fix PyLint error for utils.py

src/fuzz_introspector/frontends/frontend_rust.py
This PR fixes the pylint error for frontend-rust.
=> pylint: Fix pylint error for frontend-rust

src/fuzz_introspector/analyses/far_reach_low_coverage_analyser.py, src/fuzz_introspector/analyses/source_code_line_analyser.py, src/fuzz_introspector/datatypes/function_profile.py
This PR fixes the function dict output for standalone analyser to match the API result from webapp.
=> analyser: Fix function dict to match webapp output

src/fuzz_introspector/frontends/frontend_go.py
This PR fixes the mypy and pyline error for frontend_go.
=> pylint: Fix pylint error for frontend_go

src/fuzz_introspector/frontends/core.py
This PR fixes the pylint for frontends/core.py
=> pylint: Fix pylint for frontend/core

src/fuzz_introspector/frontends/frontend_jvm.py
This PR fixes the pylint and mypy errors for frontend_jvm.
=> pylint: Fix mypy and pylint for frontend_jvm

src/fuzz_introspector/analyses/far_reach_low_coverage_analyser.py, src/fuzz_introspector/analyses/public_candidate_analyser.py, src/fuzz_introspector/analyses/source_code_line_analyser.py, src/fuzz_introspector/analysis.py, src/fuzz_introspector/commands.py
This PR adds second entrrypoint function for standalone analyser to avoid passing in unnecessary parameters.
=> analyser: Separate entrypoint for standalone analysis

src/fuzz_introspector/analyses/__init__.py, src/fuzz_introspector/analyses/far_reach_low_coverage_analyser.py, src/fuzz_introspector/analyses/source_code_line_analyser.py, src/fuzz_introspector/commands.py
This PR fixes the standalone analyser by adding default value to some properties to allow the analyser executable from library module.
=> Analyser: Add default value to standlone analyser

src/fuzz_introspector/commands.py
This PR fixes a bug for missing entrypoint name for rust projects.
=> Rust: Fix entrypoint for rust projects

src/fuzz_introspector/frontends/datatypes.py, src/fuzz_introspector/frontends/frontend_c.py, src/fuzz_introspector/frontends/frontend_cpp.py, src/fuzz_introspector/frontends/frontend_go.py, src/fuzz_introspector/frontends/frontend_jvm.py, src/fuzz_introspector/frontends/frontend_rust.py
This PR generalises report generation functions in Project class.
=> Frontend: Generalise report generation functions

README.md, tools/web-fuzzing-introspection/README.md
Ref: https://github.com/ossf/fuzz-introspector/pull/2087
=> READMEs: document python versioning

src/fuzz_introspector/frontends/datatypes.py, src/fuzz_introspector/frontends/frontend_c.py, src/fuzz_introspector/frontends/frontend_go.py, src/fuzz_introspector/frontends/frontend_jvm.py, src/fuzz_introspector/frontends/oss_fuzz.py
This PR fixes the pylint/mypy errors for FI frontends.
=> pylint/mypy: Fix pylint/mypy errors for frontends

src/fuzz_introspector/frontends/datatypes.py, src/fuzz_introspector/frontends/frontend_c.py, src/fuzz_introspector/frontends/oss_fuzz.py
- specific improvements in C for report caching
- use CDumper from yaml
=> core: frontends: improve performance

src/fuzz_introspector/frontends/frontend_cpp.py
Return values are part of the func sig
=> frontend: cpp: fix signature definition

requirements.txt, src/pyproject.toml
Ref: https://github.com/ossf/fuzz-introspector/issues/2125
Supersedes https://github.com/ossf/fuzz-introspector/pull/2126
=> bump pyyaml

doc/LocalBuild.md, requirements.txt, tests/build_all_projects.sh, tests/build_simple_example.sh, tests/python/run_tests.sh, tests/run_simple_tests.sh
This PR resolves errors encountered during the report generation phase as outlined in [LocalBuild.md](https://github.com/ossf/fuzz-introspector/blob/main/doc/LocalBuild.md)(./build_simple_example.sh). These changes ensure the report is generated reliably in local builds.
=> Fix issues during report generation step

src/fuzz_introspector/analyses/test_file_analyser.py, src/fuzz_introspector/cli.py
This PR fixes the logic for the newly added test_file_analyser to include cross referenced functions from each of the test/example files discovered in the target project.
=> analyser: Fix logic of test file analyser

tools/web-fuzzing-introspection/app/webapp/routes.py
To enable returning test files from OFG projects.
=> webapp: weaken test file constraints

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR adds a new API in the webapps for extracting test files content from function cross reference, following #2146.
=> webapps: Add new api for test files xref

tools/web-fuzzing-introspection/app/webapp/routes.py
This PR fixes a bug related to a non-serialisable set type in the resulting dictionary.
=> webapp: Fix typing bug

src/fuzz_introspector/frontends/datatypes.py, src/fuzz_introspector/frontends/oss_fuzz.py
This PR simply the tree-sitter frontend by generalise the logic for C projects with other languages.
=> frontend-c: Generalise C frontend logic with other languages

src/fuzz_introspector/frontends/datatypes.py, src/fuzz_introspector/frontends/frontend_c.py
This PR adds extraction logic of macro conditional blocks in C projects using tree-sitter.
=> frontend-c: Extract macro condition blocks for C project

src/fuzz_introspector/frontends/datatypes.py, src/fuzz_introspector/frontends/frontend_c.py, src/fuzz_introspector/frontends/frontend_cpp.py, src/fuzz_introspector/frontends/frontend_go.py, src/fuzz_introspector/frontends/frontend_jvm.py, src/fuzz_introspector/frontends/frontend_rust.py
This PR fixes some of the mypy check error in the frontend. 
There exists some CI error for formatting in other code, which is ignored from this PR and will be fixed in later PRs.
=> mypy: Fix mypy type check

tools/web-fuzzing-introspection/app/static/assets/db/oss_fuzz.py
This PR fixes formatting issue in the logic.
=> Fix formatting

src/fuzz_introspector/frontends/frontend_c_cpp.py
This PR adds handling of macro function definition in the C/C++ tree-sitter frontend.
=> frontend-c-cpp: Extraction Function def macro
